// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/enums/ad_group_ad_status.proto

package enums

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The possible statuses of an AdGroupAd.
type AdGroupAdStatusEnum_AdGroupAdStatus int32

const (
	// No value has been specified.
	AdGroupAdStatusEnum_UNSPECIFIED AdGroupAdStatusEnum_AdGroupAdStatus = 0
	// The received value is not known in this version.
	//
	// This is a response-only value.
	AdGroupAdStatusEnum_UNKNOWN AdGroupAdStatusEnum_AdGroupAdStatus = 1
	// The ad group ad is enabled.
	AdGroupAdStatusEnum_ENABLED AdGroupAdStatusEnum_AdGroupAdStatus = 2
	// The ad group ad is paused.
	AdGroupAdStatusEnum_PAUSED AdGroupAdStatusEnum_AdGroupAdStatus = 3
	// The ad group ad is removed.
	AdGroupAdStatusEnum_REMOVED AdGroupAdStatusEnum_AdGroupAdStatus = 4
)

var AdGroupAdStatusEnum_AdGroupAdStatus_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "UNKNOWN",
	2: "ENABLED",
	3: "PAUSED",
	4: "REMOVED",
}

var AdGroupAdStatusEnum_AdGroupAdStatus_value = map[string]int32{
	"UNSPECIFIED": 0,
	"UNKNOWN":     1,
	"ENABLED":     2,
	"PAUSED":      3,
	"REMOVED":     4,
}

func (x AdGroupAdStatusEnum_AdGroupAdStatus) String() string {
	return proto.EnumName(AdGroupAdStatusEnum_AdGroupAdStatus_name, int32(x))
}

func (AdGroupAdStatusEnum_AdGroupAdStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_137acffc11908561, []int{0, 0}
}

// Container for enum describing possible statuses of an AdGroupAd.
type AdGroupAdStatusEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdGroupAdStatusEnum) Reset()         { *m = AdGroupAdStatusEnum{} }
func (m *AdGroupAdStatusEnum) String() string { return proto.CompactTextString(m) }
func (*AdGroupAdStatusEnum) ProtoMessage()    {}
func (*AdGroupAdStatusEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_137acffc11908561, []int{0}
}
func (m *AdGroupAdStatusEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdGroupAdStatusEnum.Unmarshal(m, b)
}
func (m *AdGroupAdStatusEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdGroupAdStatusEnum.Marshal(b, m, deterministic)
}
func (m *AdGroupAdStatusEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdGroupAdStatusEnum.Merge(m, src)
}
func (m *AdGroupAdStatusEnum) XXX_Size() int {
	return xxx_messageInfo_AdGroupAdStatusEnum.Size(m)
}
func (m *AdGroupAdStatusEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_AdGroupAdStatusEnum.DiscardUnknown(m)
}

var xxx_messageInfo_AdGroupAdStatusEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AdGroupAdStatusEnum)(nil), "google.ads.googleads.v0.enums.AdGroupAdStatusEnum")
	proto.RegisterEnum("google.ads.googleads.v0.enums.AdGroupAdStatusEnum_AdGroupAdStatus", AdGroupAdStatusEnum_AdGroupAdStatus_name, AdGroupAdStatusEnum_AdGroupAdStatus_value)
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/enums/ad_group_ad_status.proto", fileDescriptor_137acffc11908561)
}

var fileDescriptor_137acffc11908561 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4b, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x4f, 0x4c, 0x29, 0xd6, 0x87, 0x30, 0x41, 0xac, 0x32, 0x03, 0xfd, 0xd4, 0xbc,
	0xd2, 0xdc, 0x62, 0xfd, 0xc4, 0x94, 0xf8, 0xf4, 0xa2, 0xfc, 0xd2, 0x82, 0xf8, 0xc4, 0x94, 0xf8,
	0xe2, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x59, 0x88, 0x62,
	0xbd, 0xc4, 0x94, 0x62, 0x3d, 0xb8, 0x3e, 0xbd, 0x32, 0x03, 0x3d, 0xb0, 0x3e, 0xa5, 0x1c, 0x2e,
	0x61, 0xc7, 0x14, 0x77, 0x90, 0x4e, 0xc7, 0x94, 0x60, 0xb0, 0x3e, 0xd7, 0xbc, 0xd2, 0x5c, 0xa5,
	0x50, 0x2e, 0x7e, 0x34, 0x61, 0x21, 0x7e, 0x2e, 0xee, 0x50, 0xbf, 0xe0, 0x00, 0x57, 0x67, 0x4f,
	0x37, 0x4f, 0x57, 0x17, 0x01, 0x06, 0x21, 0x6e, 0x2e, 0xf6, 0x50, 0x3f, 0x6f, 0x3f, 0xff, 0x70,
	0x3f, 0x01, 0x46, 0x10, 0xc7, 0xd5, 0xcf, 0xd1, 0xc9, 0xc7, 0xd5, 0x45, 0x80, 0x49, 0x88, 0x8b,
	0x8b, 0x2d, 0xc0, 0x31, 0x34, 0xd8, 0xd5, 0x45, 0x80, 0x19, 0x24, 0x11, 0xe4, 0xea, 0xeb, 0x1f,
	0xe6, 0xea, 0x22, 0xc0, 0xe2, 0xb4, 0x90, 0x91, 0x4b, 0x31, 0x39, 0x3f, 0x57, 0x0f, 0xaf, 0x9b,
	0x9c, 0x44, 0xd0, 0xac, 0x0e, 0x00, 0x79, 0x24, 0x80, 0x71, 0x11, 0x13, 0xb3, 0xbb, 0xa3, 0xe3,
	0x2a, 0x26, 0x59, 0x77, 0x88, 0x6e, 0xc7, 0x94, 0x62, 0x3d, 0x08, 0x13, 0xc4, 0x0a, 0x33, 0xd0,
	0x03, 0xb9, 0xbc, 0xf8, 0x14, 0x4c, 0x3e, 0xc6, 0x31, 0xa5, 0x38, 0x06, 0x2e, 0x1f, 0x13, 0x66,
	0x10, 0x03, 0x96, 0x7f, 0x44, 0x40, 0x3e, 0x89, 0x0d, 0x1c, 0x6e, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0x1c, 0x68, 0xa5, 0x71, 0x01, 0x00, 0x00,
}
