// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/enums/page_one_promoted_strategy_goal.proto

package enums

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum describing possible strategy goals.
type PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal int32

const (
	// Not specified.
	PageOnePromotedStrategyGoalEnum_UNSPECIFIED PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal = 0
	// Used for return value only. Represents value unknown in this version.
	PageOnePromotedStrategyGoalEnum_UNKNOWN PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal = 1
	// First page on google.com.
	PageOnePromotedStrategyGoalEnum_FIRST_PAGE PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal = 2
	// Top slots of the first page on google.com.
	PageOnePromotedStrategyGoalEnum_FIRST_PAGE_PROMOTED PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal = 3
)

var PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "UNKNOWN",
	2: "FIRST_PAGE",
	3: "FIRST_PAGE_PROMOTED",
}

var PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal_value = map[string]int32{
	"UNSPECIFIED":         0,
	"UNKNOWN":             1,
	"FIRST_PAGE":          2,
	"FIRST_PAGE_PROMOTED": 3,
}

func (x PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal) String() string {
	return proto.EnumName(PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal_name, int32(x))
}

func (PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_71f12f7e453a451d, []int{0, 0}
}

// Container for enum describing possible strategy goals: where impressions are
// desired to be shown on search result pages.
type PageOnePromotedStrategyGoalEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageOnePromotedStrategyGoalEnum) Reset()         { *m = PageOnePromotedStrategyGoalEnum{} }
func (m *PageOnePromotedStrategyGoalEnum) String() string { return proto.CompactTextString(m) }
func (*PageOnePromotedStrategyGoalEnum) ProtoMessage()    {}
func (*PageOnePromotedStrategyGoalEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_71f12f7e453a451d, []int{0}
}
func (m *PageOnePromotedStrategyGoalEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageOnePromotedStrategyGoalEnum.Unmarshal(m, b)
}
func (m *PageOnePromotedStrategyGoalEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageOnePromotedStrategyGoalEnum.Marshal(b, m, deterministic)
}
func (m *PageOnePromotedStrategyGoalEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageOnePromotedStrategyGoalEnum.Merge(m, src)
}
func (m *PageOnePromotedStrategyGoalEnum) XXX_Size() int {
	return xxx_messageInfo_PageOnePromotedStrategyGoalEnum.Size(m)
}
func (m *PageOnePromotedStrategyGoalEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_PageOnePromotedStrategyGoalEnum.DiscardUnknown(m)
}

var xxx_messageInfo_PageOnePromotedStrategyGoalEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PageOnePromotedStrategyGoalEnum)(nil), "google.ads.googleads.v0.enums.PageOnePromotedStrategyGoalEnum")
	proto.RegisterEnum("google.ads.googleads.v0.enums.PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal", PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal_name, PageOnePromotedStrategyGoalEnum_PageOnePromotedStrategyGoal_value)
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/enums/page_one_promoted_strategy_goal.proto", fileDescriptor_71f12f7e453a451d)
}

var fileDescriptor_71f12f7e453a451d = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x4e, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x4f, 0x4c, 0x29, 0xd6, 0x87, 0x30, 0x41, 0xac, 0x32, 0x03, 0xfd, 0xd4, 0xbc,
	0xd2, 0xdc, 0x62, 0xfd, 0x82, 0xc4, 0xf4, 0xd4, 0xf8, 0xfc, 0xbc, 0xd4, 0xf8, 0x82, 0xa2, 0xfc,
	0xdc, 0xfc, 0x92, 0xd4, 0x94, 0xf8, 0xe2, 0x92, 0xa2, 0xc4, 0x92, 0xd4, 0xf4, 0xca, 0xf8, 0xf4,
	0xfc, 0xc4, 0x1c, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x59, 0x88, 0x4e, 0xbd, 0xc4, 0x94,
	0x62, 0x3d, 0xb8, 0x21, 0x7a, 0x65, 0x06, 0x7a, 0x60, 0x43, 0x94, 0xda, 0x19, 0xb9, 0xe4, 0x03,
	0x12, 0xd3, 0x53, 0xfd, 0xf3, 0x52, 0x03, 0xa0, 0xc6, 0x04, 0x43, 0x4d, 0x71, 0xcf, 0x4f, 0xcc,
	0x71, 0xcd, 0x2b, 0xcd, 0x55, 0x4a, 0xe1, 0x92, 0xc6, 0xa3, 0x44, 0x88, 0x9f, 0x8b, 0x3b, 0xd4,
	0x2f, 0x38, 0xc0, 0xd5, 0xd9, 0xd3, 0xcd, 0xd3, 0xd5, 0x45, 0x80, 0x41, 0x88, 0x9b, 0x8b, 0x3d,
	0xd4, 0xcf, 0xdb, 0xcf, 0x3f, 0xdc, 0x4f, 0x80, 0x51, 0x88, 0x8f, 0x8b, 0xcb, 0xcd, 0x33, 0x28,
	0x38, 0x24, 0x3e, 0xc0, 0xd1, 0xdd, 0x55, 0x80, 0x49, 0x48, 0x9c, 0x4b, 0x18, 0xc1, 0x8f, 0x0f,
	0x08, 0xf2, 0xf7, 0xf5, 0x0f, 0x71, 0x75, 0x11, 0x60, 0x76, 0x5a, 0xcb, 0xc8, 0xa5, 0x98, 0x9c,
	0x9f, 0xab, 0x87, 0xd7, 0xbd, 0x4e, 0x0a, 0x78, 0x5c, 0x12, 0x00, 0xf2, 0x70, 0x00, 0xe3, 0x22,
	0x26, 0x66, 0x77, 0x47, 0xc7, 0x55, 0x4c, 0xb2, 0xee, 0x10, 0x93, 0x1c, 0x53, 0x8a, 0xf5, 0x20,
	0x4c, 0x10, 0x2b, 0xcc, 0x40, 0x0f, 0xe4, 0xa9, 0xe2, 0x53, 0x30, 0xf9, 0x18, 0xc7, 0x94, 0xe2,
	0x18, 0xb8, 0x7c, 0x4c, 0x98, 0x41, 0x0c, 0x58, 0xfe, 0x11, 0x01, 0xf9, 0x24, 0x36, 0x70, 0xf8,
	0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x26, 0x4e, 0xd7, 0xc5, 0xa6, 0x01, 0x00, 0x00,
}
