ARG GOOGLE_ADS_VERSION

# Build stage for compiling the protocol buffers using bazel
FROM golang:latest AS protos

ENV BAZEL_VERSION=4.0.0
ARG GOOGLE_ADS_VERSION

# Install dependencies
RUN apt update --allow-releaseinfo-change
RUN apt-get update -y
RUN apt-get install git wget pkg-config zip g++ zlib1g-dev unzip python -y
RUN apt-get install \
    python3 \
    python3-distutils \
    python3-apt -y

# Install protoc
RUN apt install -y protobuf-compiler
RUN protoc --version

# Download Bazel
# RUN go get github.com/bazelbuild/bazelisk

# Clone the googleapis repo
RUN git clone https://github.com/googleapis/googleapis.git

# Install go gapic generator library
RUN go get github.com/googleapis/gapic-generator-go/cmd/protoc-gen-go_gapic \ 
        google.golang.org/protobuf/cmd/protoc-gen-go \
        google.golang.org/grpc/cmd/protoc-gen-go-grpc

WORKDIR /go/googleapis
RUN mkdir /build

ENV GOPATH=$HOME/go
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin

COPY build.sh /go/googleapis

RUN bash ./build.sh

# # Add Go build configuration to Bazel build file
# COPY 

# # Compile protocol buffers
# # RUN bazelisk build //google/ads/googleads/${GOOGLE_ADS_VERSION}:googleads-nodejs

# # Build stage for extracting the compiled nodejs gapic client and performing any custom changes
# # FROM node:latest

# # ARG GOOGLE_ADS_VERSION

# # RUN mkdir /package

# # WORKDIR /package

# # COPY --from=protos /go/googleapis/bazel-bin/google/ads/googleads/${GOOGLE_ADS_VERSION}/googleads-nodejs.tar.gz /package

# # RUN tar -xvzf googleads-nodejs.tar.gz -C .