// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v0/common/ad.proto

package google_ads_googleads_v0_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	enums "google/ads/googleads/v0/enums"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// An ad.
type Ad struct {
	// The ID of the ad.
	Id *wrappers.Int64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The list of possible final URLs after all cross-domain redirects for the
	// ad.
	FinalUrls []*wrappers.StringValue `protobuf:"bytes,2,rep,name=final_urls,json=finalUrls,proto3" json:"final_urls,omitempty"`
	// The list of possible final mobile URLs after all cross-domain redirects
	// for the ad.
	FinalMobileUrls []*wrappers.StringValue `protobuf:"bytes,16,rep,name=final_mobile_urls,json=finalMobileUrls,proto3" json:"final_mobile_urls,omitempty"`
	// The URL template for constructing a tracking URL.
	TrackingUrlTemplate *wrappers.StringValue `protobuf:"bytes,12,opt,name=tracking_url_template,json=trackingUrlTemplate,proto3" json:"tracking_url_template,omitempty"`
	// The list of mappings that can be used to substitute custom parameter tags
	// in a
	// `tracking_url_template`, `final_urls`, or `mobile_final_urls`.
	UrlCustomParameters []*CustomParameter `protobuf:"bytes,10,rep,name=url_custom_parameters,json=urlCustomParameters,proto3" json:"url_custom_parameters,omitempty"`
	// The URL that appears in the ad description for some ad formats.
	DisplayUrl *wrappers.StringValue `protobuf:"bytes,4,opt,name=display_url,json=displayUrl,proto3" json:"display_url,omitempty"`
	// The type of ad.
	Type enums.AdTypeEnum_AdType `protobuf:"varint,5,opt,name=type,proto3,enum=google.ads.googleads.v0.enums.AdTypeEnum_AdType" json:"type,omitempty"`
	// Details pertinent to the ad type. Exactly one value must be set.
	//
	// Types that are valid to be assigned to AdData:
	//	*Ad_TextAd
	//	*Ad_ExpandedTextAd
	//	*Ad_DynamicSearchAd
	//	*Ad_ResponsiveDisplayAd
	//	*Ad_CallOnlyAd
	//	*Ad_ExpandedDynamicSearchAd
	//	*Ad_HotelAd
	AdData               isAd_AdData `protobuf_oneof:"ad_data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}
func (*Ad) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2ceb544195ba6c, []int{0}
}
func (m *Ad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ad.Unmarshal(m, b)
}
func (m *Ad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ad.Marshal(b, m, deterministic)
}
func (m *Ad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad.Merge(m, src)
}
func (m *Ad) XXX_Size() int {
	return xxx_messageInfo_Ad.Size(m)
}
func (m *Ad) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad.DiscardUnknown(m)
}

var xxx_messageInfo_Ad proto.InternalMessageInfo

func (m *Ad) GetId() *wrappers.Int64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Ad) GetFinalUrls() []*wrappers.StringValue {
	if m != nil {
		return m.FinalUrls
	}
	return nil
}

func (m *Ad) GetFinalMobileUrls() []*wrappers.StringValue {
	if m != nil {
		return m.FinalMobileUrls
	}
	return nil
}

func (m *Ad) GetTrackingUrlTemplate() *wrappers.StringValue {
	if m != nil {
		return m.TrackingUrlTemplate
	}
	return nil
}

func (m *Ad) GetUrlCustomParameters() []*CustomParameter {
	if m != nil {
		return m.UrlCustomParameters
	}
	return nil
}

func (m *Ad) GetDisplayUrl() *wrappers.StringValue {
	if m != nil {
		return m.DisplayUrl
	}
	return nil
}

func (m *Ad) GetType() enums.AdTypeEnum_AdType {
	if m != nil {
		return m.Type
	}
	return enums.AdTypeEnum_UNSPECIFIED
}

type isAd_AdData interface {
	isAd_AdData()
}

type Ad_TextAd struct {
	TextAd *TextAdInfo `protobuf:"bytes,6,opt,name=text_ad,json=textAd,proto3,oneof"`
}

type Ad_ExpandedTextAd struct {
	ExpandedTextAd *ExpandedTextAdInfo `protobuf:"bytes,7,opt,name=expanded_text_ad,json=expandedTextAd,proto3,oneof"`
}

type Ad_DynamicSearchAd struct {
	DynamicSearchAd *DynamicSearchAdInfo `protobuf:"bytes,8,opt,name=dynamic_search_ad,json=dynamicSearchAd,proto3,oneof"`
}

type Ad_ResponsiveDisplayAd struct {
	ResponsiveDisplayAd *ResponsiveDisplayAdInfo `protobuf:"bytes,9,opt,name=responsive_display_ad,json=responsiveDisplayAd,proto3,oneof"`
}

type Ad_CallOnlyAd struct {
	CallOnlyAd *CallOnlyAdInfo `protobuf:"bytes,13,opt,name=call_only_ad,json=callOnlyAd,proto3,oneof"`
}

type Ad_ExpandedDynamicSearchAd struct {
	ExpandedDynamicSearchAd *ExpandedDynamicSearchAdInfo `protobuf:"bytes,14,opt,name=expanded_dynamic_search_ad,json=expandedDynamicSearchAd,proto3,oneof"`
}

type Ad_HotelAd struct {
	HotelAd *HotelAdInfo `protobuf:"bytes,15,opt,name=hotel_ad,json=hotelAd,proto3,oneof"`
}

func (*Ad_TextAd) isAd_AdData() {}

func (*Ad_ExpandedTextAd) isAd_AdData() {}

func (*Ad_DynamicSearchAd) isAd_AdData() {}

func (*Ad_ResponsiveDisplayAd) isAd_AdData() {}

func (*Ad_CallOnlyAd) isAd_AdData() {}

func (*Ad_ExpandedDynamicSearchAd) isAd_AdData() {}

func (*Ad_HotelAd) isAd_AdData() {}

func (m *Ad) GetAdData() isAd_AdData {
	if m != nil {
		return m.AdData
	}
	return nil
}

func (m *Ad) GetTextAd() *TextAdInfo {
	if x, ok := m.GetAdData().(*Ad_TextAd); ok {
		return x.TextAd
	}
	return nil
}

func (m *Ad) GetExpandedTextAd() *ExpandedTextAdInfo {
	if x, ok := m.GetAdData().(*Ad_ExpandedTextAd); ok {
		return x.ExpandedTextAd
	}
	return nil
}

func (m *Ad) GetDynamicSearchAd() *DynamicSearchAdInfo {
	if x, ok := m.GetAdData().(*Ad_DynamicSearchAd); ok {
		return x.DynamicSearchAd
	}
	return nil
}

func (m *Ad) GetResponsiveDisplayAd() *ResponsiveDisplayAdInfo {
	if x, ok := m.GetAdData().(*Ad_ResponsiveDisplayAd); ok {
		return x.ResponsiveDisplayAd
	}
	return nil
}

func (m *Ad) GetCallOnlyAd() *CallOnlyAdInfo {
	if x, ok := m.GetAdData().(*Ad_CallOnlyAd); ok {
		return x.CallOnlyAd
	}
	return nil
}

func (m *Ad) GetExpandedDynamicSearchAd() *ExpandedDynamicSearchAdInfo {
	if x, ok := m.GetAdData().(*Ad_ExpandedDynamicSearchAd); ok {
		return x.ExpandedDynamicSearchAd
	}
	return nil
}

func (m *Ad) GetHotelAd() *HotelAdInfo {
	if x, ok := m.GetAdData().(*Ad_HotelAd); ok {
		return x.HotelAd
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Ad) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Ad_OneofMarshaler, _Ad_OneofUnmarshaler, _Ad_OneofSizer, []interface{}{
		(*Ad_TextAd)(nil),
		(*Ad_ExpandedTextAd)(nil),
		(*Ad_DynamicSearchAd)(nil),
		(*Ad_ResponsiveDisplayAd)(nil),
		(*Ad_CallOnlyAd)(nil),
		(*Ad_ExpandedDynamicSearchAd)(nil),
		(*Ad_HotelAd)(nil),
	}
}

func _Ad_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Ad)
	// ad_data
	switch x := m.AdData.(type) {
	case *Ad_TextAd:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TextAd); err != nil {
			return err
		}
	case *Ad_ExpandedTextAd:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExpandedTextAd); err != nil {
			return err
		}
	case *Ad_DynamicSearchAd:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DynamicSearchAd); err != nil {
			return err
		}
	case *Ad_ResponsiveDisplayAd:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResponsiveDisplayAd); err != nil {
			return err
		}
	case *Ad_CallOnlyAd:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CallOnlyAd); err != nil {
			return err
		}
	case *Ad_ExpandedDynamicSearchAd:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExpandedDynamicSearchAd); err != nil {
			return err
		}
	case *Ad_HotelAd:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HotelAd); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Ad.AdData has unexpected type %T", x)
	}
	return nil
}

func _Ad_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Ad)
	switch tag {
	case 6: // ad_data.text_ad
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TextAdInfo)
		err := b.DecodeMessage(msg)
		m.AdData = &Ad_TextAd{msg}
		return true, err
	case 7: // ad_data.expanded_text_ad
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExpandedTextAdInfo)
		err := b.DecodeMessage(msg)
		m.AdData = &Ad_ExpandedTextAd{msg}
		return true, err
	case 8: // ad_data.dynamic_search_ad
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DynamicSearchAdInfo)
		err := b.DecodeMessage(msg)
		m.AdData = &Ad_DynamicSearchAd{msg}
		return true, err
	case 9: // ad_data.responsive_display_ad
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponsiveDisplayAdInfo)
		err := b.DecodeMessage(msg)
		m.AdData = &Ad_ResponsiveDisplayAd{msg}
		return true, err
	case 13: // ad_data.call_only_ad
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CallOnlyAdInfo)
		err := b.DecodeMessage(msg)
		m.AdData = &Ad_CallOnlyAd{msg}
		return true, err
	case 14: // ad_data.expanded_dynamic_search_ad
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExpandedDynamicSearchAdInfo)
		err := b.DecodeMessage(msg)
		m.AdData = &Ad_ExpandedDynamicSearchAd{msg}
		return true, err
	case 15: // ad_data.hotel_ad
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HotelAdInfo)
		err := b.DecodeMessage(msg)
		m.AdData = &Ad_HotelAd{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Ad_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Ad)
	// ad_data
	switch x := m.AdData.(type) {
	case *Ad_TextAd:
		s := proto.Size(x.TextAd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Ad_ExpandedTextAd:
		s := proto.Size(x.ExpandedTextAd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Ad_DynamicSearchAd:
		s := proto.Size(x.DynamicSearchAd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Ad_ResponsiveDisplayAd:
		s := proto.Size(x.ResponsiveDisplayAd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Ad_CallOnlyAd:
		s := proto.Size(x.CallOnlyAd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Ad_ExpandedDynamicSearchAd:
		s := proto.Size(x.ExpandedDynamicSearchAd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Ad_HotelAd:
		s := proto.Size(x.HotelAd)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A text ad.
type TextAdInfo struct {
	// The headline of the ad.
	Headline *wrappers.StringValue `protobuf:"bytes,1,opt,name=headline,proto3" json:"headline,omitempty"`
	// The first line of the ad's description.
	Description1 *wrappers.StringValue `protobuf:"bytes,2,opt,name=description1,proto3" json:"description1,omitempty"`
	// The second line of the ad's description.
	Description2         *wrappers.StringValue `protobuf:"bytes,3,opt,name=description2,proto3" json:"description2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TextAdInfo) Reset()         { *m = TextAdInfo{} }
func (m *TextAdInfo) String() string { return proto.CompactTextString(m) }
func (*TextAdInfo) ProtoMessage()    {}
func (*TextAdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2ceb544195ba6c, []int{1}
}
func (m *TextAdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextAdInfo.Unmarshal(m, b)
}
func (m *TextAdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextAdInfo.Marshal(b, m, deterministic)
}
func (m *TextAdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextAdInfo.Merge(m, src)
}
func (m *TextAdInfo) XXX_Size() int {
	return xxx_messageInfo_TextAdInfo.Size(m)
}
func (m *TextAdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TextAdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TextAdInfo proto.InternalMessageInfo

func (m *TextAdInfo) GetHeadline() *wrappers.StringValue {
	if m != nil {
		return m.Headline
	}
	return nil
}

func (m *TextAdInfo) GetDescription1() *wrappers.StringValue {
	if m != nil {
		return m.Description1
	}
	return nil
}

func (m *TextAdInfo) GetDescription2() *wrappers.StringValue {
	if m != nil {
		return m.Description2
	}
	return nil
}

// An expanded text ad.
type ExpandedTextAdInfo struct {
	// The first part of the ad's headline.
	HeadlinePart1 *wrappers.StringValue `protobuf:"bytes,1,opt,name=headline_part1,json=headlinePart1,proto3" json:"headline_part1,omitempty"`
	// The second part of the ad's headline.
	HeadlinePart2 *wrappers.StringValue `protobuf:"bytes,2,opt,name=headline_part2,json=headlinePart2,proto3" json:"headline_part2,omitempty"`
	// The description of the ad.
	Description *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The text that can appear alongside the ad's displayed URL.
	Path1 *wrappers.StringValue `protobuf:"bytes,4,opt,name=path1,proto3" json:"path1,omitempty"`
	// Additional text that can appear alongside the ad's displayed URL.
	Path2                *wrappers.StringValue `protobuf:"bytes,5,opt,name=path2,proto3" json:"path2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExpandedTextAdInfo) Reset()         { *m = ExpandedTextAdInfo{} }
func (m *ExpandedTextAdInfo) String() string { return proto.CompactTextString(m) }
func (*ExpandedTextAdInfo) ProtoMessage()    {}
func (*ExpandedTextAdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2ceb544195ba6c, []int{2}
}
func (m *ExpandedTextAdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandedTextAdInfo.Unmarshal(m, b)
}
func (m *ExpandedTextAdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandedTextAdInfo.Marshal(b, m, deterministic)
}
func (m *ExpandedTextAdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandedTextAdInfo.Merge(m, src)
}
func (m *ExpandedTextAdInfo) XXX_Size() int {
	return xxx_messageInfo_ExpandedTextAdInfo.Size(m)
}
func (m *ExpandedTextAdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandedTextAdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandedTextAdInfo proto.InternalMessageInfo

func (m *ExpandedTextAdInfo) GetHeadlinePart1() *wrappers.StringValue {
	if m != nil {
		return m.HeadlinePart1
	}
	return nil
}

func (m *ExpandedTextAdInfo) GetHeadlinePart2() *wrappers.StringValue {
	if m != nil {
		return m.HeadlinePart2
	}
	return nil
}

func (m *ExpandedTextAdInfo) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ExpandedTextAdInfo) GetPath1() *wrappers.StringValue {
	if m != nil {
		return m.Path1
	}
	return nil
}

func (m *ExpandedTextAdInfo) GetPath2() *wrappers.StringValue {
	if m != nil {
		return m.Path2
	}
	return nil
}

// A dynamic search ad.
type DynamicSearchAdInfo struct {
	// The first line of the ad's description.
	Description1 *wrappers.StringValue `protobuf:"bytes,1,opt,name=description1,proto3" json:"description1,omitempty"`
	// The second line of the ad's description.
	Description2         *wrappers.StringValue `protobuf:"bytes,2,opt,name=description2,proto3" json:"description2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DynamicSearchAdInfo) Reset()         { *m = DynamicSearchAdInfo{} }
func (m *DynamicSearchAdInfo) String() string { return proto.CompactTextString(m) }
func (*DynamicSearchAdInfo) ProtoMessage()    {}
func (*DynamicSearchAdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2ceb544195ba6c, []int{3}
}
func (m *DynamicSearchAdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamicSearchAdInfo.Unmarshal(m, b)
}
func (m *DynamicSearchAdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamicSearchAdInfo.Marshal(b, m, deterministic)
}
func (m *DynamicSearchAdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicSearchAdInfo.Merge(m, src)
}
func (m *DynamicSearchAdInfo) XXX_Size() int {
	return xxx_messageInfo_DynamicSearchAdInfo.Size(m)
}
func (m *DynamicSearchAdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicSearchAdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicSearchAdInfo proto.InternalMessageInfo

func (m *DynamicSearchAdInfo) GetDescription1() *wrappers.StringValue {
	if m != nil {
		return m.Description1
	}
	return nil
}

func (m *DynamicSearchAdInfo) GetDescription2() *wrappers.StringValue {
	if m != nil {
		return m.Description2
	}
	return nil
}

// A responsive display ad.
type ResponsiveDisplayAdInfo struct {
	// The short version of the ad's headline.
	ShortHeadline *wrappers.StringValue `protobuf:"bytes,1,opt,name=short_headline,json=shortHeadline,proto3" json:"short_headline,omitempty"`
	// The long version of the ad's headline.
	LongHeadline *wrappers.StringValue `protobuf:"bytes,2,opt,name=long_headline,json=longHeadline,proto3" json:"long_headline,omitempty"`
	// The description of the ad.
	Description *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The business name in the ad.
	BusinessName         *wrappers.StringValue `protobuf:"bytes,4,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResponsiveDisplayAdInfo) Reset()         { *m = ResponsiveDisplayAdInfo{} }
func (m *ResponsiveDisplayAdInfo) String() string { return proto.CompactTextString(m) }
func (*ResponsiveDisplayAdInfo) ProtoMessage()    {}
func (*ResponsiveDisplayAdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2ceb544195ba6c, []int{4}
}
func (m *ResponsiveDisplayAdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsiveDisplayAdInfo.Unmarshal(m, b)
}
func (m *ResponsiveDisplayAdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsiveDisplayAdInfo.Marshal(b, m, deterministic)
}
func (m *ResponsiveDisplayAdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsiveDisplayAdInfo.Merge(m, src)
}
func (m *ResponsiveDisplayAdInfo) XXX_Size() int {
	return xxx_messageInfo_ResponsiveDisplayAdInfo.Size(m)
}
func (m *ResponsiveDisplayAdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsiveDisplayAdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsiveDisplayAdInfo proto.InternalMessageInfo

func (m *ResponsiveDisplayAdInfo) GetShortHeadline() *wrappers.StringValue {
	if m != nil {
		return m.ShortHeadline
	}
	return nil
}

func (m *ResponsiveDisplayAdInfo) GetLongHeadline() *wrappers.StringValue {
	if m != nil {
		return m.LongHeadline
	}
	return nil
}

func (m *ResponsiveDisplayAdInfo) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ResponsiveDisplayAdInfo) GetBusinessName() *wrappers.StringValue {
	if m != nil {
		return m.BusinessName
	}
	return nil
}

// A call-only ad.
type CallOnlyAdInfo struct {
	// The country code in the ad.
	CountryCode *wrappers.StringValue `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// The phone number in the ad.
	PhoneNumber *wrappers.StringValue `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// The business name in the ad.
	BusinessName *wrappers.StringValue `protobuf:"bytes,3,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	// The first line of the ad's description.
	Description1 *wrappers.StringValue `protobuf:"bytes,4,opt,name=description1,proto3" json:"description1,omitempty"`
	// The second line of the ad's description.
	Description2 *wrappers.StringValue `protobuf:"bytes,5,opt,name=description2,proto3" json:"description2,omitempty"`
	// Whether to enable call tracking for the creative. Enabling call
	// tracking also enables call conversions.
	CallTracked *wrappers.BoolValue `protobuf:"bytes,6,opt,name=call_tracked,json=callTracked,proto3" json:"call_tracked,omitempty"`
	// Whether to disable call conversion for the creative.
	// If set to `true`, disables call conversions even when `call_tracked` is
	// `true`.
	// If `call_tracked` is `false`, this field is ignored.
	DisableCallConversion *wrappers.BoolValue `protobuf:"bytes,7,opt,name=disable_call_conversion,json=disableCallConversion,proto3" json:"disable_call_conversion,omitempty"`
	// The URL to be used for phone number verification.
	PhoneNumberVerificationUrl *wrappers.StringValue `protobuf:"bytes,8,opt,name=phone_number_verification_url,json=phoneNumberVerificationUrl,proto3" json:"phone_number_verification_url,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}              `json:"-"`
	XXX_unrecognized           []byte                `json:"-"`
	XXX_sizecache              int32                 `json:"-"`
}

func (m *CallOnlyAdInfo) Reset()         { *m = CallOnlyAdInfo{} }
func (m *CallOnlyAdInfo) String() string { return proto.CompactTextString(m) }
func (*CallOnlyAdInfo) ProtoMessage()    {}
func (*CallOnlyAdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2ceb544195ba6c, []int{5}
}
func (m *CallOnlyAdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallOnlyAdInfo.Unmarshal(m, b)
}
func (m *CallOnlyAdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallOnlyAdInfo.Marshal(b, m, deterministic)
}
func (m *CallOnlyAdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallOnlyAdInfo.Merge(m, src)
}
func (m *CallOnlyAdInfo) XXX_Size() int {
	return xxx_messageInfo_CallOnlyAdInfo.Size(m)
}
func (m *CallOnlyAdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CallOnlyAdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CallOnlyAdInfo proto.InternalMessageInfo

func (m *CallOnlyAdInfo) GetCountryCode() *wrappers.StringValue {
	if m != nil {
		return m.CountryCode
	}
	return nil
}

func (m *CallOnlyAdInfo) GetPhoneNumber() *wrappers.StringValue {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *CallOnlyAdInfo) GetBusinessName() *wrappers.StringValue {
	if m != nil {
		return m.BusinessName
	}
	return nil
}

func (m *CallOnlyAdInfo) GetDescription1() *wrappers.StringValue {
	if m != nil {
		return m.Description1
	}
	return nil
}

func (m *CallOnlyAdInfo) GetDescription2() *wrappers.StringValue {
	if m != nil {
		return m.Description2
	}
	return nil
}

func (m *CallOnlyAdInfo) GetCallTracked() *wrappers.BoolValue {
	if m != nil {
		return m.CallTracked
	}
	return nil
}

func (m *CallOnlyAdInfo) GetDisableCallConversion() *wrappers.BoolValue {
	if m != nil {
		return m.DisableCallConversion
	}
	return nil
}

func (m *CallOnlyAdInfo) GetPhoneNumberVerificationUrl() *wrappers.StringValue {
	if m != nil {
		return m.PhoneNumberVerificationUrl
	}
	return nil
}

// An expanded dynamic search ad.
type ExpandedDynamicSearchAdInfo struct {
	// The description of the ad.
	Description          *wrappers.StringValue `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExpandedDynamicSearchAdInfo) Reset()         { *m = ExpandedDynamicSearchAdInfo{} }
func (m *ExpandedDynamicSearchAdInfo) String() string { return proto.CompactTextString(m) }
func (*ExpandedDynamicSearchAdInfo) ProtoMessage()    {}
func (*ExpandedDynamicSearchAdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2ceb544195ba6c, []int{6}
}
func (m *ExpandedDynamicSearchAdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpandedDynamicSearchAdInfo.Unmarshal(m, b)
}
func (m *ExpandedDynamicSearchAdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpandedDynamicSearchAdInfo.Marshal(b, m, deterministic)
}
func (m *ExpandedDynamicSearchAdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpandedDynamicSearchAdInfo.Merge(m, src)
}
func (m *ExpandedDynamicSearchAdInfo) XXX_Size() int {
	return xxx_messageInfo_ExpandedDynamicSearchAdInfo.Size(m)
}
func (m *ExpandedDynamicSearchAdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpandedDynamicSearchAdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ExpandedDynamicSearchAdInfo proto.InternalMessageInfo

func (m *ExpandedDynamicSearchAdInfo) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

// A hotel ad.
type HotelAdInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotelAdInfo) Reset()         { *m = HotelAdInfo{} }
func (m *HotelAdInfo) String() string { return proto.CompactTextString(m) }
func (*HotelAdInfo) ProtoMessage()    {}
func (*HotelAdInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2ceb544195ba6c, []int{7}
}
func (m *HotelAdInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotelAdInfo.Unmarshal(m, b)
}
func (m *HotelAdInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotelAdInfo.Marshal(b, m, deterministic)
}
func (m *HotelAdInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotelAdInfo.Merge(m, src)
}
func (m *HotelAdInfo) XXX_Size() int {
	return xxx_messageInfo_HotelAdInfo.Size(m)
}
func (m *HotelAdInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HotelAdInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HotelAdInfo proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Ad)(nil), "google.ads.googleads.v0.common.Ad")
	proto.RegisterType((*TextAdInfo)(nil), "google.ads.googleads.v0.common.TextAdInfo")
	proto.RegisterType((*ExpandedTextAdInfo)(nil), "google.ads.googleads.v0.common.ExpandedTextAdInfo")
	proto.RegisterType((*DynamicSearchAdInfo)(nil), "google.ads.googleads.v0.common.DynamicSearchAdInfo")
	proto.RegisterType((*ResponsiveDisplayAdInfo)(nil), "google.ads.googleads.v0.common.ResponsiveDisplayAdInfo")
	proto.RegisterType((*CallOnlyAdInfo)(nil), "google.ads.googleads.v0.common.CallOnlyAdInfo")
	proto.RegisterType((*ExpandedDynamicSearchAdInfo)(nil), "google.ads.googleads.v0.common.ExpandedDynamicSearchAdInfo")
	proto.RegisterType((*HotelAdInfo)(nil), "google.ads.googleads.v0.common.HotelAdInfo")
}

func init() {
	proto.RegisterFile("google/ads/googleads/v0/common/ad.proto", fileDescriptor_db2ceb544195ba6c)
}

var fileDescriptor_db2ceb544195ba6c = []byte{
	// 976 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0xc7, 0x1b, 0xc3, 0x12, 0x38, 0x21, 0xb0, 0x3b, 0x08, 0x61, 0xb1, 0xed, 0x0a, 0xe5, 0xa6,
	0xa8, 0x48, 0x0e, 0x78, 0xfb, 0x25, 0xad, 0xb6, 0xad, 0xf9, 0xd0, 0xb2, 0x17, 0xdd, 0xa2, 0x2c,
	0x70, 0x45, 0x6b, 0x4d, 0x3c, 0x03, 0xb1, 0x3a, 0x9e, 0xb1, 0x66, 0xc6, 0x29, 0xe9, 0x63, 0xf4,
	0xaa, 0xbd, 0xad, 0x7a, 0xd5, 0x07, 0xe9, 0xc5, 0x4a, 0x7d, 0x89, 0x3e, 0x49, 0xe5, 0xf1, 0x07,
	0x09, 0x01, 0xec, 0x88, 0xbb, 0xb1, 0x7d, 0x7e, 0xff, 0x73, 0xce, 0xfc, 0x4f, 0x66, 0x02, 0x9f,
	0x5e, 0x09, 0x71, 0xc5, 0x68, 0x17, 0x13, 0xd5, 0xcd, 0x96, 0xe9, 0x6a, 0xb8, 0xdb, 0x0d, 0x44,
	0x14, 0x09, 0xde, 0xc5, 0xc4, 0x89, 0xa5, 0xd0, 0x02, 0xbd, 0xc8, 0xbe, 0x3a, 0x98, 0x28, 0xa7,
	0x0c, 0x74, 0x86, 0xbb, 0x4e, 0x16, 0xb8, 0xf9, 0x45, 0x85, 0x50, 0x90, 0x28, 0x2d, 0x22, 0x3f,
	0xc6, 0x12, 0x47, 0x54, 0x53, 0x99, 0xc9, 0x6e, 0xee, 0xdc, 0x87, 0x51, 0x9e, 0x44, 0xaa, 0x8b,
	0x89, 0xaf, 0x47, 0x31, 0xcd, 0x83, 0xf3, 0x1a, 0xba, 0xe6, 0xa9, 0x9f, 0x5c, 0x76, 0x7f, 0x91,
	0x38, 0x8e, 0xa9, 0x54, 0xd9, 0xf7, 0xce, 0x6f, 0x4b, 0x60, 0x79, 0x04, 0xed, 0x80, 0x15, 0x12,
	0xbb, 0xb1, 0xd5, 0xd8, 0x6e, 0xb9, 0xcf, 0xf3, 0x62, 0x9d, 0x82, 0x71, 0xde, 0x72, 0xfd, 0xe5,
	0xe7, 0xe7, 0x98, 0x25, 0xb4, 0x67, 0x85, 0x04, 0xbd, 0x02, 0xb8, 0x0c, 0x39, 0x66, 0x7e, 0x22,
	0x99, 0xb2, 0xad, 0xad, 0xb9, 0xed, 0x96, 0xfb, 0xf1, 0x14, 0xf4, 0x5e, 0xcb, 0x90, 0x5f, 0x65,
	0xd4, 0x92, 0x89, 0x3f, 0x93, 0x4c, 0xa1, 0x63, 0x78, 0x96, 0xc1, 0x91, 0xe8, 0x87, 0x8c, 0x66,
	0x1a, 0x4f, 0x6b, 0x68, 0xac, 0x1a, 0xec, 0x7b, 0x43, 0x19, 0xa5, 0x13, 0x58, 0xd7, 0x12, 0x07,
	0x3f, 0x87, 0xfc, 0x2a, 0x55, 0xf1, 0x35, 0x8d, 0x62, 0x86, 0x35, 0xb5, 0x97, 0x4d, 0x1b, 0x0f,
	0xab, 0xad, 0x15, 0xe8, 0x99, 0x64, 0xa7, 0x39, 0x88, 0x02, 0x58, 0x4f, 0x85, 0x6e, 0xef, 0xbb,
	0xb2, 0xc1, 0xd4, 0xd7, 0x75, 0x1e, 0x36, 0xd4, 0x39, 0x30, 0xe0, 0x49, 0xc1, 0xf5, 0xd6, 0x12,
	0xc9, 0x6e, 0xbd, 0x53, 0xe8, 0x35, 0xb4, 0x48, 0xa8, 0x62, 0x86, 0x47, 0x69, 0xd5, 0xf6, 0x7c,
	0x8d, 0x62, 0x21, 0x07, 0xce, 0x24, 0x43, 0x87, 0x30, 0x9f, 0xda, 0x6b, 0x3f, 0xd9, 0x6a, 0x6c,
	0xaf, 0xb8, 0xbb, 0xf7, 0x96, 0x64, 0x86, 0xc1, 0xf1, 0xc8, 0xe9, 0x28, 0xa6, 0x47, 0x3c, 0x89,
	0xf2, 0x65, 0xcf, 0xd0, 0xe8, 0x08, 0x9a, 0x9a, 0x5e, 0x6b, 0x1f, 0x13, 0x7b, 0xc1, 0x14, 0xf0,
	0x59, 0x55, 0x6f, 0xa7, 0xf4, 0x5a, 0x7b, 0xe4, 0x2d, 0xbf, 0x14, 0xc7, 0x1f, 0xf5, 0x16, 0xb4,
	0x79, 0x42, 0x3f, 0xc1, 0x53, 0x7a, 0x1d, 0x63, 0x4e, 0x28, 0xf1, 0x0b, 0xbd, 0xa6, 0xd1, 0x73,
	0xab, 0xf4, 0x8e, 0x72, 0x6e, 0x42, 0x77, 0x85, 0x4e, 0xbc, 0x45, 0x18, 0x9e, 0x91, 0x11, 0xc7,
	0x51, 0x18, 0xf8, 0x8a, 0x62, 0x19, 0x0c, 0xd2, 0x04, 0x8b, 0x26, 0xc1, 0xcb, 0xaa, 0x04, 0x87,
	0x19, 0xf8, 0xde, 0x70, 0x65, 0x86, 0x55, 0x32, 0xf9, 0x1a, 0x45, 0xb0, 0x2e, 0xa9, 0x8a, 0x05,
	0x57, 0xe1, 0x90, 0xfa, 0x85, 0x33, 0x98, 0xd8, 0x4b, 0x26, 0xcd, 0x57, 0x55, 0x69, 0x7a, 0x25,
	0x7c, 0x98, 0xb1, 0x65, 0xaa, 0x35, 0x39, 0xfd, 0x09, 0xf5, 0x60, 0x39, 0xc0, 0x8c, 0xf9, 0x82,
	0x33, 0x93, 0xa5, 0x6d, 0xb2, 0x38, 0x95, 0x93, 0x85, 0x19, 0xfb, 0x81, 0xb3, 0x1b, 0x71, 0x08,
	0xca, 0x37, 0xe8, 0x57, 0xd8, 0x2c, 0x5d, 0x98, 0xde, 0xae, 0x15, 0x93, 0xe1, 0x55, 0x5d, 0x3f,
	0xee, 0xde, 0xb6, 0x0d, 0x7a, 0xf7, 0x67, 0x74, 0x0c, 0x8b, 0x03, 0xa1, 0x29, 0x4b, 0x33, 0xad,
	0x9a, 0x4c, 0x3b, 0x55, 0x99, 0x8e, 0xd3, 0xf8, 0x52, 0xb9, 0x39, 0xc8, 0x1e, 0xf7, 0x97, 0xa0,
	0x89, 0x89, 0x4f, 0xb0, 0xc6, 0x9d, 0x0f, 0x0d, 0x80, 0x9b, 0xb9, 0x40, 0x5f, 0xc3, 0xe2, 0x80,
	0x62, 0xc2, 0x42, 0x4e, 0xf3, 0x23, 0xea, 0xe1, 0x9f, 0x4b, 0x19, 0x8d, 0xbe, 0x83, 0x65, 0x42,
	0x55, 0x20, 0xc3, 0x58, 0x87, 0x82, 0xef, 0xd9, 0x56, 0x0d, 0x7a, 0x82, 0xb8, 0xa5, 0xe0, 0xda,
	0x73, 0x33, 0x2a, 0xb8, 0x9d, 0x7f, 0x2c, 0x40, 0xd3, 0xc3, 0x8e, 0x0e, 0x60, 0xa5, 0x28, 0x33,
	0x3d, 0x69, 0xf4, 0x5e, 0xad, 0xd6, 0xda, 0x05, 0x73, 0x92, 0x22, 0x53, 0x22, 0x6e, 0xad, 0x0e,
	0x27, 0x44, 0x5c, 0xf4, 0x0d, 0xb4, 0xc6, 0x0a, 0xae, 0xd5, 0xe1, 0x38, 0x80, 0x5c, 0x78, 0x12,
	0x63, 0x3d, 0xd8, 0xab, 0x75, 0x94, 0x65, 0xa1, 0x05, 0xe3, 0x9a, 0x63, 0xac, 0x16, 0xe3, 0x76,
	0xfe, 0x68, 0xc0, 0xda, 0x1d, 0xd3, 0x39, 0x65, 0x72, 0xe3, 0xd1, 0x26, 0x5b, 0x33, 0x9b, 0xfc,
	0x97, 0x05, 0x1b, 0xf7, 0x9c, 0x04, 0xa9, 0x49, 0x6a, 0x20, 0xa4, 0xf6, 0x67, 0x1a, 0xe2, 0xb6,
	0x61, 0x8e, 0x8b, 0x49, 0xf6, 0xa0, 0xcd, 0x04, 0xbf, 0xba, 0xd1, 0xa8, 0x55, 0x63, 0x8a, 0x94,
	0x12, 0x8f, 0xf5, 0xd9, 0x83, 0x76, 0x3f, 0x51, 0x21, 0xa7, 0x4a, 0xf9, 0x1c, 0x47, 0xb4, 0x96,
	0xdf, 0xcb, 0x05, 0xf2, 0x0e, 0x47, 0xb4, 0xf3, 0xef, 0x3c, 0xac, 0x4c, 0x1e, 0x65, 0xe8, 0x5b,
	0x58, 0x0e, 0x44, 0xc2, 0xb5, 0x1c, 0xf9, 0x81, 0x20, 0xf5, 0xf6, 0xa6, 0x95, 0x13, 0x07, 0x82,
	0xd0, 0x54, 0x20, 0x1e, 0x08, 0x4e, 0x7d, 0x9e, 0x44, 0x7d, 0x2a, 0x6b, 0x6d, 0x4c, 0xcb, 0x10,
	0xef, 0x0c, 0x30, 0xdd, 0xd7, 0xdc, 0xac, 0x7d, 0x4d, 0x8d, 0xe0, 0xfc, 0xa3, 0x47, 0xf0, 0xc9,
	0xac, 0x23, 0x88, 0x5e, 0xe7, 0x37, 0x8b, 0xf9, 0x63, 0x43, 0x8b, 0x7b, 0x7d, 0x73, 0x4a, 0x61,
	0x5f, 0x08, 0x56, 0x6c, 0x23, 0x66, 0xec, 0x34, 0x0b, 0x47, 0x3d, 0xd8, 0x20, 0xa1, 0xc2, 0x7d,
	0x46, 0x7d, 0x23, 0x13, 0x08, 0x3e, 0xa4, 0x52, 0xa5, 0x93, 0xd2, 0xac, 0x54, 0x5a, 0xcf, 0xd1,
	0xd4, 0xdb, 0x83, 0x12, 0x44, 0x3e, 0x7c, 0x32, 0x6e, 0x8d, 0x3f, 0xa4, 0x32, 0xbc, 0x0c, 0x03,
	0x9c, 0x16, 0x6c, 0xfe, 0xfc, 0x2c, 0xd6, 0xe8, 0x72, 0x73, 0xcc, 0xab, 0xf3, 0x31, 0x81, 0x33,
	0xc9, 0x3a, 0x3f, 0xc2, 0xf3, 0x07, 0xee, 0xad, 0xdb, 0x13, 0xdf, 0x98, 0x71, 0xe2, 0x3b, 0x6d,
	0x68, 0x8d, 0x5d, 0x56, 0xfb, 0xbf, 0x37, 0xa0, 0x13, 0x88, 0xa8, 0xe2, 0x7e, 0xdb, 0x6f, 0x7a,
	0xe4, 0x24, 0x95, 0x3e, 0x69, 0xfc, 0x69, 0xcd, 0xbd, 0xf1, 0xbc, 0xbf, 0xad, 0x17, 0x6f, 0x32,
	0xc2, 0x23, 0xca, 0xc9, 0x96, 0xe9, 0xea, 0x7c, 0xd7, 0x39, 0x30, 0xc4, 0x87, 0x22, 0xe0, 0xc2,
	0x23, 0xea, 0xa2, 0x0c, 0xb8, 0x38, 0xdf, 0xbd, 0xc8, 0x02, 0xfe, 0xab, 0x0a, 0xe8, 0x2f, 0x98,
	0x66, 0x5e, 0xfe, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xcf, 0x52, 0x7c, 0x9c, 0x0c, 0x00, 0x00,
}
