// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/common/metrics.proto

package google_ads_googleads_v0_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Metrics data.
type Metrics struct {
	// All conversions divided by the number of ad interactions.
	AllConversionRate *wrappers.DoubleValue `protobuf:"bytes,5,opt,name=all_conversion_rate,json=allConversionRate,proto3" json:"all_conversion_rate,omitempty"`
	// The total value of all conversions.
	AllConversionValue *wrappers.DoubleValue `protobuf:"bytes,6,opt,name=all_conversion_value,json=allConversionValue,proto3" json:"all_conversion_value,omitempty"`
	// The total number of conversions. This includes "Conversions" plus
	// conversions that have their "Include in Conversions" setting unchecked.
	AllConversions *wrappers.DoubleValue `protobuf:"bytes,7,opt,name=all_conversions,json=allConversions,proto3" json:"all_conversions,omitempty"`
	// The value of all conversions divided by the total cost of ad interactions
	// (such as clicks for text ads or views for video ads).
	AllConversionsValuePerCost *wrappers.DoubleValue `protobuf:"bytes,62,opt,name=all_conversions_value_per_cost,json=allConversionsValuePerCost,proto3" json:"all_conversions_value_per_cost,omitempty"`
	// The value of all conversions divided by the total number of interactions.
	AllConversionsValuePerInteraction *wrappers.DoubleValue `protobuf:"bytes,61,opt,name=all_conversions_value_per_interaction,json=allConversionsValuePerInteraction,proto3" json:"all_conversions_value_per_interaction,omitempty"`
	// The average amount you pay per interaction. This amount is the total cost
	// of your ads divided by the total number of interactions.
	AverageCost *wrappers.DoubleValue `protobuf:"bytes,8,opt,name=average_cost,json=averageCost,proto3" json:"average_cost,omitempty"`
	// The total cost of all clicks divided by the total number of clicks
	// received.
	AverageCpc *wrappers.DoubleValue `protobuf:"bytes,9,opt,name=average_cpc,json=averageCpc,proto3" json:"average_cpc,omitempty"`
	// Average cost-per-thousand impressions (CPM).
	AverageCpm *wrappers.DoubleValue `protobuf:"bytes,10,opt,name=average_cpm,json=averageCpm,proto3" json:"average_cpm,omitempty"`
	// Your ad's position relative to those of other advertisers.
	AveragePosition *wrappers.DoubleValue `protobuf:"bytes,13,opt,name=average_position,json=averagePosition,proto3" json:"average_position,omitempty"`
	// Percentage of clicks where the user only visited a single page on your
	// site. Imported from Google Analytics.
	BounceRate *wrappers.DoubleValue `protobuf:"bytes,15,opt,name=bounce_rate,json=bounceRate,proto3" json:"bounce_rate,omitempty"`
	// The number of clicks.
	Clicks *wrappers.Int64Value `protobuf:"bytes,19,opt,name=clicks,proto3" json:"clicks,omitempty"`
	// The estimated percent of times that your ad was eligible to show
	// on the Display Network but didn't because your budget was too low.
	// Note: Content budget lost impression share is reported in the range of 0
	// to 0.9. Any value above 0.9 is reported as 0.9001.
	ContentBudgetLostImpressionShare *wrappers.DoubleValue `protobuf:"bytes,20,opt,name=content_budget_lost_impression_share,json=contentBudgetLostImpressionShare,proto3" json:"content_budget_lost_impression_share,omitempty"`
	// The impressions you've received on the Display Network divided
	// by the estimated number of impressions you were eligible to receive.
	// Note: Content impression share is reported in the range of 0.1 to 1. Any
	// value below 0.1 is reported as 0.0999.
	ContentImpressionShare *wrappers.DoubleValue `protobuf:"bytes,21,opt,name=content_impression_share,json=contentImpressionShare,proto3" json:"content_impression_share,omitempty"`
	// The estimated percentage of impressions on the Display Network
	// that your ads didn't receive due to poor Ad Rank.
	// Note: Content rank lost impression share is reported in the range of 0
	// to 0.9. Any value above 0.9 is reported as 0.9001.
	ContentRankLostImpressionShare *wrappers.DoubleValue `protobuf:"bytes,22,opt,name=content_rank_lost_impression_share,json=contentRankLostImpressionShare,proto3" json:"content_rank_lost_impression_share,omitempty"`
	// Conversions divided by the number of ad interactions (such as clicks for
	// text ads or views for video ads).
	ConversionRate *wrappers.DoubleValue `protobuf:"bytes,23,opt,name=conversion_rate,json=conversionRate,proto3" json:"conversion_rate,omitempty"`
	// The total value of conversions.
	ConversionValue *wrappers.DoubleValue `protobuf:"bytes,24,opt,name=conversion_value,json=conversionValue,proto3" json:"conversion_value,omitempty"`
	// The value of conversions divided by the cost of ad interactions.
	ConversionValuePerCost *wrappers.DoubleValue `protobuf:"bytes,64,opt,name=conversion_value_per_cost,json=conversionValuePerCost,proto3" json:"conversion_value_per_cost,omitempty"`
	// The value of conversions divided by the number of ad interactions.
	ConversionValuePerInteraction *wrappers.DoubleValue `protobuf:"bytes,63,opt,name=conversion_value_per_interaction,json=conversionValuePerInteraction,proto3" json:"conversion_value_per_interaction,omitempty"`
	// The number of conversions. This only includes conversion actions which have
	// "Include in Conversions" checked.
	Conversions *wrappers.DoubleValue `protobuf:"bytes,25,opt,name=conversions,proto3" json:"conversions,omitempty"`
	// The sum of your cost-per-click (CPC) and cost-per-thousand impressions
	// (CPM) costs during this period.
	CostMicros *wrappers.Int64Value `protobuf:"bytes,26,opt,name=cost_micros,json=costMicros,proto3" json:"cost_micros,omitempty"`
	// The cost of ad interactions divided by all conversions.
	CostPerAllConversion *wrappers.DoubleValue `protobuf:"bytes,27,opt,name=cost_per_all_conversion,json=costPerAllConversion,proto3" json:"cost_per_all_conversion,omitempty"`
	// The cost of ad interactions divided by conversions.
	CostPerConversion *wrappers.DoubleValue `protobuf:"bytes,28,opt,name=cost_per_conversion,json=costPerConversion,proto3" json:"cost_per_conversion,omitempty"`
	// Conversions from when a customer clicks on an AdWords ad on one device,
	// then converts on a different device or browser.
	// Cross-device conversions are already included in all_conversions.
	CrossDeviceConversions *wrappers.DoubleValue `protobuf:"bytes,29,opt,name=cross_device_conversions,json=crossDeviceConversions,proto3" json:"cross_device_conversions,omitempty"`
	// The number of clicks your ad receives (Clicks) divided by the number
	// of times your ad is shown (Impressions).
	Ctr *wrappers.DoubleValue `protobuf:"bytes,30,opt,name=ctr,proto3" json:"ctr,omitempty"`
	// How often people engage with your ad after it's shown to them. This is the
	// number of ad expansions divided by the number of times your ad is shown.
	EngagementRate *wrappers.DoubleValue `protobuf:"bytes,31,opt,name=engagement_rate,json=engagementRate,proto3" json:"engagement_rate,omitempty"`
	// The number of engagements.
	// An engagement occurs when a viewer expands your Lightbox ad. Also, in the
	// future, other ad types may support engagement metrics.
	Engagements *wrappers.Int64Value `protobuf:"bytes,32,opt,name=engagements,proto3" json:"engagements,omitempty"`
	// Count of how often your ad has appeared on a search results page or
	// website on the Google Network.
	Impressions *wrappers.Int64Value `protobuf:"bytes,37,opt,name=impressions,proto3" json:"impressions,omitempty"`
	// How often people interact with your ad after it is shown to them.
	// This is the number of interactions divided by the number of times your ad
	// is shown.
	InteractionRate *wrappers.DoubleValue `protobuf:"bytes,38,opt,name=interaction_rate,json=interactionRate,proto3" json:"interaction_rate,omitempty"`
	// The number of interactions.
	// An interaction is the main user action associated with an ad format-clicks
	// for text and shopping ads, views for video ads, and so on.
	Interactions *wrappers.Int64Value `protobuf:"bytes,39,opt,name=interactions,proto3" json:"interactions,omitempty"`
	// The percentage of clicks filtered out of your total number of clicks
	// (filtered + non-filtered clicks) during the reporting period.
	InvalidClickRate *wrappers.DoubleValue `protobuf:"bytes,40,opt,name=invalid_click_rate,json=invalidClickRate,proto3" json:"invalid_click_rate,omitempty"`
	// Number of clicks Google considers illegitimate and doesn't charge you for.
	InvalidClicks *wrappers.Int64Value `protobuf:"bytes,41,opt,name=invalid_clicks,json=invalidClicks,proto3" json:"invalid_clicks,omitempty"`
	// Percentage of first-time sessions (from people who had never visited your
	// site before). Imported from Google Analytics.
	PercentNewVisitors *wrappers.DoubleValue `protobuf:"bytes,42,opt,name=percent_new_visitors,json=percentNewVisitors,proto3" json:"percent_new_visitors,omitempty"`
	// Number of offline phone calls.
	PhoneCalls *wrappers.Int64Value `protobuf:"bytes,43,opt,name=phone_calls,json=phoneCalls,proto3" json:"phone_calls,omitempty"`
	// Number of offline phone impressions.
	PhoneImpressions *wrappers.Int64Value `protobuf:"bytes,44,opt,name=phone_impressions,json=phoneImpressions,proto3" json:"phone_impressions,omitempty"`
	// Number of phone calls received (phone_calls) divided by the number of
	// times your phone number is shown (phone_impressions).
	PhoneThroughRate *wrappers.DoubleValue `protobuf:"bytes,45,opt,name=phone_through_rate,json=phoneThroughRate,proto3" json:"phone_through_rate,omitempty"`
	// Your clickthrough rate (Ctr) divided by the average clickthrough rate of
	// all advertisers on the websites that show your ads. Measures how your ads
	// perform on Display Network sites compared to other ads on the same sites.
	RelativeCtr *wrappers.DoubleValue `protobuf:"bytes,46,opt,name=relative_ctr,json=relativeCtr,proto3" json:"relative_ctr,omitempty"`
	// The estimated percent of times that your ad was eligible to show on the
	// Search Network but didn't because your budget was too low. Note: Search
	// budget lost impression share is reported in the range of 0 to 0.9. Any
	// value above 0.9 is reported as 0.9001.
	SearchBudgetLostImpressionShare *wrappers.DoubleValue `protobuf:"bytes,47,opt,name=search_budget_lost_impression_share,json=searchBudgetLostImpressionShare,proto3" json:"search_budget_lost_impression_share,omitempty"`
	// The impressions you've received divided by the estimated number of
	// impressions you were eligible to receive on the Search Network for search
	// terms that matched your keywords exactly (or were close variants of your
	// keyword), regardless of your keyword match types. Note: Search exact match
	// impression share is reported in the range of 0.1 to 1. Any value below 0.1
	// is reported as 0.0999.
	SearchExactMatchImpressionShare *wrappers.DoubleValue `protobuf:"bytes,49,opt,name=search_exact_match_impression_share,json=searchExactMatchImpressionShare,proto3" json:"search_exact_match_impression_share,omitempty"`
	// The impressions you've received on the Search Network divided
	// by the estimated number of impressions you were eligible to receive.
	// Note: Search impression share is reported in the range of 0.1 to 1. Any
	// value below 0.1 is reported as 0.0999.
	SearchImpressionShare *wrappers.DoubleValue `protobuf:"bytes,50,opt,name=search_impression_share,json=searchImpressionShare,proto3" json:"search_impression_share,omitempty"`
	// The estimated percentage of impressions on the Search Network
	// that your ads didn't receive due to poor Ad Rank.
	// Note: Search rank lost impression share is reported in the range of 0 to
	// 0.9. Any value above 0.9 is reported as 0.9001.
	SearchRankLostImpressionShare *wrappers.DoubleValue `protobuf:"bytes,51,opt,name=search_rank_lost_impression_share,json=searchRankLostImpressionShare,proto3" json:"search_rank_lost_impression_share,omitempty"`
	// The value of all conversions divided by the number of all conversions.
	ValuePerAllConversions *wrappers.DoubleValue `protobuf:"bytes,52,opt,name=value_per_all_conversions,json=valuePerAllConversions,proto3" json:"value_per_all_conversions,omitempty"`
	// The value of conversions divided by the number of conversions.
	ValuePerConversion *wrappers.DoubleValue `protobuf:"bytes,53,opt,name=value_per_conversion,json=valuePerConversion,proto3" json:"value_per_conversion,omitempty"`
	// The total number of view-through conversions.
	// These happen when a customer sees an image or rich media ad, then later
	// completes a conversion on your site without interacting with (e.g.,
	// clicking on) another ad.
	ViewThroughConversions *wrappers.Int64Value `protobuf:"bytes,60,opt,name=view_through_conversions,json=viewThroughConversions,proto3" json:"view_through_conversions,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a6464adb140f27, []int{0}
}
func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (m *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(m, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetAllConversionRate() *wrappers.DoubleValue {
	if m != nil {
		return m.AllConversionRate
	}
	return nil
}

func (m *Metrics) GetAllConversionValue() *wrappers.DoubleValue {
	if m != nil {
		return m.AllConversionValue
	}
	return nil
}

func (m *Metrics) GetAllConversions() *wrappers.DoubleValue {
	if m != nil {
		return m.AllConversions
	}
	return nil
}

func (m *Metrics) GetAllConversionsValuePerCost() *wrappers.DoubleValue {
	if m != nil {
		return m.AllConversionsValuePerCost
	}
	return nil
}

func (m *Metrics) GetAllConversionsValuePerInteraction() *wrappers.DoubleValue {
	if m != nil {
		return m.AllConversionsValuePerInteraction
	}
	return nil
}

func (m *Metrics) GetAverageCost() *wrappers.DoubleValue {
	if m != nil {
		return m.AverageCost
	}
	return nil
}

func (m *Metrics) GetAverageCpc() *wrappers.DoubleValue {
	if m != nil {
		return m.AverageCpc
	}
	return nil
}

func (m *Metrics) GetAverageCpm() *wrappers.DoubleValue {
	if m != nil {
		return m.AverageCpm
	}
	return nil
}

func (m *Metrics) GetAveragePosition() *wrappers.DoubleValue {
	if m != nil {
		return m.AveragePosition
	}
	return nil
}

func (m *Metrics) GetBounceRate() *wrappers.DoubleValue {
	if m != nil {
		return m.BounceRate
	}
	return nil
}

func (m *Metrics) GetClicks() *wrappers.Int64Value {
	if m != nil {
		return m.Clicks
	}
	return nil
}

func (m *Metrics) GetContentBudgetLostImpressionShare() *wrappers.DoubleValue {
	if m != nil {
		return m.ContentBudgetLostImpressionShare
	}
	return nil
}

func (m *Metrics) GetContentImpressionShare() *wrappers.DoubleValue {
	if m != nil {
		return m.ContentImpressionShare
	}
	return nil
}

func (m *Metrics) GetContentRankLostImpressionShare() *wrappers.DoubleValue {
	if m != nil {
		return m.ContentRankLostImpressionShare
	}
	return nil
}

func (m *Metrics) GetConversionRate() *wrappers.DoubleValue {
	if m != nil {
		return m.ConversionRate
	}
	return nil
}

func (m *Metrics) GetConversionValue() *wrappers.DoubleValue {
	if m != nil {
		return m.ConversionValue
	}
	return nil
}

func (m *Metrics) GetConversionValuePerCost() *wrappers.DoubleValue {
	if m != nil {
		return m.ConversionValuePerCost
	}
	return nil
}

func (m *Metrics) GetConversionValuePerInteraction() *wrappers.DoubleValue {
	if m != nil {
		return m.ConversionValuePerInteraction
	}
	return nil
}

func (m *Metrics) GetConversions() *wrappers.DoubleValue {
	if m != nil {
		return m.Conversions
	}
	return nil
}

func (m *Metrics) GetCostMicros() *wrappers.Int64Value {
	if m != nil {
		return m.CostMicros
	}
	return nil
}

func (m *Metrics) GetCostPerAllConversion() *wrappers.DoubleValue {
	if m != nil {
		return m.CostPerAllConversion
	}
	return nil
}

func (m *Metrics) GetCostPerConversion() *wrappers.DoubleValue {
	if m != nil {
		return m.CostPerConversion
	}
	return nil
}

func (m *Metrics) GetCrossDeviceConversions() *wrappers.DoubleValue {
	if m != nil {
		return m.CrossDeviceConversions
	}
	return nil
}

func (m *Metrics) GetCtr() *wrappers.DoubleValue {
	if m != nil {
		return m.Ctr
	}
	return nil
}

func (m *Metrics) GetEngagementRate() *wrappers.DoubleValue {
	if m != nil {
		return m.EngagementRate
	}
	return nil
}

func (m *Metrics) GetEngagements() *wrappers.Int64Value {
	if m != nil {
		return m.Engagements
	}
	return nil
}

func (m *Metrics) GetImpressions() *wrappers.Int64Value {
	if m != nil {
		return m.Impressions
	}
	return nil
}

func (m *Metrics) GetInteractionRate() *wrappers.DoubleValue {
	if m != nil {
		return m.InteractionRate
	}
	return nil
}

func (m *Metrics) GetInteractions() *wrappers.Int64Value {
	if m != nil {
		return m.Interactions
	}
	return nil
}

func (m *Metrics) GetInvalidClickRate() *wrappers.DoubleValue {
	if m != nil {
		return m.InvalidClickRate
	}
	return nil
}

func (m *Metrics) GetInvalidClicks() *wrappers.Int64Value {
	if m != nil {
		return m.InvalidClicks
	}
	return nil
}

func (m *Metrics) GetPercentNewVisitors() *wrappers.DoubleValue {
	if m != nil {
		return m.PercentNewVisitors
	}
	return nil
}

func (m *Metrics) GetPhoneCalls() *wrappers.Int64Value {
	if m != nil {
		return m.PhoneCalls
	}
	return nil
}

func (m *Metrics) GetPhoneImpressions() *wrappers.Int64Value {
	if m != nil {
		return m.PhoneImpressions
	}
	return nil
}

func (m *Metrics) GetPhoneThroughRate() *wrappers.DoubleValue {
	if m != nil {
		return m.PhoneThroughRate
	}
	return nil
}

func (m *Metrics) GetRelativeCtr() *wrappers.DoubleValue {
	if m != nil {
		return m.RelativeCtr
	}
	return nil
}

func (m *Metrics) GetSearchBudgetLostImpressionShare() *wrappers.DoubleValue {
	if m != nil {
		return m.SearchBudgetLostImpressionShare
	}
	return nil
}

func (m *Metrics) GetSearchExactMatchImpressionShare() *wrappers.DoubleValue {
	if m != nil {
		return m.SearchExactMatchImpressionShare
	}
	return nil
}

func (m *Metrics) GetSearchImpressionShare() *wrappers.DoubleValue {
	if m != nil {
		return m.SearchImpressionShare
	}
	return nil
}

func (m *Metrics) GetSearchRankLostImpressionShare() *wrappers.DoubleValue {
	if m != nil {
		return m.SearchRankLostImpressionShare
	}
	return nil
}

func (m *Metrics) GetValuePerAllConversions() *wrappers.DoubleValue {
	if m != nil {
		return m.ValuePerAllConversions
	}
	return nil
}

func (m *Metrics) GetValuePerConversion() *wrappers.DoubleValue {
	if m != nil {
		return m.ValuePerConversion
	}
	return nil
}

func (m *Metrics) GetViewThroughConversions() *wrappers.Int64Value {
	if m != nil {
		return m.ViewThroughConversions
	}
	return nil
}

func init() {
	proto.RegisterType((*Metrics)(nil), "google.ads.googleads.v0.common.Metrics")
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/common/metrics.proto", fileDescriptor_49a6464adb140f27)
}

var fileDescriptor_49a6464adb140f27 = []byte{
	// 1001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x97, 0xdd, 0x52, 0x1b, 0x37,
	0x14, 0xc7, 0x87, 0x64, 0x4a, 0xda, 0x03, 0x09, 0x64, 0x43, 0x40, 0x90, 0xc4, 0x21, 0x69, 0xd3,
	0xa6, 0x6d, 0xba, 0xa6, 0x21, 0xed, 0x55, 0x08, 0x35, 0x0e, 0x43, 0xc9, 0x04, 0xc6, 0x43, 0x52,
	0xe7, 0x86, 0x99, 0xad, 0x2c, 0x2b, 0xf6, 0x96, 0xdd, 0xd5, 0x8e, 0x24, 0x2f, 0x7d, 0x99, 0xde,
	0xf4, 0xb2, 0x2f, 0xd1, 0xfb, 0x3e, 0x46, 0x9f, 0xa4, 0xa3, 0x0f, 0xaf, 0xb5, 0x6b, 0xc0, 0xea,
	0xdd, 0x8e, 0x7c, 0xfe, 0xbf, 0x73, 0x24, 0x9d, 0x0f, 0x19, 0x9e, 0x0d, 0x18, 0x1b, 0x24, 0xb4,
	0x89, 0xfb, 0xa2, 0x69, 0x3e, 0xd5, 0x57, 0xb1, 0xd5, 0x24, 0x2c, 0x4d, 0x59, 0xd6, 0x4c, 0xa9,
	0xe4, 0x31, 0x11, 0x61, 0xce, 0x99, 0x64, 0x41, 0xc3, 0x98, 0x84, 0xb8, 0x2f, 0xc2, 0xd2, 0x3a,
	0x2c, 0xb6, 0x42, 0x63, 0xbd, 0x61, 0x7f, 0x6f, 0x6a, 0xeb, 0xde, 0xe8, 0x63, 0xf3, 0x9c, 0xe3,
	0x3c, 0xa7, 0xdc, 0xea, 0x1f, 0xff, 0xbd, 0x01, 0x37, 0x8e, 0x0c, 0x31, 0x78, 0x0b, 0x77, 0x70,
	0x92, 0x44, 0x84, 0x65, 0x05, 0xe5, 0x22, 0x66, 0x59, 0xc4, 0xb1, 0xa4, 0xe8, 0x93, 0xcd, 0xb9,
	0xa7, 0x0b, 0xcf, 0xef, 0x5b, 0x7c, 0x38, 0x26, 0x85, 0xaf, 0xd9, 0xa8, 0x97, 0xd0, 0x2e, 0x4e,
	0x46, 0xf4, 0xe4, 0x36, 0x4e, 0x92, 0x76, 0xa9, 0x3b, 0xc1, 0x92, 0x06, 0xc7, 0xb0, 0x52, 0xa3,
	0x15, 0xca, 0x14, 0xcd, 0x7b, 0xe0, 0x82, 0x0a, 0x4e, 0xaf, 0x05, 0xfb, 0xb0, 0x54, 0xe5, 0x09,
	0x74, 0xc3, 0x03, 0x75, 0xab, 0x82, 0x12, 0xc1, 0xaf, 0xd0, 0xa8, 0x61, 0x4c, 0x5c, 0x51, 0x4e,
	0x79, 0x44, 0x98, 0x90, 0xe8, 0x95, 0x07, 0x75, 0xa3, 0x4a, 0xd5, 0x8b, 0x1d, 0xca, 0xdb, 0x4c,
	0xc8, 0x20, 0x83, 0x27, 0x97, 0x7b, 0x88, 0x33, 0x49, 0x39, 0x26, 0x32, 0x66, 0x19, 0xda, 0xf1,
	0x70, 0xf4, 0xe8, 0x62, 0x47, 0x87, 0x13, 0x4c, 0xb0, 0x0b, 0x8b, 0xb8, 0xa0, 0x1c, 0x0f, 0xa8,
	0x89, 0xff, 0x53, 0x0f, 0xec, 0x82, 0x55, 0xe8, 0x80, 0x77, 0x60, 0xa1, 0x04, 0xe4, 0x04, 0x7d,
	0xe6, 0xa1, 0x87, 0xb1, 0x3e, 0x27, 0x55, 0x79, 0x8a, 0xe0, 0x7f, 0xc9, 0xd3, 0xe0, 0x00, 0x96,
	0xc7, 0xf2, 0x9c, 0x89, 0x58, 0x9f, 0xcc, 0x4d, 0x0f, 0xc6, 0x92, 0x55, 0x75, 0xac, 0x48, 0xc5,
	0xd1, 0x63, 0xa3, 0x8c, 0x50, 0x93, 0xb6, 0x4b, 0x3e, 0x71, 0x18, 0x81, 0xce, 0xd7, 0x6d, 0x98,
	0x27, 0x49, 0x4c, 0xce, 0x04, 0xba, 0xa3, 0x95, 0xf7, 0xa6, 0x94, 0x87, 0x99, 0xfc, 0xf1, 0x85,
	0x11, 0x5a, 0xd3, 0x20, 0x81, 0x2f, 0x08, 0xcb, 0x24, 0xcd, 0x64, 0xd4, 0x1b, 0xf5, 0x07, 0x54,
	0x46, 0x09, 0x13, 0x32, 0x8a, 0xd3, 0x9c, 0x53, 0xa1, 0x93, 0x5e, 0x0c, 0x31, 0xa7, 0x68, 0xc5,
	0x23, 0x98, 0x4d, 0x4b, 0xda, 0xd3, 0xa0, 0xb7, 0x4c, 0xc8, 0xc3, 0x12, 0xf3, 0x4e, 0x51, 0x82,
	0x2e, 0xa0, 0xb1, 0xb7, 0x29, 0x0f, 0x77, 0x3d, 0x3c, 0xac, 0x5a, 0x75, 0x9d, 0x3b, 0x84, 0xc7,
	0x63, 0x2e, 0xc7, 0xd9, 0xd9, 0x25, 0x7b, 0x58, 0xf5, 0xf0, 0xd0, 0xb0, 0x9c, 0x13, 0x9c, 0x9d,
	0x5d, 0xb4, 0x83, 0x7d, 0x58, 0xaa, 0xb7, 0x97, 0x35, 0x9f, 0x22, 0x26, 0xd5, 0xde, 0x72, 0x00,
	0xcb, 0x53, 0x7d, 0x05, 0xf9, 0xe4, 0x0c, 0xa9, 0x35, 0x95, 0x0f, 0xb0, 0x5e, 0x07, 0x4d, 0x1a,
	0xc1, 0x4f, 0x9e, 0x47, 0xea, 0x12, 0xc7, 0x4d, 0x80, 0xc2, 0xe6, 0x85, 0x60, 0xb7, 0xfe, 0x77,
	0x3d, 0xf8, 0x0f, 0xa6, 0xf9, 0x6e, 0xed, 0xbf, 0x82, 0x05, 0xb7, 0x21, 0xae, 0xfb, 0x94, 0xbe,
	0x23, 0x08, 0x5e, 0x2a, 0xbd, 0x90, 0x51, 0x1a, 0x13, 0xce, 0x04, 0xda, 0x98, 0x9d, 0xf9, 0xa0,
	0xec, 0x8f, 0xb4, 0x79, 0xf0, 0x0e, 0xd6, 0xb4, 0x5a, 0x6d, 0xac, 0xda, 0xf2, 0xd0, 0x3d, 0x8f,
	0x48, 0x56, 0x94, 0xb8, 0x43, 0x79, 0xcb, 0x6d, 0x71, 0x6a, 0x0a, 0x95, 0x50, 0x07, 0x78, 0xdf,
	0x67, 0x0a, 0x59, 0xa0, 0x43, 0x53, 0x25, 0xc3, 0x99, 0x10, 0x51, 0x9f, 0x16, 0x31, 0xa1, 0x95,
	0xf1, 0xf1, 0xc0, 0xeb, 0x7e, 0x95, 0xfa, 0xb5, 0x16, 0xbb, 0x63, 0x24, 0x84, 0xeb, 0x44, 0x72,
	0xd4, 0xf0, 0x40, 0x28, 0x43, 0x95, 0xf8, 0x34, 0x1b, 0xe0, 0x01, 0x4d, 0x4d, 0x95, 0x49, 0x8a,
	0x1e, 0xfa, 0x24, 0xfe, 0x44, 0xa4, 0x13, 0x7f, 0x07, 0x16, 0x26, 0x2b, 0x02, 0x6d, 0xce, 0xbe,
	0x2f, 0xd7, 0x5e, 0xc9, 0x27, 0x65, 0x2d, 0xd0, 0x13, 0x0f, 0xb9, 0x63, 0xaf, 0xca, 0xce, 0xc9,
	0x5f, 0xb3, 0x8b, 0x2f, 0x7d, 0xca, 0xce, 0x51, 0xe9, 0x6d, 0xec, 0xc2, 0xa2, 0xb3, 0x24, 0xd0,
	0x57, 0xb3, 0x03, 0xa9, 0x08, 0x82, 0x37, 0x10, 0xc4, 0x59, 0x81, 0x93, 0xb8, 0x1f, 0xe9, 0x4e,
	0x6c, 0x62, 0x79, 0xea, 0x11, 0xcb, 0xb2, 0xd5, 0xb5, 0x95, 0x4c, 0x07, 0xb3, 0x07, 0xb7, 0x2a,
	0x2c, 0x81, 0xbe, 0x9e, 0x1d, 0xce, 0x4d, 0x17, 0x23, 0xd4, 0x63, 0x27, 0xa7, 0x9c, 0xa8, 0xbb,
	0xcd, 0xe8, 0x79, 0x54, 0xc4, 0x22, 0x96, 0x8c, 0x0b, 0xf4, 0x8d, 0xcf, 0x63, 0xc7, 0x2a, 0x8f,
	0xe9, 0x79, 0xd7, 0xea, 0x54, 0x5d, 0xe6, 0x43, 0x96, 0xd1, 0x88, 0xe0, 0x24, 0x11, 0xe8, 0x5b,
	0x8f, 0xba, 0xd4, 0xf6, 0x6d, 0x65, 0x1e, 0xfc, 0x0c, 0xb7, 0x8d, 0xda, 0xbd, 0xec, 0x67, 0xb3,
	0x19, 0xcb, 0x5a, 0x75, 0xe8, 0xdc, 0xf8, 0x1b, 0x08, 0x0c, 0x49, 0x0e, 0x39, 0x1b, 0x0d, 0x86,
	0xe6, 0x9c, 0xbf, 0xf3, 0x39, 0x67, 0xad, 0x7b, 0x6f, 0x64, 0xe3, 0x4b, 0xe7, 0x34, 0xc1, 0x32,
	0x2e, 0x68, 0xa4, 0x6a, 0x27, 0xf4, 0x69, 0x56, 0x63, 0x45, 0x5b, 0xf2, 0xe0, 0x37, 0xf8, 0x5c,
	0x50, 0xcc, 0xc9, 0xf0, 0xea, 0x59, 0xdb, 0xf4, 0xe0, 0x3e, 0x34, 0xa0, 0xcb, 0x47, 0xed, 0xc4,
	0x17, 0xfd, 0x1d, 0x13, 0x19, 0xa5, 0x58, 0x92, 0xe1, 0xb4, 0xaf, 0xef, 0xfd, 0x7d, 0xed, 0x2b,
	0xce, 0x91, 0xc2, 0xd4, 0x7d, 0xbd, 0x87, 0x35, 0xeb, 0x6b, 0x8a, 0xff, 0xdc, 0x83, 0x7f, 0xd7,
	0x88, 0xeb, 0xd4, 0x8f, 0xf0, 0xc8, 0x52, 0xaf, 0x98, 0xe9, 0xdb, 0x3e, 0x23, 0xc8, 0x60, 0x2e,
	0x1b, 0xe9, 0x1f, 0x60, 0x7d, 0x32, 0xde, 0xea, 0x2f, 0xf4, 0x17, 0x3e, 0x2d, 0xb6, 0xb0, 0x83,
	0xad, 0x55, 0x7d, 0xa9, 0x1f, 0xc3, 0x8a, 0x3b, 0x90, 0xcb, 0x49, 0xf0, 0x83, 0x4f, 0x4d, 0x15,
	0xe5, 0x30, 0x2e, 0x47, 0xc1, 0x2f, 0x80, 0x8a, 0x98, 0x9e, 0x97, 0xa9, 0xec, 0xc6, 0xf9, 0x72,
	0x76, 0x71, 0xac, 0x2a, 0xb1, 0xcd, 0x67, 0x27, 0xcc, 0xbd, 0x3f, 0xe6, 0xd4, 0xeb, 0x29, 0x0d,
	0xaf, 0xfe, 0x23, 0xb6, 0xb7, 0x68, 0xff, 0x65, 0x75, 0x14, 0xba, 0x33, 0xf7, 0xe7, 0xb5, 0xeb,
	0x07, 0xad, 0xd6, 0x5f, 0xd7, 0x1a, 0x07, 0x46, 0xd6, 0xea, 0x8b, 0xd0, 0x7c, 0xaa, 0xaf, 0xee,
	0x56, 0xd8, 0xd6, 0xb2, 0x7f, 0xc6, 0x06, 0xa7, 0xad, 0xbe, 0x38, 0x2d, 0x0d, 0x4e, 0xbb, 0x5b,
	0xa7, 0xc6, 0xe0, 0xdf, 0x59, 0x06, 0xbd, 0x79, 0xbd, 0x99, 0xed, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0x89, 0x8d, 0x60, 0x58, 0x0e, 0x00, 0x00,
}
