// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/errors/authorization_error.proto

package google_ads_googleads_v0_errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum describing possible authorization errors.
type AuthorizationErrorEnum_AuthorizationError int32

const (
	// Enum unspecified.
	AuthorizationErrorEnum_UNSPECIFIED AuthorizationErrorEnum_AuthorizationError = 0
	// The received error code is not known in this version.
	AuthorizationErrorEnum_UNKNOWN AuthorizationErrorEnum_AuthorizationError = 1
	// User doesn't have permission to access customer.
	AuthorizationErrorEnum_USER_PERMISSION_DENIED AuthorizationErrorEnum_AuthorizationError = 2
	// The developer token is not whitelisted.
	AuthorizationErrorEnum_DEVELOPER_TOKEN_NOT_WHITELISTED AuthorizationErrorEnum_AuthorizationError = 3
	// The developer token is not allowed with the project sent in the request.
	AuthorizationErrorEnum_DEVELOPER_TOKEN_PROHIBITED AuthorizationErrorEnum_AuthorizationError = 4
	// The Google Cloud project sent in the request does not have permission to
	// access the api.
	AuthorizationErrorEnum_PROJECT_DISABLED AuthorizationErrorEnum_AuthorizationError = 5
	// Authorization of the client failed.
	AuthorizationErrorEnum_AUTHORIZATION_ERROR AuthorizationErrorEnum_AuthorizationError = 6
)

var AuthorizationErrorEnum_AuthorizationError_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "UNKNOWN",
	2: "USER_PERMISSION_DENIED",
	3: "DEVELOPER_TOKEN_NOT_WHITELISTED",
	4: "DEVELOPER_TOKEN_PROHIBITED",
	5: "PROJECT_DISABLED",
	6: "AUTHORIZATION_ERROR",
}

var AuthorizationErrorEnum_AuthorizationError_value = map[string]int32{
	"UNSPECIFIED":                     0,
	"UNKNOWN":                         1,
	"USER_PERMISSION_DENIED":          2,
	"DEVELOPER_TOKEN_NOT_WHITELISTED": 3,
	"DEVELOPER_TOKEN_PROHIBITED":      4,
	"PROJECT_DISABLED":                5,
	"AUTHORIZATION_ERROR":             6,
}

func (x AuthorizationErrorEnum_AuthorizationError) String() string {
	return proto.EnumName(AuthorizationErrorEnum_AuthorizationError_name, int32(x))
}

func (AuthorizationErrorEnum_AuthorizationError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e07a13a2f7455f77, []int{0, 0}
}

// Container for enum describing possible authorization errors.
type AuthorizationErrorEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationErrorEnum) Reset()         { *m = AuthorizationErrorEnum{} }
func (m *AuthorizationErrorEnum) String() string { return proto.CompactTextString(m) }
func (*AuthorizationErrorEnum) ProtoMessage()    {}
func (*AuthorizationErrorEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07a13a2f7455f77, []int{0}
}
func (m *AuthorizationErrorEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationErrorEnum.Unmarshal(m, b)
}
func (m *AuthorizationErrorEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationErrorEnum.Marshal(b, m, deterministic)
}
func (m *AuthorizationErrorEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationErrorEnum.Merge(m, src)
}
func (m *AuthorizationErrorEnum) XXX_Size() int {
	return xxx_messageInfo_AuthorizationErrorEnum.Size(m)
}
func (m *AuthorizationErrorEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationErrorEnum.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationErrorEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AuthorizationErrorEnum)(nil), "google.ads.googleads.v0.errors.AuthorizationErrorEnum")
	proto.RegisterEnum("google.ads.googleads.v0.errors.AuthorizationErrorEnum_AuthorizationError", AuthorizationErrorEnum_AuthorizationError_name, AuthorizationErrorEnum_AuthorizationError_value)
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/errors/authorization_error.proto", fileDescriptor_e07a13a2f7455f77)
}

var fileDescriptor_e07a13a2f7455f77 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0xed, 0xa6, 0x13, 0xb2, 0x83, 0x25, 0xca, 0x06, 0x3b, 0x4c, 0x98, 0xf7, 0xb4, 0xe0,
	0xc5, 0x6b, 0xba, 0x7e, 0x6e, 0x71, 0x33, 0x29, 0x69, 0xbb, 0x81, 0x14, 0x42, 0xb5, 0x63, 0x0e,
	0xdc, 0x22, 0xed, 0xb6, 0x83, 0x8f, 0xe3, 0x49, 0x7c, 0x0c, 0x8f, 0xbe, 0x83, 0x17, 0x9f, 0x44,
	0xb2, 0xe2, 0x10, 0x07, 0x7a, 0xfb, 0xf1, 0x7d, 0xbf, 0x7f, 0x42, 0xfe, 0x41, 0x17, 0x53, 0xad,
	0xa7, 0x0f, 0x13, 0x27, 0xcd, 0x0a, 0xa7, 0x44, 0x43, 0x6b, 0xd7, 0x99, 0xe4, 0xb9, 0xce, 0x0b,
	0x27, 0x5d, 0x2d, 0xef, 0x75, 0x3e, 0x7b, 0x4a, 0x97, 0x33, 0xbd, 0x50, 0x9b, 0x21, 0x79, 0xcc,
	0xf5, 0x52, 0xe3, 0x76, 0xa9, 0x93, 0x34, 0x2b, 0xc8, 0x36, 0x49, 0xd6, 0x2e, 0x29, 0x93, 0x9d,
	0x0f, 0x0b, 0x35, 0xe8, 0xcf, 0x34, 0x98, 0x39, 0x2c, 0x56, 0xf3, 0xce, 0x9b, 0x85, 0xf0, 0xee,
	0x0a, 0x1f, 0xa1, 0x7a, 0xcc, 0xc3, 0x00, 0xba, 0xec, 0x92, 0x81, 0x6f, 0xef, 0xe1, 0x3a, 0x3a,
	0x8c, 0xf9, 0x80, 0x8b, 0x31, 0xb7, 0x2d, 0xdc, 0x42, 0x8d, 0x38, 0x04, 0xa9, 0x02, 0x90, 0xd7,
	0x2c, 0x0c, 0x99, 0xe0, 0xca, 0x07, 0x6e, 0xc4, 0x0a, 0x3e, 0x43, 0xa7, 0x3e, 0x8c, 0x60, 0x28,
	0x02, 0x90, 0x2a, 0x12, 0x03, 0xe0, 0x8a, 0x8b, 0x48, 0x8d, 0xfb, 0x2c, 0x82, 0x21, 0x0b, 0x23,
	0xf0, 0xed, 0x2a, 0x6e, 0xa3, 0xd6, 0x6f, 0x29, 0x90, 0xa2, 0xcf, 0x3c, 0x66, 0xf6, 0xfb, 0xf8,
	0x04, 0xd9, 0x81, 0x14, 0x57, 0xd0, 0x8d, 0x94, 0xcf, 0x42, 0xea, 0x0d, 0xc1, 0xb7, 0x0f, 0x70,
	0x13, 0x1d, 0xd3, 0x38, 0xea, 0x0b, 0xc9, 0x6e, 0x68, 0x64, 0x2e, 0x05, 0x29, 0x85, 0xb4, 0x6b,
	0xde, 0x8b, 0x85, 0x3a, 0x77, 0x7a, 0x4e, 0xfe, 0xae, 0xc1, 0x6b, 0xee, 0x3e, 0x34, 0x30, 0xfd,
	0x05, 0xd6, 0x73, 0xa5, 0xda, 0xa3, 0xf4, 0xb5, 0xd2, 0xee, 0x95, 0x27, 0xd0, 0xac, 0x20, 0x25,
	0x1a, 0x1a, 0xb9, 0x64, 0x23, 0x17, 0xef, 0xdf, 0x42, 0x42, 0xb3, 0x22, 0xd9, 0x0a, 0xc9, 0xc8,
	0x4d, 0x4a, 0xe1, 0xf3, 0x3f, 0xe1, 0xb6, 0xb6, 0xf9, 0xb1, 0xf3, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x74, 0x37, 0x6b, 0x73, 0xed, 0x01, 0x00, 0x00,
}
