// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/errors/bidding_strategy_error.proto

package google_ads_googleads_v0_errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum describing possible bidding strategy errors.
type BiddingStrategyErrorEnum_BiddingStrategyError int32

const (
	// Enum unspecified.
	BiddingStrategyErrorEnum_UNSPECIFIED BiddingStrategyErrorEnum_BiddingStrategyError = 0
	// The received error code is not known in this version.
	BiddingStrategyErrorEnum_UNKNOWN BiddingStrategyErrorEnum_BiddingStrategyError = 1
	// Each bidding strategy must have a unique name.
	BiddingStrategyErrorEnum_DUPLICATE_NAME BiddingStrategyErrorEnum_BiddingStrategyError = 2
	// Bidding strategy type is immutable.
	BiddingStrategyErrorEnum_CANNOT_CHANGE_BIDDING_STRATEGY_TYPE BiddingStrategyErrorEnum_BiddingStrategyError = 3
	// Only bidding strategies not linked to campaigns, adgroups or adgroup
	// criteria can be removed.
	BiddingStrategyErrorEnum_CANNOT_REMOVE_ASSOCIATED_STRATEGY BiddingStrategyErrorEnum_BiddingStrategyError = 4
	// The specified bidding strategy is not supported.
	BiddingStrategyErrorEnum_BIDDING_STRATEGY_NOT_SUPPORTED BiddingStrategyErrorEnum_BiddingStrategyError = 5
)

var BiddingStrategyErrorEnum_BiddingStrategyError_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "UNKNOWN",
	2: "DUPLICATE_NAME",
	3: "CANNOT_CHANGE_BIDDING_STRATEGY_TYPE",
	4: "CANNOT_REMOVE_ASSOCIATED_STRATEGY",
	5: "BIDDING_STRATEGY_NOT_SUPPORTED",
}

var BiddingStrategyErrorEnum_BiddingStrategyError_value = map[string]int32{
	"UNSPECIFIED":                         0,
	"UNKNOWN":                             1,
	"DUPLICATE_NAME":                      2,
	"CANNOT_CHANGE_BIDDING_STRATEGY_TYPE": 3,
	"CANNOT_REMOVE_ASSOCIATED_STRATEGY":   4,
	"BIDDING_STRATEGY_NOT_SUPPORTED":      5,
}

func (x BiddingStrategyErrorEnum_BiddingStrategyError) String() string {
	return proto.EnumName(BiddingStrategyErrorEnum_BiddingStrategyError_name, int32(x))
}

func (BiddingStrategyErrorEnum_BiddingStrategyError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0728bafc5c82bd9f, []int{0, 0}
}

// Container for enum describing possible bidding strategy errors.
type BiddingStrategyErrorEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiddingStrategyErrorEnum) Reset()         { *m = BiddingStrategyErrorEnum{} }
func (m *BiddingStrategyErrorEnum) String() string { return proto.CompactTextString(m) }
func (*BiddingStrategyErrorEnum) ProtoMessage()    {}
func (*BiddingStrategyErrorEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_0728bafc5c82bd9f, []int{0}
}
func (m *BiddingStrategyErrorEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiddingStrategyErrorEnum.Unmarshal(m, b)
}
func (m *BiddingStrategyErrorEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiddingStrategyErrorEnum.Marshal(b, m, deterministic)
}
func (m *BiddingStrategyErrorEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiddingStrategyErrorEnum.Merge(m, src)
}
func (m *BiddingStrategyErrorEnum) XXX_Size() int {
	return xxx_messageInfo_BiddingStrategyErrorEnum.Size(m)
}
func (m *BiddingStrategyErrorEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_BiddingStrategyErrorEnum.DiscardUnknown(m)
}

var xxx_messageInfo_BiddingStrategyErrorEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BiddingStrategyErrorEnum)(nil), "google.ads.googleads.v0.errors.BiddingStrategyErrorEnum")
	proto.RegisterEnum("google.ads.googleads.v0.errors.BiddingStrategyErrorEnum_BiddingStrategyError", BiddingStrategyErrorEnum_BiddingStrategyError_name, BiddingStrategyErrorEnum_BiddingStrategyError_value)
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/errors/bidding_strategy_error.proto", fileDescriptor_0728bafc5c82bd9f)
}

var fileDescriptor_0728bafc5c82bd9f = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4a, 0xc3, 0x40,
	0x14, 0xc6, 0x4d, 0xeb, 0x1f, 0x98, 0x82, 0x86, 0xc1, 0x85, 0x6e, 0x0a, 0x46, 0xc4, 0xdd, 0x24,
	0xe0, 0xd2, 0xd5, 0x24, 0x79, 0xc6, 0xa0, 0x9d, 0x0c, 0xcd, 0xa4, 0x52, 0x08, 0x0c, 0xad, 0x29,
	0xa1, 0x60, 0x3b, 0x92, 0xa9, 0x05, 0xaf, 0xe3, 0xb2, 0x67, 0xf0, 0x04, 0xde, 0xc0, 0xad, 0x27,
	0x91, 0x74, 0x6a, 0x36, 0x16, 0xdd, 0x7d, 0xcc, 0xfb, 0xfd, 0x3e, 0x98, 0xf7, 0xd0, 0x75, 0xa9,
	0x54, 0xf9, 0x34, 0x71, 0x47, 0x85, 0x76, 0x4d, 0xac, 0xd3, 0xd2, 0x73, 0x27, 0x55, 0xa5, 0x2a,
	0xed, 0x8e, 0xa7, 0x45, 0x31, 0x9d, 0x97, 0x52, 0x2f, 0xaa, 0xd1, 0x62, 0x52, 0xbe, 0xca, 0xf5,
	0x3b, 0x79, 0xae, 0xd4, 0x42, 0xe1, 0xae, 0x31, 0xc8, 0xa8, 0xd0, 0xa4, 0x91, 0xc9, 0xd2, 0x23,
	0x46, 0x76, 0x3e, 0x2d, 0x74, 0xe2, 0x9b, 0x82, 0x74, 0xe3, 0x43, 0x3d, 0x81, 0xf9, 0xcb, 0xcc,
	0x79, 0xb7, 0xd0, 0xf1, 0xb6, 0x21, 0x3e, 0x42, 0x9d, 0x8c, 0xa5, 0x1c, 0x82, 0xf8, 0x26, 0x86,
	0xd0, 0xde, 0xc1, 0x1d, 0x74, 0x90, 0xb1, 0x3b, 0x96, 0x3c, 0x30, 0xdb, 0xc2, 0x18, 0x1d, 0x86,
	0x19, 0xbf, 0x8f, 0x03, 0x2a, 0x40, 0x32, 0xda, 0x03, 0xbb, 0x85, 0x2f, 0xd1, 0x79, 0x40, 0x19,
	0x4b, 0x84, 0x0c, 0x6e, 0x29, 0x8b, 0x40, 0xfa, 0x71, 0x18, 0xc6, 0x2c, 0x92, 0xa9, 0xe8, 0x53,
	0x01, 0xd1, 0x50, 0x8a, 0x21, 0x07, 0xbb, 0x8d, 0x2f, 0xd0, 0xd9, 0x06, 0xec, 0x43, 0x2f, 0x19,
	0x80, 0xa4, 0x69, 0x9a, 0x04, 0x31, 0x15, 0x10, 0x36, 0xac, 0xbd, 0x8b, 0x1d, 0xd4, 0xfd, 0xd5,
	0x50, 0x4b, 0x69, 0xc6, 0x79, 0xd2, 0x17, 0x10, 0xda, 0x7b, 0xfe, 0xca, 0x42, 0xce, 0xa3, 0x9a,
	0x91, 0xbf, 0x57, 0xe0, 0x9f, 0x6e, 0xfb, 0x22, 0xaf, 0xb7, 0xc7, 0xad, 0xb7, 0x56, 0x3b, 0xa2,
	0x74, 0xd5, 0xea, 0x46, 0xa6, 0x83, 0x16, 0x9a, 0x98, 0x58, 0xa7, 0x81, 0x47, 0xd6, 0xb0, 0xfe,
	0xf8, 0x01, 0x72, 0x5a, 0xe8, 0xbc, 0x01, 0xf2, 0x81, 0x97, 0x1b, 0xe0, 0xeb, 0x3f, 0x60, 0xbc,
	0xbf, 0xbe, 0xd7, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x62, 0x3f, 0x4e, 0xee, 0x01,
	0x00, 0x00,
}
