// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v0/errors/function_parsing_error.proto

package google_ads_googleads_v0_errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum describing possible function parsing errors.
type FunctionParsingErrorEnum_FunctionParsingError int32

const (
	// Enum unspecified.
	FunctionParsingErrorEnum_UNSPECIFIED FunctionParsingErrorEnum_FunctionParsingError = 0
	// The received error code is not known in this version.
	FunctionParsingErrorEnum_UNKNOWN FunctionParsingErrorEnum_FunctionParsingError = 1
	// Unexpected end of function string.
	FunctionParsingErrorEnum_NO_MORE_INPUT FunctionParsingErrorEnum_FunctionParsingError = 2
	// Could not find an expected character.
	FunctionParsingErrorEnum_EXPECTED_CHARACTER FunctionParsingErrorEnum_FunctionParsingError = 3
	// Unexpected separator character.
	FunctionParsingErrorEnum_UNEXPECTED_SEPARATOR FunctionParsingErrorEnum_FunctionParsingError = 4
	// Unmatched left bracket or parenthesis.
	FunctionParsingErrorEnum_UNMATCHED_LEFT_BRACKET FunctionParsingErrorEnum_FunctionParsingError = 5
	// Unmatched right bracket or parenthesis.
	FunctionParsingErrorEnum_UNMATCHED_RIGHT_BRACKET FunctionParsingErrorEnum_FunctionParsingError = 6
	// Functions are nested too deeply.
	FunctionParsingErrorEnum_TOO_MANY_NESTED_FUNCTIONS FunctionParsingErrorEnum_FunctionParsingError = 7
	// Missing right-hand-side operand.
	FunctionParsingErrorEnum_MISSING_RIGHT_HAND_OPERAND FunctionParsingErrorEnum_FunctionParsingError = 8
	// Invalid operator/function name.
	FunctionParsingErrorEnum_INVALID_OPERATOR_NAME FunctionParsingErrorEnum_FunctionParsingError = 9
	// Feed attribute operand's argument is not an integer.
	FunctionParsingErrorEnum_FEED_ATTRIBUTE_OPERAND_ARGUMENT_NOT_INTEGER FunctionParsingErrorEnum_FunctionParsingError = 10
	// Missing function operands.
	FunctionParsingErrorEnum_NO_OPERANDS FunctionParsingErrorEnum_FunctionParsingError = 11
	// Function had too many operands.
	FunctionParsingErrorEnum_TOO_MANY_OPERANDS FunctionParsingErrorEnum_FunctionParsingError = 12
)

var FunctionParsingErrorEnum_FunctionParsingError_name = map[int32]string{
	0:  "UNSPECIFIED",
	1:  "UNKNOWN",
	2:  "NO_MORE_INPUT",
	3:  "EXPECTED_CHARACTER",
	4:  "UNEXPECTED_SEPARATOR",
	5:  "UNMATCHED_LEFT_BRACKET",
	6:  "UNMATCHED_RIGHT_BRACKET",
	7:  "TOO_MANY_NESTED_FUNCTIONS",
	8:  "MISSING_RIGHT_HAND_OPERAND",
	9:  "INVALID_OPERATOR_NAME",
	10: "FEED_ATTRIBUTE_OPERAND_ARGUMENT_NOT_INTEGER",
	11: "NO_OPERANDS",
	12: "TOO_MANY_OPERANDS",
}

var FunctionParsingErrorEnum_FunctionParsingError_value = map[string]int32{
	"UNSPECIFIED":                                 0,
	"UNKNOWN":                                     1,
	"NO_MORE_INPUT":                               2,
	"EXPECTED_CHARACTER":                          3,
	"UNEXPECTED_SEPARATOR":                        4,
	"UNMATCHED_LEFT_BRACKET":                      5,
	"UNMATCHED_RIGHT_BRACKET":                     6,
	"TOO_MANY_NESTED_FUNCTIONS":                   7,
	"MISSING_RIGHT_HAND_OPERAND":                  8,
	"INVALID_OPERATOR_NAME":                       9,
	"FEED_ATTRIBUTE_OPERAND_ARGUMENT_NOT_INTEGER": 10,
	"NO_OPERANDS":                                 11,
	"TOO_MANY_OPERANDS":                           12,
}

func (x FunctionParsingErrorEnum_FunctionParsingError) String() string {
	return proto.EnumName(FunctionParsingErrorEnum_FunctionParsingError_name, int32(x))
}

func (FunctionParsingErrorEnum_FunctionParsingError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d7874a447e476afb, []int{0, 0}
}

// Container for enum describing possible function parsing errors.
type FunctionParsingErrorEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionParsingErrorEnum) Reset()         { *m = FunctionParsingErrorEnum{} }
func (m *FunctionParsingErrorEnum) String() string { return proto.CompactTextString(m) }
func (*FunctionParsingErrorEnum) ProtoMessage()    {}
func (*FunctionParsingErrorEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7874a447e476afb, []int{0}
}
func (m *FunctionParsingErrorEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionParsingErrorEnum.Unmarshal(m, b)
}
func (m *FunctionParsingErrorEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionParsingErrorEnum.Marshal(b, m, deterministic)
}
func (m *FunctionParsingErrorEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionParsingErrorEnum.Merge(m, src)
}
func (m *FunctionParsingErrorEnum) XXX_Size() int {
	return xxx_messageInfo_FunctionParsingErrorEnum.Size(m)
}
func (m *FunctionParsingErrorEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionParsingErrorEnum.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionParsingErrorEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FunctionParsingErrorEnum)(nil), "google.ads.googleads.v0.errors.FunctionParsingErrorEnum")
	proto.RegisterEnum("google.ads.googleads.v0.errors.FunctionParsingErrorEnum_FunctionParsingError", FunctionParsingErrorEnum_FunctionParsingError_name, FunctionParsingErrorEnum_FunctionParsingError_value)
}

func init() {
	proto.RegisterFile("google/ads/googleads/v0/errors/function_parsing_error.proto", fileDescriptor_d7874a447e476afb)
}

var fileDescriptor_d7874a447e476afb = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x69, 0x02, 0x2d, 0x4c, 0x40, 0x6c, 0x57, 0x6d, 0x69, 0x8a, 0xc8, 0x21, 0x57, 0x24,
	0x3b, 0x12, 0x47, 0x4e, 0x13, 0x7b, 0xec, 0xac, 0x5a, 0xcf, 0x5a, 0xeb, 0x75, 0x00, 0x29, 0xd2,
	0x2a, 0x34, 0x25, 0xaa, 0x44, 0xe3, 0xca, 0x6e, 0xfb, 0x00, 0x3c, 0x0a, 0xc7, 0x3e, 0x0a, 0x8f,
	0x81, 0xc4, 0x7b, 0x20, 0xc7, 0x89, 0x7b, 0xa9, 0xe0, 0xf6, 0x6b, 0xfe, 0xef, 0x1b, 0x59, 0x9e,
	0x85, 0x8f, 0xcb, 0xa2, 0x58, 0x7e, 0xbf, 0xf0, 0xe7, 0x8b, 0xca, 0x6f, 0x62, 0x9d, 0xee, 0x46,
	0xfe, 0x45, 0x59, 0x16, 0x65, 0xe5, 0x7f, 0xbb, 0x5d, 0x9d, 0xdf, 0x5c, 0x16, 0x2b, 0x77, 0x3d,
	0x2f, 0xab, 0xcb, 0xd5, 0xd2, 0xad, 0xe7, 0xde, 0x75, 0x59, 0xdc, 0x14, 0x72, 0xd0, 0x18, 0xde,
	0x7c, 0x51, 0x79, 0xad, 0xec, 0xdd, 0x8d, 0xbc, 0x46, 0x1e, 0xfe, 0xe8, 0xc2, 0x71, 0xb4, 0x59,
	0x90, 0x36, 0x3e, 0xd5, 0x0d, 0xad, 0x6e, 0xaf, 0x86, 0x7f, 0x3a, 0x70, 0xf0, 0x58, 0x29, 0x5f,
	0x43, 0x2f, 0xe7, 0x2c, 0xa5, 0x40, 0x45, 0x8a, 0x42, 0xf1, 0x44, 0xf6, 0x60, 0x2f, 0xe7, 0x53,
	0xd6, 0x9f, 0x58, 0xec, 0xc8, 0x7d, 0x78, 0xc5, 0xda, 0x25, 0xda, 0x90, 0x53, 0x9c, 0xe6, 0x56,
	0x74, 0xe4, 0x11, 0x48, 0xfa, 0x9c, 0x52, 0x60, 0x29, 0x74, 0xc1, 0x04, 0x0d, 0x06, 0x96, 0x8c,
	0xe8, 0xca, 0x63, 0x38, 0xc8, 0xb9, 0x6d, 0x32, 0x4a, 0xd1, 0xa0, 0xd5, 0x46, 0x3c, 0x95, 0x27,
	0x70, 0x94, 0x73, 0x82, 0x36, 0x98, 0x50, 0xe8, 0xce, 0x28, 0xb2, 0x6e, 0x6c, 0x30, 0x38, 0x25,
	0x2b, 0x9e, 0xc9, 0xb7, 0xf0, 0xe6, 0xa1, 0x33, 0x2a, 0x9e, 0x3c, 0x94, 0xbb, 0xf2, 0x1d, 0xf4,
	0xad, 0xd6, 0x2e, 0x41, 0xfe, 0xe2, 0x98, 0xb2, 0x7a, 0x6f, 0x94, 0x73, 0x60, 0x95, 0xe6, 0x4c,
	0xec, 0xc9, 0x01, 0x9c, 0x24, 0x2a, 0xcb, 0x14, 0xc7, 0x1b, 0x73, 0x82, 0x1c, 0x3a, 0x9d, 0x92,
	0x41, 0x0e, 0xc5, 0x73, 0xd9, 0x87, 0x43, 0xc5, 0x53, 0x3c, 0x53, 0x9b, 0xa1, 0xd5, 0xc6, 0x31,
	0x26, 0x24, 0x5e, 0x48, 0x1f, 0xde, 0x47, 0x44, 0xa1, 0x43, 0x6b, 0x8d, 0x1a, 0xe7, 0x96, 0xb6,
	0x9a, 0x43, 0x13, 0xe7, 0x09, 0xb1, 0x75, 0xac, 0xad, 0x53, 0x6c, 0x29, 0x26, 0x23, 0xa0, 0xfe,
	0x4d, 0xac, 0xb7, 0x50, 0x26, 0x7a, 0xf2, 0x10, 0xf6, 0xdb, 0x6f, 0x6b, 0xc7, 0x2f, 0xc7, 0xf7,
	0x3b, 0x30, 0x3c, 0x2f, 0xae, 0xbc, 0x7f, 0xdf, 0x6a, 0xdc, 0x7f, 0xec, 0x16, 0x69, 0x7d, 0xe6,
	0x74, 0xe7, 0x67, 0xa7, 0x1b, 0x23, 0xde, 0x77, 0x06, 0x71, 0xb3, 0x03, 0x17, 0x95, 0xd7, 0xc4,
	0x3a, 0x4d, 0x47, 0xde, 0x1a, 0xae, 0x7e, 0x6d, 0x81, 0x19, 0x2e, 0xaa, 0x59, 0x0b, 0xcc, 0xa6,
	0xa3, 0x59, 0x03, 0xfc, 0xfe, 0x1f, 0xf0, 0x75, 0x77, 0xfd, 0xb0, 0x3e, 0xfc, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0x01, 0x96, 0x49, 0x97, 0x02, 0x00, 0x00,
}
