// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v0/errors/function_error.proto

package google_ads_googleads_v0_errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum describing possible function errors.
type FunctionErrorEnum_FunctionError int32

const (
	// Enum unspecified.
	FunctionErrorEnum_UNSPECIFIED FunctionErrorEnum_FunctionError = 0
	// The received error code is not known in this version.
	FunctionErrorEnum_UNKNOWN FunctionErrorEnum_FunctionError = 1
	// The format of the function is not recognized as a supported function
	// format.
	FunctionErrorEnum_INVALID_FUNCTION_FORMAT FunctionErrorEnum_FunctionError = 2
	// Operand data types do not match.
	FunctionErrorEnum_DATA_TYPE_MISMATCH FunctionErrorEnum_FunctionError = 3
	// The operands cannot be used together in a conjunction.
	FunctionErrorEnum_INVALID_CONJUNCTION_OPERANDS FunctionErrorEnum_FunctionError = 4
	// Invalid numer of Operands.
	FunctionErrorEnum_INVALID_NUMBER_OF_OPERANDS FunctionErrorEnum_FunctionError = 5
	// Operand Type not supported.
	FunctionErrorEnum_INVALID_OPERAND_TYPE FunctionErrorEnum_FunctionError = 6
	// Operator not supported.
	FunctionErrorEnum_INVALID_OPERATOR FunctionErrorEnum_FunctionError = 7
	// Request context type not supported.
	FunctionErrorEnum_INVALID_REQUEST_CONTEXT_TYPE FunctionErrorEnum_FunctionError = 8
	// The matching function is not allowed for call placeholders
	FunctionErrorEnum_INVALID_FUNCTION_FOR_CALL_PLACEHOLDER FunctionErrorEnum_FunctionError = 9
	// The matching function is not allowed for the specified placeholder
	FunctionErrorEnum_INVALID_FUNCTION_FOR_PLACEHOLDER FunctionErrorEnum_FunctionError = 10
	// Invalid operand.
	FunctionErrorEnum_INVALID_OPERAND FunctionErrorEnum_FunctionError = 11
	// Missing value for the constant operand.
	FunctionErrorEnum_MISSING_CONSTANT_OPERAND_VALUE FunctionErrorEnum_FunctionError = 12
	// The value of the constant operand is invalid.
	FunctionErrorEnum_INVALID_CONSTANT_OPERAND_VALUE FunctionErrorEnum_FunctionError = 13
	// Invalid function nesting.
	FunctionErrorEnum_INVALID_NESTING FunctionErrorEnum_FunctionError = 14
	// The Feed ID was different from another Feed ID in the same function.
	FunctionErrorEnum_MULTIPLE_FEED_IDS_NOT_SUPPORTED FunctionErrorEnum_FunctionError = 15
	// The matching function is invalid for use with a feed with a fixed schema.
	FunctionErrorEnum_INVALID_FUNCTION_FOR_FEED_WITH_FIXED_SCHEMA FunctionErrorEnum_FunctionError = 16
	// Invalid attribute name.
	FunctionErrorEnum_INVALID_ATTRIBUTE_NAME FunctionErrorEnum_FunctionError = 17
)

var FunctionErrorEnum_FunctionError_name = map[int32]string{
	0:  "UNSPECIFIED",
	1:  "UNKNOWN",
	2:  "INVALID_FUNCTION_FORMAT",
	3:  "DATA_TYPE_MISMATCH",
	4:  "INVALID_CONJUNCTION_OPERANDS",
	5:  "INVALID_NUMBER_OF_OPERANDS",
	6:  "INVALID_OPERAND_TYPE",
	7:  "INVALID_OPERATOR",
	8:  "INVALID_REQUEST_CONTEXT_TYPE",
	9:  "INVALID_FUNCTION_FOR_CALL_PLACEHOLDER",
	10: "INVALID_FUNCTION_FOR_PLACEHOLDER",
	11: "INVALID_OPERAND",
	12: "MISSING_CONSTANT_OPERAND_VALUE",
	13: "INVALID_CONSTANT_OPERAND_VALUE",
	14: "INVALID_NESTING",
	15: "MULTIPLE_FEED_IDS_NOT_SUPPORTED",
	16: "INVALID_FUNCTION_FOR_FEED_WITH_FIXED_SCHEMA",
	17: "INVALID_ATTRIBUTE_NAME",
}

var FunctionErrorEnum_FunctionError_value = map[string]int32{
	"UNSPECIFIED":                                 0,
	"UNKNOWN":                                     1,
	"INVALID_FUNCTION_FORMAT":                     2,
	"DATA_TYPE_MISMATCH":                          3,
	"INVALID_CONJUNCTION_OPERANDS":                4,
	"INVALID_NUMBER_OF_OPERANDS":                  5,
	"INVALID_OPERAND_TYPE":                        6,
	"INVALID_OPERATOR":                            7,
	"INVALID_REQUEST_CONTEXT_TYPE":                8,
	"INVALID_FUNCTION_FOR_CALL_PLACEHOLDER":       9,
	"INVALID_FUNCTION_FOR_PLACEHOLDER":            10,
	"INVALID_OPERAND":                             11,
	"MISSING_CONSTANT_OPERAND_VALUE":              12,
	"INVALID_CONSTANT_OPERAND_VALUE":              13,
	"INVALID_NESTING":                             14,
	"MULTIPLE_FEED_IDS_NOT_SUPPORTED":             15,
	"INVALID_FUNCTION_FOR_FEED_WITH_FIXED_SCHEMA": 16,
	"INVALID_ATTRIBUTE_NAME":                      17,
}

func (x FunctionErrorEnum_FunctionError) String() string {
	return proto.EnumName(FunctionErrorEnum_FunctionError_name, int32(x))
}

func (FunctionErrorEnum_FunctionError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_855fd6ada22aea64, []int{0, 0}
}

// Container for enum describing possible function errors.
type FunctionErrorEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionErrorEnum) Reset()         { *m = FunctionErrorEnum{} }
func (m *FunctionErrorEnum) String() string { return proto.CompactTextString(m) }
func (*FunctionErrorEnum) ProtoMessage()    {}
func (*FunctionErrorEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_855fd6ada22aea64, []int{0}
}
func (m *FunctionErrorEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionErrorEnum.Unmarshal(m, b)
}
func (m *FunctionErrorEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionErrorEnum.Marshal(b, m, deterministic)
}
func (m *FunctionErrorEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionErrorEnum.Merge(m, src)
}
func (m *FunctionErrorEnum) XXX_Size() int {
	return xxx_messageInfo_FunctionErrorEnum.Size(m)
}
func (m *FunctionErrorEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionErrorEnum.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionErrorEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FunctionErrorEnum)(nil), "google.ads.googleads.v0.errors.FunctionErrorEnum")
	proto.RegisterEnum("google.ads.googleads.v0.errors.FunctionErrorEnum_FunctionError", FunctionErrorEnum_FunctionError_name, FunctionErrorEnum_FunctionError_value)
}

func init() {
	proto.RegisterFile("google/ads/googleads/v0/errors/function_error.proto", fileDescriptor_855fd6ada22aea64)
}

var fileDescriptor_855fd6ada22aea64 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x51, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x49, 0x1a, 0x5a, 0x98, 0x50, 0xb2, 0x5d, 0xaa, 0x82, 0x0a, 0x0a, 0x55, 0x80, 0x07,
	0x84, 0x64, 0x47, 0xea, 0x09, 0x36, 0xf6, 0x38, 0x59, 0xb0, 0x77, 0x8d, 0x77, 0x9c, 0x16, 0x29,
	0xd2, 0xaa, 0x34, 0xa5, 0x42, 0xa2, 0x31, 0x8a, 0xdb, 0x1e, 0x08, 0xde, 0xe0, 0x14, 0xbc, 0x72,
	0x0c, 0x4e, 0x82, 0x6c, 0xd7, 0x21, 0x41, 0x11, 0xbc, 0x8d, 0x67, 0xbe, 0xcf, 0xff, 0xae, 0x35,
	0x86, 0xc3, 0xf3, 0x2c, 0x3b, 0xff, 0x74, 0xe6, 0x9e, 0x4c, 0x73, 0xb7, 0x2a, 0x8b, 0xea, 0xba,
	0xef, 0x9e, 0xcd, 0xe7, 0xd9, 0x3c, 0x77, 0x3f, 0x5c, 0xcd, 0x4e, 0x2f, 0x3f, 0x66, 0x33, 0x5b,
	0x3e, 0x3b, 0x9f, 0xe7, 0xd9, 0x65, 0xc6, 0xbb, 0x15, 0xe9, 0x9c, 0x4c, 0x73, 0x67, 0x21, 0x39,
	0xd7, 0x7d, 0xa7, 0x92, 0x7a, 0x3f, 0x5a, 0xb0, 0x13, 0xdc, 0x88, 0x58, 0xb4, 0x70, 0x76, 0x75,
	0xd1, 0xfb, 0xde, 0x82, 0xed, 0x95, 0x2e, 0xef, 0x40, 0x3b, 0x55, 0x26, 0x46, 0x4f, 0x06, 0x12,
	0x7d, 0x76, 0x8b, 0xb7, 0x61, 0x2b, 0x55, 0x6f, 0x94, 0x3e, 0x52, 0xac, 0xc1, 0x1f, 0xc3, 0x43,
	0xa9, 0xc6, 0x22, 0x94, 0xbe, 0x0d, 0x52, 0xe5, 0x91, 0xd4, 0xca, 0x06, 0x3a, 0x89, 0x04, 0xb1,
	0x26, 0xdf, 0x03, 0xee, 0x0b, 0x12, 0x96, 0xde, 0xc5, 0x68, 0x23, 0x69, 0x22, 0x41, 0xde, 0x88,
	0x6d, 0xf0, 0x03, 0x78, 0x52, 0x4b, 0x9e, 0x56, 0xaf, 0x6b, 0x4f, 0xc7, 0x98, 0x08, 0xe5, 0x1b,
	0xd6, 0xe2, 0x5d, 0xd8, 0xaf, 0x09, 0x95, 0x46, 0x03, 0x4c, 0xac, 0x0e, 0xfe, 0xcc, 0x6f, 0xf3,
	0x47, 0xb0, 0x5b, 0xcf, 0x6f, 0xba, 0x65, 0x08, 0xdb, 0xe4, 0xbb, 0xc0, 0x56, 0x26, 0xa4, 0x13,
	0xb6, 0xb5, 0x9c, 0x98, 0xe0, 0xdb, 0x14, 0x0d, 0x15, 0xc9, 0x84, 0xc7, 0x54, 0x79, 0x77, 0xf8,
	0x4b, 0x78, 0xb1, 0xee, 0x22, 0xd6, 0x13, 0x61, 0x68, 0xe3, 0x50, 0x78, 0x38, 0xd2, 0xa1, 0x8f,
	0x09, 0xbb, 0xcb, 0x9f, 0xc3, 0xc1, 0x5a, 0x74, 0x99, 0x02, 0xfe, 0x00, 0x3a, 0x7f, 0x1d, 0x91,
	0xb5, 0x79, 0x0f, 0xba, 0x91, 0x34, 0x46, 0xaa, 0x61, 0x91, 0x6f, 0x48, 0x28, 0x5a, 0x5c, 0x60,
	0x2c, 0xc2, 0x14, 0xd9, 0xbd, 0x82, 0x59, 0xfa, 0x3a, 0xeb, 0x98, 0xed, 0xe5, 0x97, 0x2b, 0x34,
	0x24, 0xd5, 0x90, 0xdd, 0xe7, 0xcf, 0xe0, 0x69, 0x94, 0x86, 0x24, 0xe3, 0x10, 0x6d, 0x80, 0xe8,
	0x5b, 0xe9, 0x1b, 0xab, 0x34, 0x59, 0x93, 0xc6, 0xb1, 0x4e, 0x08, 0x7d, 0xd6, 0xe1, 0x2e, 0xbc,
	0x5a, 0x7b, 0xf8, 0x52, 0x38, 0x92, 0x34, 0xb2, 0x81, 0x3c, 0x46, 0xdf, 0x1a, 0x6f, 0x84, 0x91,
	0x60, 0x8c, 0xef, 0xc3, 0x5e, 0x2d, 0x08, 0xa2, 0x44, 0x0e, 0x52, 0x42, 0xab, 0x44, 0x84, 0x6c,
	0x67, 0xf0, 0xb5, 0x01, 0xbd, 0xd3, 0xec, 0xc2, 0xf9, 0xf7, 0xaa, 0x0d, 0xf8, 0xca, 0x46, 0xc5,
	0xc5, 0x7a, 0xc6, 0x8d, 0x2f, 0xcd, 0x8d, 0xa1, 0x10, 0xdf, 0x9a, 0xdd, 0x61, 0x25, 0x8b, 0x69,
	0xee, 0x54, 0x65, 0x51, 0x8d, 0xfb, 0x4e, 0x09, 0xe7, 0x3f, 0x6b, 0x60, 0x22, 0xa6, 0xf9, 0x64,
	0x01, 0x4c, 0xc6, 0xfd, 0x49, 0x05, 0xfc, 0xfa, 0x1f, 0xf0, 0x7e, 0xb3, 0xfc, 0x21, 0x0e, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x80, 0xc9, 0xca, 0x34, 0x47, 0x03, 0x00, 0x00,
}
