// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/errors/media_bundle_error.proto

package google_ads_googleads_v0_errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum describing possible media bundle errors.
type MediaBundleErrorEnum_MediaBundleError int32

const (
	// Enum unspecified.
	MediaBundleErrorEnum_UNSPECIFIED MediaBundleErrorEnum_MediaBundleError = 0
	// The received error code is not known in this version.
	MediaBundleErrorEnum_UNKNOWN MediaBundleErrorEnum_MediaBundleError = 1
	// There was a problem with the request.
	MediaBundleErrorEnum_BAD_REQUEST MediaBundleErrorEnum_MediaBundleError = 3
	// HTML5 ads using DoubleClick Studio created ZIP files are not supported.
	MediaBundleErrorEnum_DOUBLECLICK_BUNDLE_NOT_ALLOWED MediaBundleErrorEnum_MediaBundleError = 4
	// Cannot reference URL external to the media bundle.
	MediaBundleErrorEnum_EXTERNAL_URL_NOT_ALLOWED MediaBundleErrorEnum_MediaBundleError = 5
	// Media bundle file is too large.
	MediaBundleErrorEnum_FILE_TOO_LARGE MediaBundleErrorEnum_MediaBundleError = 6
	// ZIP file from Google Web Designer is not published.
	MediaBundleErrorEnum_GOOGLE_WEB_DESIGNER_ZIP_FILE_NOT_PUBLISHED MediaBundleErrorEnum_MediaBundleError = 7
	// Input was invalid.
	MediaBundleErrorEnum_INVALID_INPUT MediaBundleErrorEnum_MediaBundleError = 8
	// There was a problem with the media bundle.
	MediaBundleErrorEnum_INVALID_MEDIA_BUNDLE MediaBundleErrorEnum_MediaBundleError = 9
	// There was a problem with one or more of the media bundle entries.
	MediaBundleErrorEnum_INVALID_MEDIA_BUNDLE_ENTRY MediaBundleErrorEnum_MediaBundleError = 10
	// The media bundle contains a file with an unknown mime type
	MediaBundleErrorEnum_INVALID_MIME_TYPE MediaBundleErrorEnum_MediaBundleError = 11
	// The media bundle contain an invalid asset path.
	MediaBundleErrorEnum_INVALID_PATH MediaBundleErrorEnum_MediaBundleError = 12
	// HTML5 ad is trying to reference an asset not in .ZIP file
	MediaBundleErrorEnum_INVALID_URL_REFERENCE MediaBundleErrorEnum_MediaBundleError = 13
	// Media data is too large.
	MediaBundleErrorEnum_MEDIA_DATA_TOO_LARGE MediaBundleErrorEnum_MediaBundleError = 14
	// The media bundle contains no primary entry.
	MediaBundleErrorEnum_MISSING_PRIMARY_MEDIA_BUNDLE_ENTRY MediaBundleErrorEnum_MediaBundleError = 15
	// There was an error on the server.
	MediaBundleErrorEnum_SERVER_ERROR MediaBundleErrorEnum_MediaBundleError = 16
	// The image could not be stored.
	MediaBundleErrorEnum_STORAGE_ERROR MediaBundleErrorEnum_MediaBundleError = 17
	// Media bundle created with the Swiffy tool is not allowed.
	MediaBundleErrorEnum_SWIFFY_BUNDLE_NOT_ALLOWED MediaBundleErrorEnum_MediaBundleError = 18
	// The media bundle contains too many files.
	MediaBundleErrorEnum_TOO_MANY_FILES MediaBundleErrorEnum_MediaBundleError = 19
	// The media bundle is not of legal dimensions.
	MediaBundleErrorEnum_UNEXPECTED_SIZE MediaBundleErrorEnum_MediaBundleError = 20
	// Google Web Designer not created for "AdWords" environment.
	MediaBundleErrorEnum_UNSUPPORTED_GOOGLE_WEB_DESIGNER_ENVIRONMENT MediaBundleErrorEnum_MediaBundleError = 21
	// Unsupported HTML5 feature in HTML5 asset.
	MediaBundleErrorEnum_UNSUPPORTED_HTML5_FEATURE MediaBundleErrorEnum_MediaBundleError = 22
	// URL in HTML5 entry is not ssl compliant.
	MediaBundleErrorEnum_URL_IN_MEDIA_BUNDLE_NOT_SSL_COMPLIANT MediaBundleErrorEnum_MediaBundleError = 23
	// Custom exits not allowed in HTML5 entry.
	MediaBundleErrorEnum_CUSTOM_EXIT_NOT_ALLOWED MediaBundleErrorEnum_MediaBundleError = 24
)

var MediaBundleErrorEnum_MediaBundleError_name = map[int32]string{
	0:  "UNSPECIFIED",
	1:  "UNKNOWN",
	3:  "BAD_REQUEST",
	4:  "DOUBLECLICK_BUNDLE_NOT_ALLOWED",
	5:  "EXTERNAL_URL_NOT_ALLOWED",
	6:  "FILE_TOO_LARGE",
	7:  "GOOGLE_WEB_DESIGNER_ZIP_FILE_NOT_PUBLISHED",
	8:  "INVALID_INPUT",
	9:  "INVALID_MEDIA_BUNDLE",
	10: "INVALID_MEDIA_BUNDLE_ENTRY",
	11: "INVALID_MIME_TYPE",
	12: "INVALID_PATH",
	13: "INVALID_URL_REFERENCE",
	14: "MEDIA_DATA_TOO_LARGE",
	15: "MISSING_PRIMARY_MEDIA_BUNDLE_ENTRY",
	16: "SERVER_ERROR",
	17: "STORAGE_ERROR",
	18: "SWIFFY_BUNDLE_NOT_ALLOWED",
	19: "TOO_MANY_FILES",
	20: "UNEXPECTED_SIZE",
	21: "UNSUPPORTED_GOOGLE_WEB_DESIGNER_ENVIRONMENT",
	22: "UNSUPPORTED_HTML5_FEATURE",
	23: "URL_IN_MEDIA_BUNDLE_NOT_SSL_COMPLIANT",
	24: "CUSTOM_EXIT_NOT_ALLOWED",
}

var MediaBundleErrorEnum_MediaBundleError_value = map[string]int32{
	"UNSPECIFIED":                    0,
	"UNKNOWN":                        1,
	"BAD_REQUEST":                    3,
	"DOUBLECLICK_BUNDLE_NOT_ALLOWED": 4,
	"EXTERNAL_URL_NOT_ALLOWED":       5,
	"FILE_TOO_LARGE":                 6,
	"GOOGLE_WEB_DESIGNER_ZIP_FILE_NOT_PUBLISHED": 7,
	"INVALID_INPUT":                               8,
	"INVALID_MEDIA_BUNDLE":                        9,
	"INVALID_MEDIA_BUNDLE_ENTRY":                  10,
	"INVALID_MIME_TYPE":                           11,
	"INVALID_PATH":                                12,
	"INVALID_URL_REFERENCE":                       13,
	"MEDIA_DATA_TOO_LARGE":                        14,
	"MISSING_PRIMARY_MEDIA_BUNDLE_ENTRY":          15,
	"SERVER_ERROR":                                16,
	"STORAGE_ERROR":                               17,
	"SWIFFY_BUNDLE_NOT_ALLOWED":                   18,
	"TOO_MANY_FILES":                              19,
	"UNEXPECTED_SIZE":                             20,
	"UNSUPPORTED_GOOGLE_WEB_DESIGNER_ENVIRONMENT": 21,
	"UNSUPPORTED_HTML5_FEATURE":                   22,
	"URL_IN_MEDIA_BUNDLE_NOT_SSL_COMPLIANT":       23,
	"CUSTOM_EXIT_NOT_ALLOWED":                     24,
}

func (x MediaBundleErrorEnum_MediaBundleError) String() string {
	return proto.EnumName(MediaBundleErrorEnum_MediaBundleError_name, int32(x))
}

func (MediaBundleErrorEnum_MediaBundleError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e1b604261dae857, []int{0, 0}
}

// Container for enum describing possible media bundle errors.
type MediaBundleErrorEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaBundleErrorEnum) Reset()         { *m = MediaBundleErrorEnum{} }
func (m *MediaBundleErrorEnum) String() string { return proto.CompactTextString(m) }
func (*MediaBundleErrorEnum) ProtoMessage()    {}
func (*MediaBundleErrorEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e1b604261dae857, []int{0}
}
func (m *MediaBundleErrorEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaBundleErrorEnum.Unmarshal(m, b)
}
func (m *MediaBundleErrorEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaBundleErrorEnum.Marshal(b, m, deterministic)
}
func (m *MediaBundleErrorEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaBundleErrorEnum.Merge(m, src)
}
func (m *MediaBundleErrorEnum) XXX_Size() int {
	return xxx_messageInfo_MediaBundleErrorEnum.Size(m)
}
func (m *MediaBundleErrorEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaBundleErrorEnum.DiscardUnknown(m)
}

var xxx_messageInfo_MediaBundleErrorEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MediaBundleErrorEnum)(nil), "google.ads.googleads.v0.errors.MediaBundleErrorEnum")
	proto.RegisterEnum("google.ads.googleads.v0.errors.MediaBundleErrorEnum_MediaBundleError", MediaBundleErrorEnum_MediaBundleError_name, MediaBundleErrorEnum_MediaBundleError_value)
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/errors/media_bundle_error.proto", fileDescriptor_8e1b604261dae857)
}

var fileDescriptor_8e1b604261dae857 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xdb, 0x4e, 0x14, 0x31,
	0x18, 0x16, 0x10, 0xd0, 0x72, 0x2a, 0x85, 0x15, 0xf0, 0xb0, 0x17, 0x9b, 0x68, 0xa2, 0x26, 0xb3,
	0x9b, 0x18, 0xe3, 0x75, 0x67, 0xe6, 0xdf, 0xa1, 0xa1, 0xd3, 0xd6, 0x1e, 0x76, 0x59, 0xb2, 0x49,
	0x03, 0xee, 0x86, 0x98, 0x00, 0x63, 0x76, 0x84, 0xd7, 0x31, 0xf1, 0xc2, 0x0b, 0x9f, 0xc0, 0x67,
	0xf0, 0x31, 0x7c, 0x12, 0xd3, 0x19, 0x96, 0x00, 0xd9, 0xe8, 0xdd, 0x9f, 0xef, 0xd0, 0xbf, 0xdf,
	0x97, 0x16, 0x7d, 0x38, 0x2d, 0x8a, 0xd3, 0xb3, 0x71, 0xfb, 0x78, 0x54, 0xb6, 0xeb, 0x31, 0x4c,
	0x57, 0x9d, 0xf6, 0x78, 0x32, 0x29, 0x26, 0x65, 0xfb, 0x7c, 0x3c, 0xfa, 0x7c, 0xec, 0x4f, 0x2e,
	0x2f, 0x46, 0x67, 0x63, 0x5f, 0x61, 0xd1, 0x97, 0x49, 0xf1, 0xb5, 0x20, 0xcd, 0x5a, 0x1d, 0x1d,
	0x8f, 0xca, 0xe8, 0xc6, 0x18, 0x5d, 0x75, 0xa2, 0xda, 0xd8, 0xfa, 0xb5, 0x88, 0xb6, 0xf3, 0x60,
	0x8e, 0x2b, 0x2f, 0x04, 0x14, 0x2e, 0x2e, 0xcf, 0x5b, 0xdf, 0x16, 0x11, 0xbe, 0x4f, 0x90, 0x0d,
	0xb4, 0xe2, 0x84, 0x51, 0x90, 0xb0, 0x2e, 0x83, 0x14, 0x3f, 0x20, 0x2b, 0x68, 0xd9, 0x89, 0x03,
	0x21, 0xfb, 0x02, 0xcf, 0x05, 0x36, 0xa6, 0xa9, 0xd7, 0xf0, 0xd1, 0x81, 0xb1, 0x78, 0x81, 0xb4,
	0x50, 0x33, 0x95, 0x2e, 0xe6, 0x90, 0x70, 0x96, 0x1c, 0xf8, 0xd8, 0x89, 0x94, 0x83, 0x17, 0xd2,
	0x7a, 0xca, 0xb9, 0xec, 0x43, 0x8a, 0x1f, 0x92, 0xe7, 0x68, 0x17, 0x0e, 0x2d, 0x68, 0x41, 0xb9,
	0x77, 0x9a, 0xdf, 0x61, 0x17, 0x09, 0x41, 0xeb, 0x5d, 0xc6, 0xc1, 0x5b, 0x29, 0x3d, 0xa7, 0x3a,
	0x03, 0xbc, 0x44, 0x22, 0xf4, 0x26, 0x93, 0x32, 0xe3, 0xe0, 0xfb, 0x10, 0xfb, 0x14, 0x0c, 0xcb,
	0x04, 0x68, 0x7f, 0xc4, 0x94, 0xaf, 0xb4, 0xe1, 0x04, 0xe5, 0x62, 0xce, 0xcc, 0x3e, 0xa4, 0x78,
	0x99, 0x6c, 0xa2, 0x35, 0x26, 0x7a, 0x94, 0xb3, 0xd4, 0x33, 0xa1, 0x9c, 0xc5, 0x8f, 0xc8, 0x2e,
	0xda, 0x9e, 0x42, 0x39, 0xa4, 0x8c, 0x5e, 0x5f, 0x0d, 0x3f, 0x26, 0x4d, 0xf4, 0x74, 0x16, 0xe3,
	0x41, 0x58, 0x3d, 0xc0, 0x88, 0x34, 0xd0, 0xe6, 0x0d, 0xcf, 0x72, 0xf0, 0x76, 0xa0, 0x00, 0xaf,
	0x10, 0x8c, 0x56, 0xa7, 0xb0, 0xa2, 0x76, 0x1f, 0xaf, 0x92, 0x3d, 0xd4, 0x98, 0x22, 0x21, 0x96,
	0x86, 0x2e, 0x68, 0x10, 0x09, 0xe0, 0xb5, 0xb0, 0xbd, 0x3e, 0x3b, 0xa5, 0x96, 0xde, 0x8a, 0xb6,
	0x4e, 0x5e, 0xa1, 0x56, 0xce, 0x8c, 0x61, 0x22, 0xf3, 0x4a, 0xb3, 0x9c, 0xea, 0xc1, 0xac, 0x5b,
	0x6c, 0x84, 0x75, 0x06, 0x74, 0x0f, 0xb4, 0x07, 0xad, 0xa5, 0xc6, 0x38, 0x84, 0x34, 0x56, 0x6a,
	0x9a, 0xc1, 0x35, 0xb4, 0x49, 0x5e, 0xa0, 0x3d, 0xd3, 0x67, 0xdd, 0xee, 0x60, 0x56, 0xf1, 0x24,
	0x54, 0x1b, 0x56, 0xe7, 0x54, 0x0c, 0xaa, 0xde, 0x0c, 0xde, 0x22, 0x5b, 0x68, 0xc3, 0x09, 0x38,
	0x54, 0x90, 0x58, 0x48, 0xbd, 0x61, 0x47, 0x80, 0xb7, 0x49, 0x1b, 0xbd, 0x75, 0xc2, 0x38, 0xa5,
	0xa4, 0x0e, 0xe8, 0xac, 0xee, 0x41, 0xf4, 0x98, 0x96, 0x22, 0x07, 0x61, 0x71, 0x23, 0x2c, 0xbe,
	0x6d, 0xd8, 0xb7, 0x39, 0x7f, 0xef, 0xbb, 0x40, 0xad, 0xd3, 0x80, 0x9f, 0x90, 0xd7, 0xe8, 0x65,
	0x68, 0x84, 0x89, 0xbb, 0xd9, 0xc2, 0xed, 0x8c, 0xe1, 0x3e, 0x91, 0xb9, 0xe2, 0x8c, 0x0a, 0x8b,
	0x77, 0xc8, 0x33, 0xb4, 0x93, 0x38, 0x63, 0x65, 0xee, 0xe1, 0x90, 0xd9, 0x3b, 0x01, 0x76, 0xe3,
	0x1f, 0x73, 0xa8, 0xf5, 0xa9, 0x38, 0x8f, 0xfe, 0xfd, 0xc2, 0xe3, 0xc6, 0xfd, 0x57, 0xac, 0xc2,
	0xc7, 0x50, 0x73, 0xdf, 0xe7, 0x17, 0x32, 0x4a, 0x7f, 0xce, 0x37, 0xb3, 0xda, 0x4f, 0x47, 0x65,
	0x54, 0x8f, 0x61, 0xea, 0x75, 0xa2, 0x4a, 0x5c, 0xfe, 0x9e, 0x0a, 0x86, 0x74, 0x54, 0x0e, 0x6f,
	0x04, 0xc3, 0x5e, 0x67, 0x58, 0x0b, 0xfe, 0xfc, 0x4f, 0x70, 0xb2, 0x54, 0x7d, 0xc5, 0x77, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x63, 0x35, 0xa7, 0xd0, 0xc5, 0x03, 0x00, 0x00,
}
