// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v0/errors/region_code_error.proto

package google_ads_googleads_v0_errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum describing possible region code errors.
type RegionCodeErrorEnum_RegionCodeError int32

const (
	// Enum unspecified.
	RegionCodeErrorEnum_UNSPECIFIED RegionCodeErrorEnum_RegionCodeError = 0
	// The received error code is not known in this version.
	RegionCodeErrorEnum_UNKNOWN RegionCodeErrorEnum_RegionCodeError = 1
	// Invalid region code.
	RegionCodeErrorEnum_INVALID_REGION_CODE RegionCodeErrorEnum_RegionCodeError = 2
)

var RegionCodeErrorEnum_RegionCodeError_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "UNKNOWN",
	2: "INVALID_REGION_CODE",
}

var RegionCodeErrorEnum_RegionCodeError_value = map[string]int32{
	"UNSPECIFIED":         0,
	"UNKNOWN":             1,
	"INVALID_REGION_CODE": 2,
}

func (x RegionCodeErrorEnum_RegionCodeError) String() string {
	return proto.EnumName(RegionCodeErrorEnum_RegionCodeError_name, int32(x))
}

func (RegionCodeErrorEnum_RegionCodeError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bcbca575d34b6211, []int{0, 0}
}

// Container for enum describing possible region code errors.
type RegionCodeErrorEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegionCodeErrorEnum) Reset()         { *m = RegionCodeErrorEnum{} }
func (m *RegionCodeErrorEnum) String() string { return proto.CompactTextString(m) }
func (*RegionCodeErrorEnum) ProtoMessage()    {}
func (*RegionCodeErrorEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_bcbca575d34b6211, []int{0}
}
func (m *RegionCodeErrorEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionCodeErrorEnum.Unmarshal(m, b)
}
func (m *RegionCodeErrorEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionCodeErrorEnum.Marshal(b, m, deterministic)
}
func (m *RegionCodeErrorEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionCodeErrorEnum.Merge(m, src)
}
func (m *RegionCodeErrorEnum) XXX_Size() int {
	return xxx_messageInfo_RegionCodeErrorEnum.Size(m)
}
func (m *RegionCodeErrorEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionCodeErrorEnum.DiscardUnknown(m)
}

var xxx_messageInfo_RegionCodeErrorEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegionCodeErrorEnum)(nil), "google.ads.googleads.v0.errors.RegionCodeErrorEnum")
	proto.RegisterEnum("google.ads.googleads.v0.errors.RegionCodeErrorEnum_RegionCodeError", RegionCodeErrorEnum_RegionCodeError_name, RegionCodeErrorEnum_RegionCodeError_value)
}

func init() {
	proto.RegisterFile("google/ads/googleads/v0/errors/region_code_error.proto", fileDescriptor_bcbca575d34b6211)
}

var fileDescriptor_bcbca575d34b6211 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4b, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x4f, 0x4c, 0x29, 0xd6, 0x87, 0x30, 0x41, 0xac, 0x32, 0x03, 0xfd, 0xd4, 0xa2,
	0xa2, 0xfc, 0xa2, 0x62, 0xfd, 0xa2, 0xd4, 0xf4, 0xcc, 0xfc, 0xbc, 0xf8, 0xe4, 0xfc, 0x94, 0xd4,
	0x78, 0xb0, 0x90, 0x5e, 0x41, 0x51, 0x7e, 0x49, 0xbe, 0x90, 0x1c, 0x44, 0xb1, 0x5e, 0x62, 0x4a,
	0xb1, 0x1e, 0x5c, 0x9f, 0x5e, 0x99, 0x81, 0x1e, 0x44, 0x9f, 0x52, 0x3c, 0x97, 0x70, 0x10, 0x58,
	0xab, 0x73, 0x7e, 0x4a, 0xaa, 0x2b, 0x48, 0xcc, 0x35, 0xaf, 0x34, 0x57, 0xc9, 0x83, 0x8b, 0x1f,
	0x4d, 0x58, 0x88, 0x9f, 0x8b, 0x3b, 0xd4, 0x2f, 0x38, 0xc0, 0xd5, 0xd9, 0xd3, 0xcd, 0xd3, 0xd5,
	0x45, 0x80, 0x41, 0x88, 0x9b, 0x8b, 0x3d, 0xd4, 0xcf, 0xdb, 0xcf, 0x3f, 0xdc, 0x4f, 0x80, 0x51,
	0x48, 0x9c, 0x4b, 0xd8, 0xd3, 0x2f, 0xcc, 0xd1, 0xc7, 0xd3, 0x25, 0x3e, 0xc8, 0xd5, 0xdd, 0xd3,
	0xdf, 0x2f, 0xde, 0xd9, 0xdf, 0xc5, 0x55, 0x80, 0xc9, 0x69, 0x29, 0x23, 0x97, 0x52, 0x72, 0x7e,
	0xae, 0x1e, 0x7e, 0x77, 0x38, 0x89, 0xa0, 0x59, 0x17, 0x00, 0x72, 0x7d, 0x00, 0xe3, 0x22, 0x26,
	0x66, 0x77, 0x47, 0xc7, 0x55, 0x4c, 0x72, 0xee, 0x10, 0xed, 0x8e, 0x29, 0xc5, 0x7a, 0x10, 0x26,
	0x88, 0x15, 0x66, 0xa0, 0x07, 0x56, 0x5c, 0x7c, 0x0a, 0xa6, 0x20, 0xc6, 0x31, 0xa5, 0x38, 0x06,
	0xae, 0x20, 0x26, 0xcc, 0x20, 0x06, 0xa2, 0xe0, 0x11, 0x21, 0x05, 0x49, 0x6c, 0xe0, 0xf0, 0x32,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x0f, 0xf4, 0xb5, 0x69, 0x01, 0x00, 0x00,
}
