// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/services/campaign_budget_service.proto

package google_ads_googleads_v0_services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	resources "github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/resources"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Request message for [CampaignBudgetService.GetCampaignBudget][].
type GetCampaignBudgetRequest struct {
	// The resource name of the campaign budget to fetch.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCampaignBudgetRequest) Reset()         { *m = GetCampaignBudgetRequest{} }
func (m *GetCampaignBudgetRequest) String() string { return proto.CompactTextString(m) }
func (*GetCampaignBudgetRequest) ProtoMessage()    {}
func (*GetCampaignBudgetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34b8b6a01eeaad93, []int{0}
}
func (m *GetCampaignBudgetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCampaignBudgetRequest.Unmarshal(m, b)
}
func (m *GetCampaignBudgetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCampaignBudgetRequest.Marshal(b, m, deterministic)
}
func (m *GetCampaignBudgetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCampaignBudgetRequest.Merge(m, src)
}
func (m *GetCampaignBudgetRequest) XXX_Size() int {
	return xxx_messageInfo_GetCampaignBudgetRequest.Size(m)
}
func (m *GetCampaignBudgetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCampaignBudgetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCampaignBudgetRequest proto.InternalMessageInfo

func (m *GetCampaignBudgetRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

// Request message for [CampaignBudgetService.MutateCampaignBudgets][].
type MutateCampaignBudgetsRequest struct {
	// The ID of the customer whose campaign budgets are being modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// The list of operations to perform on individual campaign budgets.
	Operations           []*CampaignBudgetOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MutateCampaignBudgetsRequest) Reset()         { *m = MutateCampaignBudgetsRequest{} }
func (m *MutateCampaignBudgetsRequest) String() string { return proto.CompactTextString(m) }
func (*MutateCampaignBudgetsRequest) ProtoMessage()    {}
func (*MutateCampaignBudgetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34b8b6a01eeaad93, []int{1}
}
func (m *MutateCampaignBudgetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateCampaignBudgetsRequest.Unmarshal(m, b)
}
func (m *MutateCampaignBudgetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateCampaignBudgetsRequest.Marshal(b, m, deterministic)
}
func (m *MutateCampaignBudgetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateCampaignBudgetsRequest.Merge(m, src)
}
func (m *MutateCampaignBudgetsRequest) XXX_Size() int {
	return xxx_messageInfo_MutateCampaignBudgetsRequest.Size(m)
}
func (m *MutateCampaignBudgetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateCampaignBudgetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutateCampaignBudgetsRequest proto.InternalMessageInfo

func (m *MutateCampaignBudgetsRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *MutateCampaignBudgetsRequest) GetOperations() []*CampaignBudgetOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

// A single operation (create, update, remove) on a campaign budget.
type CampaignBudgetOperation struct {
	// FieldMask that determines which resource fields are modified in an update.
	UpdateMask *field_mask.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//	*CampaignBudgetOperation_Create
	//	*CampaignBudgetOperation_Update
	//	*CampaignBudgetOperation_Remove
	Operation            isCampaignBudgetOperation_Operation `protobuf_oneof:"operation"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *CampaignBudgetOperation) Reset()         { *m = CampaignBudgetOperation{} }
func (m *CampaignBudgetOperation) String() string { return proto.CompactTextString(m) }
func (*CampaignBudgetOperation) ProtoMessage()    {}
func (*CampaignBudgetOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_34b8b6a01eeaad93, []int{2}
}
func (m *CampaignBudgetOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignBudgetOperation.Unmarshal(m, b)
}
func (m *CampaignBudgetOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignBudgetOperation.Marshal(b, m, deterministic)
}
func (m *CampaignBudgetOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignBudgetOperation.Merge(m, src)
}
func (m *CampaignBudgetOperation) XXX_Size() int {
	return xxx_messageInfo_CampaignBudgetOperation.Size(m)
}
func (m *CampaignBudgetOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignBudgetOperation.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignBudgetOperation proto.InternalMessageInfo

func (m *CampaignBudgetOperation) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type isCampaignBudgetOperation_Operation interface {
	isCampaignBudgetOperation_Operation()
}

type CampaignBudgetOperation_Create struct {
	Create *resources.CampaignBudget `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type CampaignBudgetOperation_Update struct {
	Update *resources.CampaignBudget `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type CampaignBudgetOperation_Remove struct {
	Remove string `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*CampaignBudgetOperation_Create) isCampaignBudgetOperation_Operation() {}

func (*CampaignBudgetOperation_Update) isCampaignBudgetOperation_Operation() {}

func (*CampaignBudgetOperation_Remove) isCampaignBudgetOperation_Operation() {}

func (m *CampaignBudgetOperation) GetOperation() isCampaignBudgetOperation_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *CampaignBudgetOperation) GetCreate() *resources.CampaignBudget {
	if x, ok := m.GetOperation().(*CampaignBudgetOperation_Create); ok {
		return x.Create
	}
	return nil
}

func (m *CampaignBudgetOperation) GetUpdate() *resources.CampaignBudget {
	if x, ok := m.GetOperation().(*CampaignBudgetOperation_Update); ok {
		return x.Update
	}
	return nil
}

func (m *CampaignBudgetOperation) GetRemove() string {
	if x, ok := m.GetOperation().(*CampaignBudgetOperation_Remove); ok {
		return x.Remove
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CampaignBudgetOperation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CampaignBudgetOperation_OneofMarshaler, _CampaignBudgetOperation_OneofUnmarshaler, _CampaignBudgetOperation_OneofSizer, []interface{}{
		(*CampaignBudgetOperation_Create)(nil),
		(*CampaignBudgetOperation_Update)(nil),
		(*CampaignBudgetOperation_Remove)(nil),
	}
}

func _CampaignBudgetOperation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CampaignBudgetOperation)
	// operation
	switch x := m.Operation.(type) {
	case *CampaignBudgetOperation_Create:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Create); err != nil {
			return err
		}
	case *CampaignBudgetOperation_Update:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Update); err != nil {
			return err
		}
	case *CampaignBudgetOperation_Remove:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Remove)
	case nil:
	default:
		return fmt.Errorf("CampaignBudgetOperation.Operation has unexpected type %T", x)
	}
	return nil
}

func _CampaignBudgetOperation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CampaignBudgetOperation)
	switch tag {
	case 1: // operation.create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(resources.CampaignBudget)
		err := b.DecodeMessage(msg)
		m.Operation = &CampaignBudgetOperation_Create{msg}
		return true, err
	case 2: // operation.update
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(resources.CampaignBudget)
		err := b.DecodeMessage(msg)
		m.Operation = &CampaignBudgetOperation_Update{msg}
		return true, err
	case 3: // operation.remove
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Operation = &CampaignBudgetOperation_Remove{x}
		return true, err
	default:
		return false, nil
	}
}

func _CampaignBudgetOperation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CampaignBudgetOperation)
	// operation
	switch x := m.Operation.(type) {
	case *CampaignBudgetOperation_Create:
		s := proto.Size(x.Create)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CampaignBudgetOperation_Update:
		s := proto.Size(x.Update)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *CampaignBudgetOperation_Remove:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Remove)))
		n += len(x.Remove)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Response message for campaign budget mutate.
type MutateCampaignBudgetsResponse struct {
	// All results for the mutate.
	Results              []*MutateCampaignBudgetResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MutateCampaignBudgetsResponse) Reset()         { *m = MutateCampaignBudgetsResponse{} }
func (m *MutateCampaignBudgetsResponse) String() string { return proto.CompactTextString(m) }
func (*MutateCampaignBudgetsResponse) ProtoMessage()    {}
func (*MutateCampaignBudgetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34b8b6a01eeaad93, []int{3}
}
func (m *MutateCampaignBudgetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateCampaignBudgetsResponse.Unmarshal(m, b)
}
func (m *MutateCampaignBudgetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateCampaignBudgetsResponse.Marshal(b, m, deterministic)
}
func (m *MutateCampaignBudgetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateCampaignBudgetsResponse.Merge(m, src)
}
func (m *MutateCampaignBudgetsResponse) XXX_Size() int {
	return xxx_messageInfo_MutateCampaignBudgetsResponse.Size(m)
}
func (m *MutateCampaignBudgetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateCampaignBudgetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MutateCampaignBudgetsResponse proto.InternalMessageInfo

func (m *MutateCampaignBudgetsResponse) GetResults() []*MutateCampaignBudgetResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// The result for the campaign budget mutate.
type MutateCampaignBudgetResult struct {
	// Returned for successful operations.
	ResourceName         string   `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutateCampaignBudgetResult) Reset()         { *m = MutateCampaignBudgetResult{} }
func (m *MutateCampaignBudgetResult) String() string { return proto.CompactTextString(m) }
func (*MutateCampaignBudgetResult) ProtoMessage()    {}
func (*MutateCampaignBudgetResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_34b8b6a01eeaad93, []int{4}
}
func (m *MutateCampaignBudgetResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateCampaignBudgetResult.Unmarshal(m, b)
}
func (m *MutateCampaignBudgetResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateCampaignBudgetResult.Marshal(b, m, deterministic)
}
func (m *MutateCampaignBudgetResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateCampaignBudgetResult.Merge(m, src)
}
func (m *MutateCampaignBudgetResult) XXX_Size() int {
	return xxx_messageInfo_MutateCampaignBudgetResult.Size(m)
}
func (m *MutateCampaignBudgetResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateCampaignBudgetResult.DiscardUnknown(m)
}

var xxx_messageInfo_MutateCampaignBudgetResult proto.InternalMessageInfo

func (m *MutateCampaignBudgetResult) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetCampaignBudgetRequest)(nil), "google.ads.googleads.v0.services.GetCampaignBudgetRequest")
	proto.RegisterType((*MutateCampaignBudgetsRequest)(nil), "google.ads.googleads.v0.services.MutateCampaignBudgetsRequest")
	proto.RegisterType((*CampaignBudgetOperation)(nil), "google.ads.googleads.v0.services.CampaignBudgetOperation")
	proto.RegisterType((*MutateCampaignBudgetsResponse)(nil), "google.ads.googleads.v0.services.MutateCampaignBudgetsResponse")
	proto.RegisterType((*MutateCampaignBudgetResult)(nil), "google.ads.googleads.v0.services.MutateCampaignBudgetResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CampaignBudgetServiceClient is the client API for CampaignBudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CampaignBudgetServiceClient interface {
	// Returns the requested Campaign Budget in full detail.
	GetCampaignBudget(ctx context.Context, in *GetCampaignBudgetRequest, opts ...grpc.CallOption) (*resources.CampaignBudget, error)
	// Creates, updates, or removes campaign budgets. Operation statuses are
	// returned.
	MutateCampaignBudgets(ctx context.Context, in *MutateCampaignBudgetsRequest, opts ...grpc.CallOption) (*MutateCampaignBudgetsResponse, error)
}

type campaignBudgetServiceClient struct {
	cc *grpc.ClientConn
}

func NewCampaignBudgetServiceClient(cc *grpc.ClientConn) CampaignBudgetServiceClient {
	return &campaignBudgetServiceClient{cc}
}

func (c *campaignBudgetServiceClient) GetCampaignBudget(ctx context.Context, in *GetCampaignBudgetRequest, opts ...grpc.CallOption) (*resources.CampaignBudget, error) {
	out := new(resources.CampaignBudget)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v0.services.CampaignBudgetService/GetCampaignBudget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignBudgetServiceClient) MutateCampaignBudgets(ctx context.Context, in *MutateCampaignBudgetsRequest, opts ...grpc.CallOption) (*MutateCampaignBudgetsResponse, error) {
	out := new(MutateCampaignBudgetsResponse)
	err := c.cc.Invoke(ctx, "/google.ads.googleads.v0.services.CampaignBudgetService/MutateCampaignBudgets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignBudgetServiceServer is the server API for CampaignBudgetService service.
type CampaignBudgetServiceServer interface {
	// Returns the requested Campaign Budget in full detail.
	GetCampaignBudget(context.Context, *GetCampaignBudgetRequest) (*resources.CampaignBudget, error)
	// Creates, updates, or removes campaign budgets. Operation statuses are
	// returned.
	MutateCampaignBudgets(context.Context, *MutateCampaignBudgetsRequest) (*MutateCampaignBudgetsResponse, error)
}

func RegisterCampaignBudgetServiceServer(s *grpc.Server, srv CampaignBudgetServiceServer) {
	s.RegisterService(&_CampaignBudgetService_serviceDesc, srv)
}

func _CampaignBudgetService_GetCampaignBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignBudgetServiceServer).GetCampaignBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v0.services.CampaignBudgetService/GetCampaignBudget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignBudgetServiceServer).GetCampaignBudget(ctx, req.(*GetCampaignBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignBudgetService_MutateCampaignBudgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateCampaignBudgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignBudgetServiceServer).MutateCampaignBudgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.ads.googleads.v0.services.CampaignBudgetService/MutateCampaignBudgets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignBudgetServiceServer).MutateCampaignBudgets(ctx, req.(*MutateCampaignBudgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CampaignBudgetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.ads.googleads.v0.services.CampaignBudgetService",
	HandlerType: (*CampaignBudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCampaignBudget",
			Handler:    _CampaignBudgetService_GetCampaignBudget_Handler,
		},
		{
			MethodName: "MutateCampaignBudgets",
			Handler:    _CampaignBudgetService_MutateCampaignBudgets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/services/campaign_budget_service.proto",
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/services/campaign_budget_service.proto", fileDescriptor_34b8b6a01eeaad93)
}

var fileDescriptor_34b8b6a01eeaad93 = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x4d, 0x2a, 0x2b, 0xfb, 0xa2, 0x07, 0x07, 0x16, 0x43, 0x58, 0xb1, 0x44, 0x0f, 0xa5,
	0x87, 0xa4, 0xdb, 0x15, 0xa4, 0xd5, 0xdd, 0xd2, 0x0a, 0x56, 0x91, 0xd5, 0x25, 0x42, 0x41, 0x28,
	0x94, 0x69, 0xf3, 0xb6, 0x84, 0x6d, 0x32, 0x31, 0x33, 0xa9, 0x87, 0x65, 0x2f, 0x7e, 0x05, 0x0f,
	0x82, 0x47, 0x8f, 0x5e, 0xf7, 0xec, 0x17, 0xf0, 0xea, 0xc9, 0xab, 0xf8, 0x41, 0x24, 0x99, 0x4c,
	0xdd, 0xae, 0x0d, 0xd5, 0xf5, 0xf6, 0x32, 0xf3, 0xde, 0xef, 0xbd, 0xf7, 0x7f, 0xf3, 0x02, 0xfb,
	0x53, 0xc6, 0xa6, 0x33, 0x74, 0xa9, 0xcf, 0x5d, 0x69, 0x66, 0xd6, 0xbc, 0xe1, 0x72, 0x4c, 0xe6,
	0xc1, 0x04, 0xb9, 0x3b, 0xa1, 0x61, 0x4c, 0x83, 0x69, 0x34, 0x1a, 0xa7, 0xfe, 0x14, 0xc5, 0xa8,
	0xb8, 0x70, 0xe2, 0x84, 0x09, 0x46, 0xaa, 0x32, 0xc8, 0xa1, 0x3e, 0x77, 0x16, 0xf1, 0xce, 0xbc,
	0xe1, 0xa8, 0x78, 0xeb, 0x41, 0x59, 0x86, 0x04, 0x39, 0x4b, 0x93, 0x15, 0x29, 0x24, 0xda, 0xda,
	0x56, 0x81, 0x71, 0xe0, 0xd2, 0x28, 0x62, 0x82, 0x8a, 0x80, 0x45, 0xbc, 0xb8, 0x2d, 0x12, 0xbb,
	0xf9, 0xd7, 0x38, 0x3d, 0x72, 0x8f, 0x02, 0x9c, 0xf9, 0xa3, 0x90, 0xf2, 0x63, 0xe9, 0x61, 0x77,
	0xc0, 0xec, 0xa3, 0x78, 0x5c, 0xb0, 0x7b, 0x39, 0xda, 0xc3, 0x37, 0x29, 0x72, 0x41, 0xee, 0xc2,
	0x0d, 0x95, 0x7e, 0x14, 0xd1, 0x10, 0x4d, 0xad, 0xaa, 0xd5, 0x36, 0xbd, 0xeb, 0xea, 0xf0, 0x05,
	0x0d, 0xd1, 0xfe, 0xa8, 0xc1, 0xf6, 0x41, 0x2a, 0xa8, 0xc0, 0x65, 0x08, 0x57, 0x94, 0x3b, 0x60,
	0x4c, 0x52, 0x2e, 0x58, 0x88, 0xc9, 0x28, 0xf0, 0x0b, 0x06, 0xa8, 0xa3, 0x67, 0x3e, 0x79, 0x0d,
	0xc0, 0x62, 0x4c, 0x64, 0xe1, 0xa6, 0x5e, 0xad, 0xd4, 0x8c, 0x66, 0xcb, 0x59, 0x27, 0x99, 0xb3,
	0x9c, 0xee, 0xa5, 0x22, 0x78, 0xe7, 0x60, 0xf6, 0x07, 0x1d, 0x6e, 0x95, 0xf8, 0x91, 0x87, 0x60,
	0xa4, 0xb1, 0x4f, 0x05, 0xe6, 0x72, 0x98, 0x57, 0xab, 0x5a, 0xcd, 0x68, 0x5a, 0x2a, 0xaf, 0x52,
	0xcc, 0x79, 0x92, 0x29, 0x76, 0x40, 0xf9, 0xb1, 0x07, 0xd2, 0x3d, 0xb3, 0xc9, 0x73, 0xd8, 0x98,
	0x24, 0x48, 0x85, 0xd4, 0xc4, 0x68, 0xee, 0x94, 0xd6, 0xbb, 0x18, 0xe0, 0x85, 0x82, 0x9f, 0x5e,
	0xf1, 0x0a, 0x44, 0x06, 0x93, 0x68, 0x53, 0xff, 0x0f, 0x98, 0x44, 0x10, 0x13, 0x36, 0x12, 0x0c,
	0xd9, 0x1c, 0xcd, 0x4a, 0xa6, 0x74, 0x76, 0x23, 0xbf, 0x7b, 0x06, 0x6c, 0x2e, 0xa4, 0xb1, 0xdf,
	0xc2, 0xed, 0x92, 0xa9, 0xf1, 0x98, 0x45, 0x1c, 0xc9, 0x00, 0xae, 0x25, 0xc8, 0xd3, 0x99, 0x50,
	0x23, 0x79, 0xb4, 0x7e, 0x24, 0xab, 0x88, 0x5e, 0x0e, 0xf1, 0x14, 0xcc, 0xee, 0x82, 0x55, 0xee,
	0xf6, 0x57, 0x4f, 0xae, 0x79, 0x56, 0x81, 0xad, 0xe5, 0xe8, 0x57, 0xb2, 0x02, 0xf2, 0x45, 0x83,
	0x9b, 0x7f, 0x3c, 0x67, 0xd2, 0x5e, 0x5f, 0x79, 0xd9, 0x0e, 0x58, 0xff, 0x3e, 0x0b, 0xbb, 0xf5,
	0xee, 0xdb, 0xcf, 0xf7, 0xfa, 0x2e, 0xd9, 0xc9, 0xf6, 0xf7, 0x64, 0xa9, 0x9d, 0x3d, 0xf5, 0xec,
	0xb9, 0x5b, 0x5f, 0x2c, 0x74, 0xa1, 0xbc, 0x5b, 0x3f, 0x25, 0xdf, 0x35, 0xd8, 0x5a, 0x39, 0x16,
	0xb2, 0x7f, 0x39, 0xf5, 0xd5, 0x16, 0x5a, 0x9d, 0x4b, 0xc7, 0xcb, 0xf7, 0x60, 0x77, 0xf2, 0xae,
	0x5a, 0xf6, 0xfd, 0xac, 0xab, 0xdf, 0x6d, 0x9c, 0x9c, 0xdb, 0xed, 0xbd, 0xfa, 0xe9, 0xc5, 0xa6,
	0xda, 0x61, 0x0e, 0x6d, 0x6b, 0xf5, 0xde, 0x99, 0x06, 0xf7, 0x26, 0x2c, 0x5c, 0x5b, 0x47, 0xcf,
	0x5a, 0x39, 0xdb, 0xc3, 0x6c, 0x21, 0x0f, 0xb5, 0x4f, 0x7a, 0xa5, 0xdf, 0xed, 0x7e, 0xd6, 0xab,
	0x7d, 0x89, 0xe9, 0xfa, 0xdc, 0x91, 0x66, 0x66, 0x0d, 0x1a, 0x4e, 0xe1, 0xce, 0xbf, 0x2a, 0x97,
	0x61, 0xd7, 0xe7, 0xc3, 0x85, 0xcb, 0x70, 0xd0, 0x18, 0x2a, 0x97, 0x1f, 0xeb, 0x5d, 0xc6, 0x1b,
	0xf9, 0x8f, 0x60, 0xf7, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xdc, 0x49, 0x5a, 0x03, 0x06,
	0x00, 0x00,
}
