// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/errors/setting_error.proto

package errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enum describing possible setting errors.
type SettingErrorEnum_SettingError int32

const (
	// Enum unspecified.
	SettingErrorEnum_UNSPECIFIED SettingErrorEnum_SettingError = 0
	// The received error code is not known in this version.
	SettingErrorEnum_UNKNOWN SettingErrorEnum_SettingError = 1
	// The campaign setting is not available for this AdWords account.
	SettingErrorEnum_SETTING_TYPE_IS_NOT_AVAILABLE SettingErrorEnum_SettingError = 3
	// The setting is not compatible with the campaign.
	SettingErrorEnum_SETTING_TYPE_IS_NOT_COMPATIBLE_WITH_CAMPAIGN SettingErrorEnum_SettingError = 4
	// The supplied TargetingSetting contains an invalid CriterionTypeGroup. See
	// CriterionTypeGroup documentation for CriterionTypeGroups allowed
	// in Campaign or AdGroup TargetingSettings.
	SettingErrorEnum_TARGETING_SETTING_CONTAINS_INVALID_CRITERION_TYPE_GROUP SettingErrorEnum_SettingError = 5
	// TargetingSetting must not explicitly
	// set any of the Demographic CriterionTypeGroups (AGE_RANGE, GENDER,
	// PARENT, INCOME_RANGE) to false (it's okay to not set them at all, in
	// which case the system will set them to true automatically).
	SettingErrorEnum_TARGETING_SETTING_DEMOGRAPHIC_CRITERION_TYPE_GROUPS_MUST_BE_SET_TO_TARGET_ALL SettingErrorEnum_SettingError = 6
	// TargetingSetting cannot change any of
	// the Demographic CriterionTypeGroups (AGE_RANGE, GENDER, PARENT,
	// INCOME_RANGE) from true to false.
	SettingErrorEnum_TARGETING_SETTING_CANNOT_CHANGE_TARGET_ALL_TO_FALSE_FOR_DEMOGRAPHIC_CRITERION_TYPE_GROUP SettingErrorEnum_SettingError = 7
	// At least one feed id should be present.
	SettingErrorEnum_DYNAMIC_SEARCH_ADS_SETTING_AT_LEAST_ONE_FEED_ID_MUST_BE_PRESENT SettingErrorEnum_SettingError = 8
	// The supplied DynamicSearchAdsSetting contains an invalid domain name.
	SettingErrorEnum_DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_DOMAIN_NAME SettingErrorEnum_SettingError = 9
	// The supplied DynamicSearchAdsSetting contains a subdomain name.
	SettingErrorEnum_DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_SUBDOMAIN_NAME SettingErrorEnum_SettingError = 10
	// The supplied DynamicSearchAdsSetting contains an invalid language code.
	SettingErrorEnum_DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_LANGUAGE_CODE SettingErrorEnum_SettingError = 11
	// TargetingSettings in search campaigns should not have
	// CriterionTypeGroup.PLACEMENT set to targetAll.
	SettingErrorEnum_TARGET_ALL_IS_NOT_ALLOWED_FOR_PLACEMENT_IN_SEARCH_CAMPAIGN SettingErrorEnum_SettingError = 12
	// Duplicate description in universal app setting description field.
	SettingErrorEnum_UNIVERSAL_APP_CAMPAIGN_SETTING_DUPLICATE_DESCRIPTION SettingErrorEnum_SettingError = 13
	// Description line width is too long in universal app setting description
	// field.
	SettingErrorEnum_UNIVERSAL_APP_CAMPAIGN_SETTING_DESCRIPTION_LINE_WIDTH_TOO_LONG SettingErrorEnum_SettingError = 14
	// Universal app setting appId field cannot be modified for COMPLETE
	// campaigns.
	SettingErrorEnum_UNIVERSAL_APP_CAMPAIGN_SETTING_APP_ID_CANNOT_BE_MODIFIED SettingErrorEnum_SettingError = 15
	// YoutubeVideoMediaIds in universal app setting cannot exceed size limit.
	SettingErrorEnum_TOO_MANY_YOUTUBE_MEDIA_IDS_IN_UNIVERSAL_APP_CAMPAIGN SettingErrorEnum_SettingError = 16
	// ImageMediaIds in universal app setting cannot exceed size limit.
	SettingErrorEnum_TOO_MANY_IMAGE_MEDIA_IDS_IN_UNIVERSAL_APP_CAMPAIGN SettingErrorEnum_SettingError = 17
	// Media is incompatible for universal app campaign.
	SettingErrorEnum_MEDIA_INCOMPATIBLE_FOR_UNIVERSAL_APP_CAMPAIGN SettingErrorEnum_SettingError = 18
	// Too many exclamation marks in universal app campaign ad text ideas.
	SettingErrorEnum_TOO_MANY_EXCLAMATION_MARKS SettingErrorEnum_SettingError = 19
)

var SettingErrorEnum_SettingError_name = map[int32]string{
	0:  "UNSPECIFIED",
	1:  "UNKNOWN",
	3:  "SETTING_TYPE_IS_NOT_AVAILABLE",
	4:  "SETTING_TYPE_IS_NOT_COMPATIBLE_WITH_CAMPAIGN",
	5:  "TARGETING_SETTING_CONTAINS_INVALID_CRITERION_TYPE_GROUP",
	6:  "TARGETING_SETTING_DEMOGRAPHIC_CRITERION_TYPE_GROUPS_MUST_BE_SET_TO_TARGET_ALL",
	7:  "TARGETING_SETTING_CANNOT_CHANGE_TARGET_ALL_TO_FALSE_FOR_DEMOGRAPHIC_CRITERION_TYPE_GROUP",
	8:  "DYNAMIC_SEARCH_ADS_SETTING_AT_LEAST_ONE_FEED_ID_MUST_BE_PRESENT",
	9:  "DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_DOMAIN_NAME",
	10: "DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_SUBDOMAIN_NAME",
	11: "DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_LANGUAGE_CODE",
	12: "TARGET_ALL_IS_NOT_ALLOWED_FOR_PLACEMENT_IN_SEARCH_CAMPAIGN",
	13: "UNIVERSAL_APP_CAMPAIGN_SETTING_DUPLICATE_DESCRIPTION",
	14: "UNIVERSAL_APP_CAMPAIGN_SETTING_DESCRIPTION_LINE_WIDTH_TOO_LONG",
	15: "UNIVERSAL_APP_CAMPAIGN_SETTING_APP_ID_CANNOT_BE_MODIFIED",
	16: "TOO_MANY_YOUTUBE_MEDIA_IDS_IN_UNIVERSAL_APP_CAMPAIGN",
	17: "TOO_MANY_IMAGE_MEDIA_IDS_IN_UNIVERSAL_APP_CAMPAIGN",
	18: "MEDIA_INCOMPATIBLE_FOR_UNIVERSAL_APP_CAMPAIGN",
	19: "TOO_MANY_EXCLAMATION_MARKS",
}

var SettingErrorEnum_SettingError_value = map[string]int32{
	"UNSPECIFIED":                   0,
	"UNKNOWN":                       1,
	"SETTING_TYPE_IS_NOT_AVAILABLE": 3,
	"SETTING_TYPE_IS_NOT_COMPATIBLE_WITH_CAMPAIGN":                                             4,
	"TARGETING_SETTING_CONTAINS_INVALID_CRITERION_TYPE_GROUP":                                  5,
	"TARGETING_SETTING_DEMOGRAPHIC_CRITERION_TYPE_GROUPS_MUST_BE_SET_TO_TARGET_ALL":            6,
	"TARGETING_SETTING_CANNOT_CHANGE_TARGET_ALL_TO_FALSE_FOR_DEMOGRAPHIC_CRITERION_TYPE_GROUP": 7,
	"DYNAMIC_SEARCH_ADS_SETTING_AT_LEAST_ONE_FEED_ID_MUST_BE_PRESENT":                          8,
	"DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_DOMAIN_NAME":                                  9,
	"DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_SUBDOMAIN_NAME":                                       10,
	"DYNAMIC_SEARCH_ADS_SETTING_CONTAINS_INVALID_LANGUAGE_CODE":                                11,
	"TARGET_ALL_IS_NOT_ALLOWED_FOR_PLACEMENT_IN_SEARCH_CAMPAIGN":                               12,
	"UNIVERSAL_APP_CAMPAIGN_SETTING_DUPLICATE_DESCRIPTION":                                     13,
	"UNIVERSAL_APP_CAMPAIGN_SETTING_DESCRIPTION_LINE_WIDTH_TOO_LONG":                           14,
	"UNIVERSAL_APP_CAMPAIGN_SETTING_APP_ID_CANNOT_BE_MODIFIED":                                 15,
	"TOO_MANY_YOUTUBE_MEDIA_IDS_IN_UNIVERSAL_APP_CAMPAIGN":                                     16,
	"TOO_MANY_IMAGE_MEDIA_IDS_IN_UNIVERSAL_APP_CAMPAIGN":                                       17,
	"MEDIA_INCOMPATIBLE_FOR_UNIVERSAL_APP_CAMPAIGN":                                            18,
	"TOO_MANY_EXCLAMATION_MARKS":                                                               19,
}

func (x SettingErrorEnum_SettingError) String() string {
	return proto.EnumName(SettingErrorEnum_SettingError_name, int32(x))
}

func (SettingErrorEnum_SettingError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6d3509e491f49471, []int{0, 0}
}

// Container for enum describing possible setting errors.
type SettingErrorEnum struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettingErrorEnum) Reset()         { *m = SettingErrorEnum{} }
func (m *SettingErrorEnum) String() string { return proto.CompactTextString(m) }
func (*SettingErrorEnum) ProtoMessage()    {}
func (*SettingErrorEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d3509e491f49471, []int{0}
}
func (m *SettingErrorEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingErrorEnum.Unmarshal(m, b)
}
func (m *SettingErrorEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingErrorEnum.Marshal(b, m, deterministic)
}
func (m *SettingErrorEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingErrorEnum.Merge(m, src)
}
func (m *SettingErrorEnum) XXX_Size() int {
	return xxx_messageInfo_SettingErrorEnum.Size(m)
}
func (m *SettingErrorEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingErrorEnum.DiscardUnknown(m)
}

var xxx_messageInfo_SettingErrorEnum proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SettingErrorEnum)(nil), "google.ads.googleads.v0.errors.SettingErrorEnum")
	proto.RegisterEnum("google.ads.googleads.v0.errors.SettingErrorEnum_SettingError", SettingErrorEnum_SettingError_name, SettingErrorEnum_SettingError_value)
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/errors/setting_error.proto", fileDescriptor_6d3509e491f49471)
}

var fileDescriptor_6d3509e491f49471 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x4e, 0x1b, 0x3b,
	0x10, 0xc6, 0x0f, 0x70, 0x0e, 0x70, 0x0c, 0xe7, 0x60, 0xdc, 0xbb, 0x4a, 0x45, 0x2a, 0xd7, 0xed,
	0x26, 0xa5, 0x55, 0x4b, 0xff, 0x51, 0xcd, 0xae, 0x27, 0x1b, 0x0b, 0xaf, 0xbd, 0x5d, 0x7b, 0x03,
	0x91, 0x22, 0x8d, 0x68, 0x83, 0x50, 0xa5, 0x42, 0xaa, 0x84, 0xf2, 0x40, 0xdc, 0xb5, 0x0f, 0xd1,
	0x07, 0xe8, 0x63, 0xf4, 0x49, 0x2a, 0x67, 0x9b, 0x25, 0x12, 0x29, 0xa1, 0x77, 0xb3, 0xf6, 0xf7,
	0x9b, 0xf1, 0x7e, 0x1e, 0x0f, 0xdb, 0x39, 0x19, 0x0c, 0x4e, 0x3e, 0x1e, 0x37, 0x8e, 0xfa, 0xa3,
	0x46, 0x15, 0x86, 0xe8, 0xa2, 0xd9, 0x38, 0x1e, 0x0e, 0x07, 0xc3, 0x51, 0x63, 0x74, 0x7c, 0x7e,
	0xfe, 0xe1, 0xec, 0x84, 0xc6, 0x9f, 0xd1, 0xa7, 0xe1, 0xe0, 0x7c, 0x20, 0xb6, 0x2a, 0x61, 0x74,
	0xd4, 0x1f, 0x45, 0x35, 0x13, 0x5d, 0x34, 0xa3, 0x8a, 0xd9, 0xfe, 0xb6, 0xca, 0xb8, 0xab, 0x38,
	0x0c, 0x2b, 0x78, 0xf6, 0xf9, 0x74, 0xfb, 0xcb, 0x2a, 0x5b, 0x9f, 0x5e, 0x14, 0x1b, 0x6c, 0xad,
	0x34, 0x2e, 0xc7, 0x44, 0xb5, 0x14, 0x4a, 0xfe, 0x97, 0x58, 0x63, 0x2b, 0xa5, 0xd9, 0x37, 0xf6,
	0xc0, 0xf0, 0x05, 0x71, 0x9f, 0xdd, 0x73, 0xe8, 0xbd, 0x32, 0x29, 0xf9, 0x6e, 0x8e, 0xa4, 0x1c,
	0x19, 0xeb, 0x09, 0x3a, 0xa0, 0x34, 0xc4, 0x1a, 0xf9, 0x92, 0x68, 0xb2, 0x07, 0xb3, 0x24, 0x89,
	0xcd, 0x72, 0xf0, 0x2a, 0xd6, 0x48, 0x07, 0xca, 0xb7, 0x29, 0x81, 0x2c, 0x07, 0x95, 0x1a, 0xfe,
	0xb7, 0x78, 0xc9, 0x9e, 0x79, 0x28, 0x52, 0x1c, 0x33, 0x13, 0x36, 0xb1, 0xc6, 0x83, 0x32, 0x8e,
	0x94, 0xe9, 0x80, 0x56, 0x92, 0x92, 0x42, 0x79, 0x2c, 0x94, 0x35, 0x55, 0xda, 0xb4, 0xb0, 0x65,
	0xce, 0xff, 0x11, 0x6f, 0x59, 0x76, 0x1d, 0x96, 0x98, 0xd9, 0xb4, 0x80, 0xbc, 0xad, 0x92, 0x99,
	0x9c, 0xa3, 0xac, 0x74, 0x9e, 0x62, 0x0c, 0x04, 0x79, 0x4b, 0x55, 0x0a, 0x02, 0xad, 0xf9, 0xb2,
	0xe8, 0xb1, 0xc3, 0x19, 0xe7, 0x01, 0x33, 0xfe, 0x8d, 0x36, 0x98, 0x14, 0xa7, 0xf4, 0x81, 0x6e,
	0x81, 0x76, 0x48, 0x2d, 0x5b, 0xcc, 0x2d, 0xcc, 0x57, 0x44, 0xc2, 0xde, 0xc8, 0xae, 0x81, 0x4c,
	0x25, 0xe4, 0x10, 0x8a, 0xa4, 0x4d, 0x20, 0x5d, 0x5d, 0x06, 0x3c, 0x69, 0x04, 0xe7, 0xc9, 0x1a,
	0xa4, 0x16, 0xa2, 0x24, 0x25, 0xeb, 0xc3, 0xe6, 0x05, 0x3a, 0x34, 0x9e, 0xaf, 0x06, 0xcb, 0x6e,
	0x48, 0x72, 0xcd, 0x3b, 0x69, 0x33, 0x50, 0x86, 0x0c, 0x64, 0xc8, 0xff, 0x15, 0x4f, 0xd9, 0xce,
	0x6d, 0x60, 0x57, 0xc6, 0xd3, 0x1c, 0x13, 0xaf, 0xd9, 0xf3, 0x3f, 0x29, 0xaa, 0xc1, 0xa4, 0x25,
	0xa4, 0x48, 0x89, 0x95, 0xc8, 0xd7, 0xc4, 0x1e, 0x7b, 0x31, 0x65, 0xdb, 0xa4, 0x73, 0xb4, 0xb6,
	0x07, 0x28, 0xc7, 0xe6, 0xe5, 0x1a, 0x12, 0xcc, 0xd0, 0x78, 0x52, 0x66, 0x52, 0xa1, 0x6e, 0x93,
	0x75, 0xb1, 0xcb, 0x9e, 0x94, 0x46, 0x75, 0xb0, 0x70, 0xa0, 0x09, 0xf2, 0xbc, 0xde, 0xbb, 0xba,
	0xf6, 0x32, 0xd7, 0x2a, 0x01, 0x8f, 0x24, 0xd1, 0x25, 0x85, 0xca, 0xbd, 0xb2, 0x86, 0xff, 0x27,
	0x62, 0xb6, 0x37, 0x8f, 0xbc, 0xd2, 0x93, 0x56, 0x26, 0xf4, 0xa8, 0xf4, 0x6d, 0xf2, 0xd6, 0x92,
	0xb6, 0x26, 0xe5, 0xff, 0x8b, 0x57, 0x6c, 0x77, 0x4e, 0x8e, 0xb0, 0x18, 0xfa, 0xb4, 0x6a, 0x94,
	0x18, 0x29, 0xb3, 0xb2, 0x7a, 0x44, 0x1b, 0xe1, 0xec, 0x21, 0x57, 0x06, 0xa6, 0x4b, 0x5d, 0x5b,
	0xfa, 0x32, 0x6c, 0xa3, 0x54, 0x40, 0x4a, 0x06, 0xc7, 0x68, 0x76, 0x6e, 0xce, 0xc3, 0x65, 0xd5,
	0xa4, 0xca, 0x82, 0x9d, 0xb7, 0xe1, 0x36, 0xc5, 0x23, 0xf6, 0xf0, 0x97, 0xd0, 0x4c, 0x3d, 0xbd,
	0x60, 0xf3, 0x6f, 0x10, 0x21, 0xb6, 0xd8, 0xdd, 0xba, 0x14, 0x1e, 0x26, 0x1a, 0x32, 0x18, 0x1b,
	0x92, 0x41, 0xb1, 0xef, 0xf8, 0x9d, 0xf8, 0x72, 0x81, 0x6d, 0xbf, 0x1f, 0x9c, 0x46, 0x37, 0xcf,
	0x99, 0x78, 0x73, 0x7a, 0x9e, 0xe4, 0x61, 0x34, 0xe5, 0x0b, 0x97, 0x8b, 0x4b, 0x29, 0xc0, 0xd7,
	0xc5, 0xad, 0xb4, 0x62, 0xa1, 0x3f, 0x8a, 0xaa, 0x30, 0x44, 0x9d, 0x66, 0x34, 0x16, 0x8f, 0xbe,
	0x4f, 0x04, 0x3d, 0xe8, 0x8f, 0x7a, 0xb5, 0xa0, 0xd7, 0x69, 0xf6, 0x2a, 0xc1, 0x8f, 0x79, 0x82,
	0x77, 0xcb, 0xe3, 0x61, 0xf8, 0xf8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xf6, 0x39, 0x32,
	0x42, 0x05, 0x00, 0x00,
}
