// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/resources/google_ads_field.proto

package google_ads_googleads_v0_resources

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	enums "github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/enums"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A field or resource (artifact) used by GoogleAdsService.
type GoogleAdsField struct {
	// The resource name of the artifact.
	// Artifact resource names have the form:
	//
	// `googleAdsFields/{name}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// The name of the artifact.
	Name *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The category of the artifact.
	Category enums.GoogleAdsFieldCategoryEnum_GoogleAdsFieldCategory `protobuf:"varint,3,opt,name=category,proto3,enum=google.ads.googleads.v0.enums.GoogleAdsFieldCategoryEnum_GoogleAdsFieldCategory" json:"category,omitempty"`
	// Whether the artifact can be used in a SELECT clause in search
	// queries.
	Selectable *wrappers.BoolValue `protobuf:"bytes,4,opt,name=selectable,proto3" json:"selectable,omitempty"`
	// Whether the artifact can be used in a WHERE clause in search
	// queries.
	Filterable *wrappers.BoolValue `protobuf:"bytes,5,opt,name=filterable,proto3" json:"filterable,omitempty"`
	// Whether the artifact can be used in a ORDER BY clause in search
	// queries.
	Sortable *wrappers.BoolValue `protobuf:"bytes,6,opt,name=sortable,proto3" json:"sortable,omitempty"`
	// The names of all resources, segments, and metrics that are selectable with
	// the described artifact.
	SelectableWith []*wrappers.StringValue `protobuf:"bytes,7,rep,name=selectable_with,json=selectableWith,proto3" json:"selectable_with,omitempty"`
	// The names of all resources that are selectable with the described
	// artifact. Fields from these resources do not segment metrics when included
	// in search queries.
	//
	// This field is only set for artifacts whose category is RESOURCE.
	AttributeResources []*wrappers.StringValue `protobuf:"bytes,8,rep,name=attribute_resources,json=attributeResources,proto3" json:"attribute_resources,omitempty"`
	// The names of all metrics that are selectable with the described artifact.
	//
	// This field is only set for artifacts whose category is either RESOURCE or
	// SEGMENT.
	Metrics []*wrappers.StringValue `protobuf:"bytes,9,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// The names of all artifacts, whether a segment or another resource, that
	// segment metrics when included in search queries.
	//
	// This field is only set for artifacts of category RESOURCE, SEGMENT or
	// METRIC.
	Segments []*wrappers.StringValue `protobuf:"bytes,10,rep,name=segments,proto3" json:"segments,omitempty"`
	// Values the artifact can assume if it is a field of type ENUM.
	//
	// This field is only set for artifacts of category SEGMENT or ATTRIBUTE.
	EnumValues []*wrappers.StringValue `protobuf:"bytes,11,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	// This field determines the operators that can be used with the artifact
	// in WHERE clauses.
	DataType enums.GoogleAdsFieldDataTypeEnum_GoogleAdsFieldDataType `protobuf:"varint,12,opt,name=data_type,json=dataType,proto3,enum=google.ads.googleads.v0.enums.GoogleAdsFieldDataTypeEnum_GoogleAdsFieldDataType" json:"data_type,omitempty"`
	// The URL of proto describing the artifact's data type.
	TypeUrl *wrappers.StringValue `protobuf:"bytes,13,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// Whether the field artifact is repeated.
	IsRepeated           *wrappers.BoolValue `protobuf:"bytes,14,opt,name=is_repeated,json=isRepeated,proto3" json:"is_repeated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GoogleAdsField) Reset()         { *m = GoogleAdsField{} }
func (m *GoogleAdsField) String() string { return proto.CompactTextString(m) }
func (*GoogleAdsField) ProtoMessage()    {}
func (*GoogleAdsField) Descriptor() ([]byte, []int) {
	return fileDescriptor_80f6b4594efeb0d1, []int{0}
}
func (m *GoogleAdsField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleAdsField.Unmarshal(m, b)
}
func (m *GoogleAdsField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleAdsField.Marshal(b, m, deterministic)
}
func (m *GoogleAdsField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleAdsField.Merge(m, src)
}
func (m *GoogleAdsField) XXX_Size() int {
	return xxx_messageInfo_GoogleAdsField.Size(m)
}
func (m *GoogleAdsField) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleAdsField.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleAdsField proto.InternalMessageInfo

func (m *GoogleAdsField) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *GoogleAdsField) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GoogleAdsField) GetCategory() enums.GoogleAdsFieldCategoryEnum_GoogleAdsFieldCategory {
	if m != nil {
		return m.Category
	}
	return enums.GoogleAdsFieldCategoryEnum_UNSPECIFIED
}

func (m *GoogleAdsField) GetSelectable() *wrappers.BoolValue {
	if m != nil {
		return m.Selectable
	}
	return nil
}

func (m *GoogleAdsField) GetFilterable() *wrappers.BoolValue {
	if m != nil {
		return m.Filterable
	}
	return nil
}

func (m *GoogleAdsField) GetSortable() *wrappers.BoolValue {
	if m != nil {
		return m.Sortable
	}
	return nil
}

func (m *GoogleAdsField) GetSelectableWith() []*wrappers.StringValue {
	if m != nil {
		return m.SelectableWith
	}
	return nil
}

func (m *GoogleAdsField) GetAttributeResources() []*wrappers.StringValue {
	if m != nil {
		return m.AttributeResources
	}
	return nil
}

func (m *GoogleAdsField) GetMetrics() []*wrappers.StringValue {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *GoogleAdsField) GetSegments() []*wrappers.StringValue {
	if m != nil {
		return m.Segments
	}
	return nil
}

func (m *GoogleAdsField) GetEnumValues() []*wrappers.StringValue {
	if m != nil {
		return m.EnumValues
	}
	return nil
}

func (m *GoogleAdsField) GetDataType() enums.GoogleAdsFieldDataTypeEnum_GoogleAdsFieldDataType {
	if m != nil {
		return m.DataType
	}
	return enums.GoogleAdsFieldDataTypeEnum_UNSPECIFIED
}

func (m *GoogleAdsField) GetTypeUrl() *wrappers.StringValue {
	if m != nil {
		return m.TypeUrl
	}
	return nil
}

func (m *GoogleAdsField) GetIsRepeated() *wrappers.BoolValue {
	if m != nil {
		return m.IsRepeated
	}
	return nil
}

func init() {
	proto.RegisterType((*GoogleAdsField)(nil), "google.ads.googleads.v0.resources.GoogleAdsField")
}

func init() {
	proto.RegisterFile("github.com/kritzware/google-ads-go/protos/google/ads/googleads/v0/resources/google_ads_field.proto", fileDescriptor_80f6b4594efeb0d1)
}

var fileDescriptor_80f6b4594efeb0d1 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x6a, 0x13, 0x4f,
	0x14, 0xc7, 0xd9, 0xa4, 0xbf, 0x66, 0x33, 0x69, 0xf3, 0x83, 0xe9, 0xcd, 0x10, 0x44, 0x52, 0x45,
	0xc8, 0xd5, 0x24, 0x54, 0xa8, 0x45, 0xa9, 0x90, 0x68, 0xed, 0x95, 0x12, 0x56, 0x8d, 0x37, 0x81,
	0x61, 0x92, 0x39, 0x49, 0x17, 0x66, 0x33, 0xcb, 0xcc, 0x6c, 0x4a, 0x5e, 0xc7, 0x4b, 0xaf, 0xf4,
	0x35, 0x7c, 0x0c, 0x9f, 0x44, 0xf6, 0xdf, 0xa4, 0xa5, 0x86, 0xac, 0xde, 0x9d, 0x9c, 0xf3, 0xfd,
	0x9c, 0x7f, 0x39, 0xb3, 0xe8, 0x62, 0xa9, 0xd4, 0x52, 0x42, 0x9f, 0x0b, 0xd3, 0xcf, 0xcd, 0xd4,
	0x5a, 0x0f, 0xfa, 0x1a, 0x8c, 0x4a, 0xf4, 0x1c, 0x4a, 0x37, 0xe3, 0xc2, 0xb0, 0x45, 0x08, 0x52,
	0xd0, 0x58, 0x2b, 0xab, 0xf0, 0x69, 0xee, 0xa7, 0x5c, 0x18, 0xea, 0x48, 0xba, 0x1e, 0x50, 0x47,
	0x76, 0x2e, 0x77, 0x25, 0x87, 0x55, 0x12, 0x3d, 0x4c, 0xcc, 0xe6, 0xdc, 0xc2, 0x52, 0xe9, 0x4d,
	0x5e, 0xa1, 0xf3, 0xfa, 0x2f, 0x71, 0xc1, 0x2d, 0x67, 0x76, 0x13, 0x43, 0xc1, 0x3f, 0x2e, 0xf8,
	0xec, 0xd7, 0x2c, 0x59, 0xf4, 0x6f, 0x35, 0x8f, 0x63, 0xd0, 0x26, 0x8f, 0x3f, 0xf9, 0xd1, 0x40,
	0xed, 0xeb, 0x4c, 0x32, 0x14, 0xe6, 0x5d, 0x9a, 0x02, 0x3f, 0x45, 0xc7, 0x65, 0xfb, 0x6c, 0xc5,
	0x23, 0x20, 0x5e, 0xd7, 0xeb, 0x35, 0x83, 0xa3, 0xd2, 0xf9, 0x81, 0x47, 0x80, 0x07, 0xe8, 0x20,
	0x8b, 0xd5, 0xba, 0x5e, 0xaf, 0x75, 0xf6, 0xa8, 0x98, 0x9e, 0x96, 0x65, 0xe8, 0x47, 0xab, 0xc3,
	0xd5, 0x72, 0xc2, 0x65, 0x02, 0x41, 0xa6, 0xc4, 0x12, 0xf9, 0xe5, 0x6c, 0xa4, 0xde, 0xf5, 0x7a,
	0xed, 0xb3, 0x31, 0xdd, 0xb5, 0xbe, 0x6c, 0x38, 0x7a, 0xbf, 0xaf, 0x37, 0x05, 0x7c, 0xb5, 0x4a,
	0xa2, 0x1d, 0xa1, 0xc0, 0x55, 0xc0, 0x2f, 0x11, 0x32, 0x20, 0x61, 0x6e, 0xf9, 0x4c, 0x02, 0x39,
	0xc8, 0xba, 0xec, 0x3c, 0xe8, 0x72, 0xa4, 0x94, 0xcc, 0x7b, 0xbc, 0xa3, 0x4e, 0xd9, 0x45, 0x28,
	0x2d, 0xe8, 0x8c, 0xfd, 0x6f, 0x3f, 0xbb, 0x55, 0xe3, 0x73, 0xe4, 0x1b, 0xa5, 0xf3, 0xaa, 0x87,
	0x7b, 0x49, 0xa7, 0xc5, 0x57, 0xe8, 0xff, 0x6d, 0x07, 0xec, 0x36, 0xb4, 0x37, 0xa4, 0xd1, 0xad,
	0xef, 0x5d, 0x6d, 0x7b, 0x0b, 0x7d, 0x09, 0xed, 0x0d, 0x7e, 0x8f, 0x4e, 0xb8, 0xb5, 0x3a, 0x9c,
	0x25, 0x16, 0x98, 0x3b, 0x42, 0xe2, 0x57, 0x48, 0x85, 0x1d, 0x18, 0x94, 0x1c, 0x3e, 0x47, 0x8d,
	0x08, 0xac, 0x0e, 0xe7, 0x86, 0x34, 0x2b, 0xa4, 0x28, 0xc5, 0xf8, 0x02, 0xf9, 0x06, 0x96, 0x11,
	0xac, 0xac, 0x21, 0xa8, 0x02, 0xe8, 0xd4, 0xf8, 0x12, 0xb5, 0xd2, 0x3f, 0x9f, 0xad, 0x53, 0xbf,
	0x21, 0xad, 0x0a, 0x30, 0x4a, 0x81, 0xcc, 0x34, 0x38, 0x42, 0x4d, 0xf7, 0x02, 0xc8, 0xd1, 0x3f,
	0x5c, 0xd9, 0x5b, 0x6e, 0xf9, 0xa7, 0x4d, 0x0c, 0x7f, 0xb8, 0xb2, 0x32, 0x14, 0xf8, 0xa2, 0xb0,
	0xf0, 0x0b, 0xe4, 0xa7, 0x95, 0x58, 0xa2, 0x25, 0x39, 0xae, 0xf0, 0x12, 0x1a, 0xa9, 0xfa, 0xb3,
	0x96, 0xf8, 0x15, 0x6a, 0x85, 0x86, 0x69, 0x88, 0x81, 0x5b, 0x10, 0xa4, 0xbd, 0xff, 0xc6, 0x42,
	0x13, 0x14, 0xea, 0xd1, 0x77, 0x0f, 0x3d, 0x9b, 0xab, 0x88, 0xee, 0xfd, 0xf8, 0x8c, 0x4e, 0xee,
	0x4f, 0x30, 0x4e, 0xf3, 0x8e, 0xbd, 0xaf, 0xb5, 0xfa, 0xf5, 0x70, 0xf8, 0xad, 0x76, 0x9a, 0x47,
	0xe9, 0x50, 0xdc, 0xd9, 0x02, 0x9d, 0x0c, 0xa8, 0x3b, 0x80, 0x9f, 0xa5, 0x66, 0x3a, 0x14, 0x66,
	0xea, 0x34, 0xd3, 0xc9, 0x60, 0xea, 0x34, 0xbf, 0x2a, 0x68, 0x66, 0x87, 0xd9, 0x48, 0xcf, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x0d, 0xd8, 0xe0, 0x6b, 0x05, 0x00, 0x00,
}
