// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/ads/googleads/v0/resources/recommendation.proto

package google_ads_googleads_v0_resources

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "google/ads/googleads/v0/common"
	enums "google/ads/googleads/v0/enums"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A recommendation.
type Recommendation struct {
	// The resource name of the recommendation.
	//
	// `customers/{customer_id}/recommendations/{recommendation_id}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// The type of recommendation.
	Type enums.RecommendationTypeEnum_RecommendationType `protobuf:"varint,2,opt,name=type,proto3,enum=google.ads.googleads.v0.enums.RecommendationTypeEnum_RecommendationType" json:"type,omitempty"`
	// The impact on account performance as a result of applying the
	// recommendation.
	Impact *Recommendation_RecommendationImpact `protobuf:"bytes,3,opt,name=impact,proto3" json:"impact,omitempty"`
	// The budget targeted by this recommendation. This will be set only when
	// the recommendation affects a single campaign budget.
	//
	// This field must not be used in WHERE clauses.
	//
	// This field will be set for the following recommendation types:
	// CAMPAIGN_BUDGET
	CampaignBudget *wrappers.StringValue `protobuf:"bytes,5,opt,name=campaign_budget,json=campaignBudget,proto3" json:"campaign_budget,omitempty"`
	// The campaign targeted by this recommendation. This will be set only when
	// the recommendation affects a single campaign.
	//
	// This field must not be used in WHERE clauses.
	//
	// This field will be set for the following recommendation types:
	// KEYWORD, TEXT_AD, TARGET_CPA_OPT_IN
	Campaign *wrappers.StringValue `protobuf:"bytes,6,opt,name=campaign,proto3" json:"campaign,omitempty"`
	// The ad group targeted by this recommendation. This will be set only when
	// the recommendation affects a single ad group.
	//
	// This field must not be used in WHERE clauses.
	//
	// This field will be set for the following recommendation types:
	// KEYWORD, TEXT_AD
	AdGroup *wrappers.StringValue `protobuf:"bytes,7,opt,name=ad_group,json=adGroup,proto3" json:"ad_group,omitempty"`
	// The details of recommendation.
	//
	// Types that are valid to be assigned to Recommendation:
	//	*Recommendation_CampaignBudgetRecommendation_
	//	*Recommendation_KeywordRecommendation_
	//	*Recommendation_TextAdRecommendation_
	//	*Recommendation_TargetCpaOptInRecommendation_
	Recommendation       isRecommendation_Recommendation `protobuf_oneof:"recommendation"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Recommendation) Reset()         { *m = Recommendation{} }
func (m *Recommendation) String() string { return proto.CompactTextString(m) }
func (*Recommendation) ProtoMessage()    {}
func (*Recommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0}
}
func (m *Recommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation.Unmarshal(m, b)
}
func (m *Recommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation.Marshal(b, m, deterministic)
}
func (m *Recommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation.Merge(m, src)
}
func (m *Recommendation) XXX_Size() int {
	return xxx_messageInfo_Recommendation.Size(m)
}
func (m *Recommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation proto.InternalMessageInfo

func (m *Recommendation) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *Recommendation) GetType() enums.RecommendationTypeEnum_RecommendationType {
	if m != nil {
		return m.Type
	}
	return enums.RecommendationTypeEnum_UNSPECIFIED
}

func (m *Recommendation) GetImpact() *Recommendation_RecommendationImpact {
	if m != nil {
		return m.Impact
	}
	return nil
}

func (m *Recommendation) GetCampaignBudget() *wrappers.StringValue {
	if m != nil {
		return m.CampaignBudget
	}
	return nil
}

func (m *Recommendation) GetCampaign() *wrappers.StringValue {
	if m != nil {
		return m.Campaign
	}
	return nil
}

func (m *Recommendation) GetAdGroup() *wrappers.StringValue {
	if m != nil {
		return m.AdGroup
	}
	return nil
}

type isRecommendation_Recommendation interface {
	isRecommendation_Recommendation()
}

type Recommendation_CampaignBudgetRecommendation_ struct {
	CampaignBudgetRecommendation *Recommendation_CampaignBudgetRecommendation `protobuf:"bytes,4,opt,name=campaign_budget_recommendation,json=campaignBudgetRecommendation,proto3,oneof"`
}

type Recommendation_KeywordRecommendation_ struct {
	KeywordRecommendation *Recommendation_KeywordRecommendation `protobuf:"bytes,8,opt,name=keyword_recommendation,json=keywordRecommendation,proto3,oneof"`
}

type Recommendation_TextAdRecommendation_ struct {
	TextAdRecommendation *Recommendation_TextAdRecommendation `protobuf:"bytes,9,opt,name=text_ad_recommendation,json=textAdRecommendation,proto3,oneof"`
}

type Recommendation_TargetCpaOptInRecommendation_ struct {
	TargetCpaOptInRecommendation *Recommendation_TargetCpaOptInRecommendation `protobuf:"bytes,10,opt,name=target_cpa_opt_in_recommendation,json=targetCpaOptInRecommendation,proto3,oneof"`
}

func (*Recommendation_CampaignBudgetRecommendation_) isRecommendation_Recommendation() {}

func (*Recommendation_KeywordRecommendation_) isRecommendation_Recommendation() {}

func (*Recommendation_TextAdRecommendation_) isRecommendation_Recommendation() {}

func (*Recommendation_TargetCpaOptInRecommendation_) isRecommendation_Recommendation() {}

func (m *Recommendation) GetRecommendation() isRecommendation_Recommendation {
	if m != nil {
		return m.Recommendation
	}
	return nil
}

func (m *Recommendation) GetCampaignBudgetRecommendation() *Recommendation_CampaignBudgetRecommendation {
	if x, ok := m.GetRecommendation().(*Recommendation_CampaignBudgetRecommendation_); ok {
		return x.CampaignBudgetRecommendation
	}
	return nil
}

func (m *Recommendation) GetKeywordRecommendation() *Recommendation_KeywordRecommendation {
	if x, ok := m.GetRecommendation().(*Recommendation_KeywordRecommendation_); ok {
		return x.KeywordRecommendation
	}
	return nil
}

func (m *Recommendation) GetTextAdRecommendation() *Recommendation_TextAdRecommendation {
	if x, ok := m.GetRecommendation().(*Recommendation_TextAdRecommendation_); ok {
		return x.TextAdRecommendation
	}
	return nil
}

func (m *Recommendation) GetTargetCpaOptInRecommendation() *Recommendation_TargetCpaOptInRecommendation {
	if x, ok := m.GetRecommendation().(*Recommendation_TargetCpaOptInRecommendation_); ok {
		return x.TargetCpaOptInRecommendation
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Recommendation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Recommendation_OneofMarshaler, _Recommendation_OneofUnmarshaler, _Recommendation_OneofSizer, []interface{}{
		(*Recommendation_CampaignBudgetRecommendation_)(nil),
		(*Recommendation_KeywordRecommendation_)(nil),
		(*Recommendation_TextAdRecommendation_)(nil),
		(*Recommendation_TargetCpaOptInRecommendation_)(nil),
	}
}

func _Recommendation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Recommendation)
	// recommendation
	switch x := m.Recommendation.(type) {
	case *Recommendation_CampaignBudgetRecommendation_:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CampaignBudgetRecommendation); err != nil {
			return err
		}
	case *Recommendation_KeywordRecommendation_:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.KeywordRecommendation); err != nil {
			return err
		}
	case *Recommendation_TextAdRecommendation_:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TextAdRecommendation); err != nil {
			return err
		}
	case *Recommendation_TargetCpaOptInRecommendation_:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TargetCpaOptInRecommendation); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Recommendation.Recommendation has unexpected type %T", x)
	}
	return nil
}

func _Recommendation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Recommendation)
	switch tag {
	case 4: // recommendation.campaign_budget_recommendation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Recommendation_CampaignBudgetRecommendation)
		err := b.DecodeMessage(msg)
		m.Recommendation = &Recommendation_CampaignBudgetRecommendation_{msg}
		return true, err
	case 8: // recommendation.keyword_recommendation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Recommendation_KeywordRecommendation)
		err := b.DecodeMessage(msg)
		m.Recommendation = &Recommendation_KeywordRecommendation_{msg}
		return true, err
	case 9: // recommendation.text_ad_recommendation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Recommendation_TextAdRecommendation)
		err := b.DecodeMessage(msg)
		m.Recommendation = &Recommendation_TextAdRecommendation_{msg}
		return true, err
	case 10: // recommendation.target_cpa_opt_in_recommendation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Recommendation_TargetCpaOptInRecommendation)
		err := b.DecodeMessage(msg)
		m.Recommendation = &Recommendation_TargetCpaOptInRecommendation_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Recommendation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Recommendation)
	// recommendation
	switch x := m.Recommendation.(type) {
	case *Recommendation_CampaignBudgetRecommendation_:
		s := proto.Size(x.CampaignBudgetRecommendation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Recommendation_KeywordRecommendation_:
		s := proto.Size(x.KeywordRecommendation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Recommendation_TextAdRecommendation_:
		s := proto.Size(x.TextAdRecommendation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Recommendation_TargetCpaOptInRecommendation_:
		s := proto.Size(x.TargetCpaOptInRecommendation)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// The impact of making the change as described in the recommendation.
// Some types of recommendations may not have impact information.
type Recommendation_RecommendationImpact struct {
	// Base metrics at the time the recommendation was generated.
	BaseMetrics *Recommendation_RecommendationMetrics `protobuf:"bytes,1,opt,name=base_metrics,json=baseMetrics,proto3" json:"base_metrics,omitempty"`
	// Estimated metrics if the recommendation is applied.
	PotentialMetrics     *Recommendation_RecommendationMetrics `protobuf:"bytes,2,opt,name=potential_metrics,json=potentialMetrics,proto3" json:"potential_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *Recommendation_RecommendationImpact) Reset()         { *m = Recommendation_RecommendationImpact{} }
func (m *Recommendation_RecommendationImpact) String() string { return proto.CompactTextString(m) }
func (*Recommendation_RecommendationImpact) ProtoMessage()    {}
func (*Recommendation_RecommendationImpact) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0, 0}
}
func (m *Recommendation_RecommendationImpact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation_RecommendationImpact.Unmarshal(m, b)
}
func (m *Recommendation_RecommendationImpact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation_RecommendationImpact.Marshal(b, m, deterministic)
}
func (m *Recommendation_RecommendationImpact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation_RecommendationImpact.Merge(m, src)
}
func (m *Recommendation_RecommendationImpact) XXX_Size() int {
	return xxx_messageInfo_Recommendation_RecommendationImpact.Size(m)
}
func (m *Recommendation_RecommendationImpact) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation_RecommendationImpact.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation_RecommendationImpact proto.InternalMessageInfo

func (m *Recommendation_RecommendationImpact) GetBaseMetrics() *Recommendation_RecommendationMetrics {
	if m != nil {
		return m.BaseMetrics
	}
	return nil
}

func (m *Recommendation_RecommendationImpact) GetPotentialMetrics() *Recommendation_RecommendationMetrics {
	if m != nil {
		return m.PotentialMetrics
	}
	return nil
}

// Weekly account performance metrics. For some recommendation types, these
// are averaged over the past 90-day period and hence can be fractional.
type Recommendation_RecommendationMetrics struct {
	// Number of ad impressions.
	Impressions *wrappers.DoubleValue `protobuf:"bytes,1,opt,name=impressions,proto3" json:"impressions,omitempty"`
	// Number of ad clicks.
	Clicks *wrappers.DoubleValue `protobuf:"bytes,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	// Cost (in micros) for advertising, in the local currency for the account.
	CostMicros *wrappers.Int64Value `protobuf:"bytes,3,opt,name=cost_micros,json=costMicros,proto3" json:"cost_micros,omitempty"`
	// Number of conversions.
	Conversions *wrappers.DoubleValue `protobuf:"bytes,4,opt,name=conversions,proto3" json:"conversions,omitempty"`
	// Number of video views for a video ad campaign.
	VideoViews           *wrappers.DoubleValue `protobuf:"bytes,5,opt,name=video_views,json=videoViews,proto3" json:"video_views,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Recommendation_RecommendationMetrics) Reset()         { *m = Recommendation_RecommendationMetrics{} }
func (m *Recommendation_RecommendationMetrics) String() string { return proto.CompactTextString(m) }
func (*Recommendation_RecommendationMetrics) ProtoMessage()    {}
func (*Recommendation_RecommendationMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0, 1}
}
func (m *Recommendation_RecommendationMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation_RecommendationMetrics.Unmarshal(m, b)
}
func (m *Recommendation_RecommendationMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation_RecommendationMetrics.Marshal(b, m, deterministic)
}
func (m *Recommendation_RecommendationMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation_RecommendationMetrics.Merge(m, src)
}
func (m *Recommendation_RecommendationMetrics) XXX_Size() int {
	return xxx_messageInfo_Recommendation_RecommendationMetrics.Size(m)
}
func (m *Recommendation_RecommendationMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation_RecommendationMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation_RecommendationMetrics proto.InternalMessageInfo

func (m *Recommendation_RecommendationMetrics) GetImpressions() *wrappers.DoubleValue {
	if m != nil {
		return m.Impressions
	}
	return nil
}

func (m *Recommendation_RecommendationMetrics) GetClicks() *wrappers.DoubleValue {
	if m != nil {
		return m.Clicks
	}
	return nil
}

func (m *Recommendation_RecommendationMetrics) GetCostMicros() *wrappers.Int64Value {
	if m != nil {
		return m.CostMicros
	}
	return nil
}

func (m *Recommendation_RecommendationMetrics) GetConversions() *wrappers.DoubleValue {
	if m != nil {
		return m.Conversions
	}
	return nil
}

func (m *Recommendation_RecommendationMetrics) GetVideoViews() *wrappers.DoubleValue {
	if m != nil {
		return m.VideoViews
	}
	return nil
}

// The budget recommendation for budget constrained campaigns.
type Recommendation_CampaignBudgetRecommendation struct {
	// The current budget amount in micros.
	CurrentBudgetAmountMicros *wrappers.Int64Value `protobuf:"bytes,1,opt,name=current_budget_amount_micros,json=currentBudgetAmountMicros,proto3" json:"current_budget_amount_micros,omitempty"`
	// The recommended budget amount in micros.
	RecommendedBudgetAmountMicros *wrappers.Int64Value `protobuf:"bytes,2,opt,name=recommended_budget_amount_micros,json=recommendedBudgetAmountMicros,proto3" json:"recommended_budget_amount_micros,omitempty"`
	// The budget amounts and associated impact estimates for some values of
	// possible budget amounts.
	BudgetOptions        []*Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption `protobuf:"bytes,3,rep,name=budget_options,json=budgetOptions,proto3" json:"budget_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                                          `json:"-"`
	XXX_unrecognized     []byte                                                                            `json:"-"`
	XXX_sizecache        int32                                                                             `json:"-"`
}

func (m *Recommendation_CampaignBudgetRecommendation) Reset() {
	*m = Recommendation_CampaignBudgetRecommendation{}
}
func (m *Recommendation_CampaignBudgetRecommendation) String() string {
	return proto.CompactTextString(m)
}
func (*Recommendation_CampaignBudgetRecommendation) ProtoMessage() {}
func (*Recommendation_CampaignBudgetRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0, 2}
}
func (m *Recommendation_CampaignBudgetRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation_CampaignBudgetRecommendation.Unmarshal(m, b)
}
func (m *Recommendation_CampaignBudgetRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation_CampaignBudgetRecommendation.Marshal(b, m, deterministic)
}
func (m *Recommendation_CampaignBudgetRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation_CampaignBudgetRecommendation.Merge(m, src)
}
func (m *Recommendation_CampaignBudgetRecommendation) XXX_Size() int {
	return xxx_messageInfo_Recommendation_CampaignBudgetRecommendation.Size(m)
}
func (m *Recommendation_CampaignBudgetRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation_CampaignBudgetRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation_CampaignBudgetRecommendation proto.InternalMessageInfo

func (m *Recommendation_CampaignBudgetRecommendation) GetCurrentBudgetAmountMicros() *wrappers.Int64Value {
	if m != nil {
		return m.CurrentBudgetAmountMicros
	}
	return nil
}

func (m *Recommendation_CampaignBudgetRecommendation) GetRecommendedBudgetAmountMicros() *wrappers.Int64Value {
	if m != nil {
		return m.RecommendedBudgetAmountMicros
	}
	return nil
}

func (m *Recommendation_CampaignBudgetRecommendation) GetBudgetOptions() []*Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption {
	if m != nil {
		return m.BudgetOptions
	}
	return nil
}

// The impact estimates for a given budget amount.
type Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption struct {
	// The budget amount for this option.
	BudgetAmountMicros *wrappers.Int64Value `protobuf:"bytes,1,opt,name=budget_amount_micros,json=budgetAmountMicros,proto3" json:"budget_amount_micros,omitempty"`
	// The impact estimate if budget is changed to amount specified in this
	// option.
	Impact               *Recommendation_RecommendationImpact `protobuf:"bytes,2,opt,name=impact,proto3" json:"impact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) Reset() {
	*m = Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption{}
}
func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) String() string {
	return proto.CompactTextString(m)
}
func (*Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) ProtoMessage() {
}
func (*Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0, 2, 0}
}
func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption.Unmarshal(m, b)
}
func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption.Marshal(b, m, deterministic)
}
func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption.Merge(m, src)
}
func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) XXX_Size() int {
	return xxx_messageInfo_Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption.Size(m)
}
func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption proto.InternalMessageInfo

func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) GetBudgetAmountMicros() *wrappers.Int64Value {
	if m != nil {
		return m.BudgetAmountMicros
	}
	return nil
}

func (m *Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption) GetImpact() *Recommendation_RecommendationImpact {
	if m != nil {
		return m.Impact
	}
	return nil
}

// The keyword recommendation.
type Recommendation_KeywordRecommendation struct {
	// The recommended keyword.
	Keyword *common.KeywordInfo `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// The recommended CPC (cost-per-click) bid.
	RecommendedCpcBidMicros *wrappers.Int64Value `protobuf:"bytes,2,opt,name=recommended_cpc_bid_micros,json=recommendedCpcBidMicros,proto3" json:"recommended_cpc_bid_micros,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}             `json:"-"`
	XXX_unrecognized        []byte               `json:"-"`
	XXX_sizecache           int32                `json:"-"`
}

func (m *Recommendation_KeywordRecommendation) Reset()         { *m = Recommendation_KeywordRecommendation{} }
func (m *Recommendation_KeywordRecommendation) String() string { return proto.CompactTextString(m) }
func (*Recommendation_KeywordRecommendation) ProtoMessage()    {}
func (*Recommendation_KeywordRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0, 3}
}
func (m *Recommendation_KeywordRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation_KeywordRecommendation.Unmarshal(m, b)
}
func (m *Recommendation_KeywordRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation_KeywordRecommendation.Marshal(b, m, deterministic)
}
func (m *Recommendation_KeywordRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation_KeywordRecommendation.Merge(m, src)
}
func (m *Recommendation_KeywordRecommendation) XXX_Size() int {
	return xxx_messageInfo_Recommendation_KeywordRecommendation.Size(m)
}
func (m *Recommendation_KeywordRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation_KeywordRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation_KeywordRecommendation proto.InternalMessageInfo

func (m *Recommendation_KeywordRecommendation) GetKeyword() *common.KeywordInfo {
	if m != nil {
		return m.Keyword
	}
	return nil
}

func (m *Recommendation_KeywordRecommendation) GetRecommendedCpcBidMicros() *wrappers.Int64Value {
	if m != nil {
		return m.RecommendedCpcBidMicros
	}
	return nil
}

// The text ad recommendation.
type Recommendation_TextAdRecommendation struct {
	// Recommended ad.
	Ad *common.Ad `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	// Creation date of the recommended ad.
	// YYYY-MM-DD format, e.g., 2018-04-17.
	CreationDate *wrappers.StringValue `protobuf:"bytes,2,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	// Date, if present, is the earliest when the recommendation will be auto
	// applied.
	// YYYY-MM-DD format, e.g., 2018-04-17.
	AutoApplyDate        *wrappers.StringValue `protobuf:"bytes,3,opt,name=auto_apply_date,json=autoApplyDate,proto3" json:"auto_apply_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Recommendation_TextAdRecommendation) Reset()         { *m = Recommendation_TextAdRecommendation{} }
func (m *Recommendation_TextAdRecommendation) String() string { return proto.CompactTextString(m) }
func (*Recommendation_TextAdRecommendation) ProtoMessage()    {}
func (*Recommendation_TextAdRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0, 4}
}
func (m *Recommendation_TextAdRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation_TextAdRecommendation.Unmarshal(m, b)
}
func (m *Recommendation_TextAdRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation_TextAdRecommendation.Marshal(b, m, deterministic)
}
func (m *Recommendation_TextAdRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation_TextAdRecommendation.Merge(m, src)
}
func (m *Recommendation_TextAdRecommendation) XXX_Size() int {
	return xxx_messageInfo_Recommendation_TextAdRecommendation.Size(m)
}
func (m *Recommendation_TextAdRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation_TextAdRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation_TextAdRecommendation proto.InternalMessageInfo

func (m *Recommendation_TextAdRecommendation) GetAd() *common.Ad {
	if m != nil {
		return m.Ad
	}
	return nil
}

func (m *Recommendation_TextAdRecommendation) GetCreationDate() *wrappers.StringValue {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *Recommendation_TextAdRecommendation) GetAutoApplyDate() *wrappers.StringValue {
	if m != nil {
		return m.AutoApplyDate
	}
	return nil
}

// The Target CPA opt-in recommendation.
type Recommendation_TargetCpaOptInRecommendation struct {
	// The available goals and corresponding options for Target CPA strategy.
	Options []*Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	// The recommended average CPA target. See required budget amount and impact
	// of using this recommendation in options list.
	RecommendedTargetCpaMicros *wrappers.Int64Value `protobuf:"bytes,2,opt,name=recommended_target_cpa_micros,json=recommendedTargetCpaMicros,proto3" json:"recommended_target_cpa_micros,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}             `json:"-"`
	XXX_unrecognized           []byte               `json:"-"`
	XXX_sizecache              int32                `json:"-"`
}

func (m *Recommendation_TargetCpaOptInRecommendation) Reset() {
	*m = Recommendation_TargetCpaOptInRecommendation{}
}
func (m *Recommendation_TargetCpaOptInRecommendation) String() string {
	return proto.CompactTextString(m)
}
func (*Recommendation_TargetCpaOptInRecommendation) ProtoMessage() {}
func (*Recommendation_TargetCpaOptInRecommendation) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0, 5}
}
func (m *Recommendation_TargetCpaOptInRecommendation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation.Unmarshal(m, b)
}
func (m *Recommendation_TargetCpaOptInRecommendation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation.Marshal(b, m, deterministic)
}
func (m *Recommendation_TargetCpaOptInRecommendation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation.Merge(m, src)
}
func (m *Recommendation_TargetCpaOptInRecommendation) XXX_Size() int {
	return xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation.Size(m)
}
func (m *Recommendation_TargetCpaOptInRecommendation) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation proto.InternalMessageInfo

func (m *Recommendation_TargetCpaOptInRecommendation) GetOptions() []*Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Recommendation_TargetCpaOptInRecommendation) GetRecommendedTargetCpaMicros() *wrappers.Int64Value {
	if m != nil {
		return m.RecommendedTargetCpaMicros
	}
	return nil
}

// The Target CPA opt-in option with impact estimate.
type Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption struct {
	// The goal achieved by this option.
	Goal enums.TargetCpaOptInRecommendationGoalEnum_TargetCpaOptInRecommendationGoal `protobuf:"varint,1,opt,name=goal,proto3,enum=google.ads.googleads.v0.enums.TargetCpaOptInRecommendationGoalEnum_TargetCpaOptInRecommendationGoal" json:"goal,omitempty"`
	// Average CPA target.
	TargetCpaMicros *wrappers.Int64Value `protobuf:"bytes,2,opt,name=target_cpa_micros,json=targetCpaMicros,proto3" json:"target_cpa_micros,omitempty"`
	// The minimum campaign budget, in local currency for the account,
	// required to achieve the target CPA.
	// Amount is specified in micros, where one million is equivalent to one
	// currency unit.
	RequiredCampaignBudgetAmountMicros *wrappers.Int64Value `protobuf:"bytes,3,opt,name=required_campaign_budget_amount_micros,json=requiredCampaignBudgetAmountMicros,proto3" json:"required_campaign_budget_amount_micros,omitempty"`
	// The impact estimate if this option is selected.
	Impact               *Recommendation_RecommendationImpact `protobuf:"bytes,4,opt,name=impact,proto3" json:"impact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) Reset() {
	*m = Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption{}
}
func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) String() string {
	return proto.CompactTextString(m)
}
func (*Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) ProtoMessage() {
}
func (*Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd2e1170b8a3fab0, []int{0, 5, 0}
}
func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption.Unmarshal(m, b)
}
func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption.Marshal(b, m, deterministic)
}
func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption.Merge(m, src)
}
func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) XXX_Size() int {
	return xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption.Size(m)
}
func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) XXX_DiscardUnknown() {
	xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption.DiscardUnknown(m)
}

var xxx_messageInfo_Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption proto.InternalMessageInfo

func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) GetGoal() enums.TargetCpaOptInRecommendationGoalEnum_TargetCpaOptInRecommendationGoal {
	if m != nil {
		return m.Goal
	}
	return enums.TargetCpaOptInRecommendationGoalEnum_UNSPECIFIED
}

func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) GetTargetCpaMicros() *wrappers.Int64Value {
	if m != nil {
		return m.TargetCpaMicros
	}
	return nil
}

func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) GetRequiredCampaignBudgetAmountMicros() *wrappers.Int64Value {
	if m != nil {
		return m.RequiredCampaignBudgetAmountMicros
	}
	return nil
}

func (m *Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption) GetImpact() *Recommendation_RecommendationImpact {
	if m != nil {
		return m.Impact
	}
	return nil
}

func init() {
	proto.RegisterType((*Recommendation)(nil), "google.ads.googleads.v0.resources.Recommendation")
	proto.RegisterType((*Recommendation_RecommendationImpact)(nil), "google.ads.googleads.v0.resources.Recommendation.RecommendationImpact")
	proto.RegisterType((*Recommendation_RecommendationMetrics)(nil), "google.ads.googleads.v0.resources.Recommendation.RecommendationMetrics")
	proto.RegisterType((*Recommendation_CampaignBudgetRecommendation)(nil), "google.ads.googleads.v0.resources.Recommendation.CampaignBudgetRecommendation")
	proto.RegisterType((*Recommendation_CampaignBudgetRecommendation_CampaignBudgetRecommendationOption)(nil), "google.ads.googleads.v0.resources.Recommendation.CampaignBudgetRecommendation.CampaignBudgetRecommendationOption")
	proto.RegisterType((*Recommendation_KeywordRecommendation)(nil), "google.ads.googleads.v0.resources.Recommendation.KeywordRecommendation")
	proto.RegisterType((*Recommendation_TextAdRecommendation)(nil), "google.ads.googleads.v0.resources.Recommendation.TextAdRecommendation")
	proto.RegisterType((*Recommendation_TargetCpaOptInRecommendation)(nil), "google.ads.googleads.v0.resources.Recommendation.TargetCpaOptInRecommendation")
	proto.RegisterType((*Recommendation_TargetCpaOptInRecommendation_TargetCpaOptInRecommendationOption)(nil), "google.ads.googleads.v0.resources.Recommendation.TargetCpaOptInRecommendation.TargetCpaOptInRecommendationOption")
}

func init() {
	proto.RegisterFile("google/ads/googleads/v0/resources/recommendation.proto", fileDescriptor_dd2e1170b8a3fab0)
}

var fileDescriptor_dd2e1170b8a3fab0 = []byte{
	// 1054 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x2e, 0x25, 0xc5, 0x76, 0x46, 0xb6, 0x9c, 0x6c, 0xed, 0x54, 0x51, 0xd5, 0x40, 0x51, 0xd1,
	0xd6, 0x40, 0x51, 0xca, 0x50, 0x83, 0xa4, 0x87, 0xb6, 0x80, 0x64, 0xbb, 0x8a, 0x50, 0x38, 0x09,
	0x58, 0xc3, 0xe8, 0x41, 0x08, 0xb1, 0x22, 0x37, 0x02, 0x6b, 0x91, 0xbb, 0x59, 0x2e, 0x65, 0xfb,
	0x52, 0xf4, 0xde, 0x7b, 0x91, 0x73, 0x8f, 0x3d, 0xf5, 0x98, 0x37, 0x28, 0x90, 0x6b, 0xde, 0xa0,
	0x2f, 0xd0, 0x6b, 0x8f, 0x05, 0x97, 0x3f, 0x25, 0xf5, 0x43, 0xca, 0x42, 0x7c, 0xe3, 0xee, 0xce,
	0xf7, 0xcd, 0x37, 0x33, 0x9c, 0xd9, 0x85, 0x87, 0x23, 0x4a, 0x47, 0x63, 0xd2, 0xc2, 0xa6, 0xdb,
	0x0a, 0x3e, 0xfd, 0xaf, 0xc9, 0x7e, 0x8b, 0x13, 0x97, 0x7a, 0xdc, 0x20, 0x6e, 0x8b, 0x13, 0x83,
	0xda, 0x36, 0x71, 0x4c, 0x2c, 0x2c, 0xea, 0xa8, 0x8c, 0x53, 0x41, 0xd1, 0xfd, 0xc0, 0x58, 0xc5,
	0xa6, 0xab, 0xc6, 0x38, 0x75, 0xb2, 0xaf, 0xc6, 0xb8, 0xda, 0x67, 0x8b, 0xa8, 0x7d, 0x3a, 0xea,
	0xb4, 0xb0, 0x19, 0x70, 0xd5, 0xbe, 0xc8, 0x31, 0x34, 0xb8, 0x25, 0x08, 0xb7, 0x70, 0x68, 0xfe,
	0x68, 0x91, 0x39, 0x71, 0x3c, 0x7b, 0x5a, 0xae, 0x2e, 0x2e, 0x19, 0x09, 0x81, 0xfd, 0x6c, 0xa0,
	0xc0, 0x7c, 0x44, 0x84, 0x6e, 0x30, 0xac, 0x53, 0x26, 0x74, 0xcb, 0xd1, 0xa7, 0xa8, 0x46, 0x14,
	0x8f, 0x43, 0xaa, 0x7b, 0x21, 0x95, 0x5c, 0x0d, 0xbd, 0x17, 0xad, 0x73, 0x8e, 0x19, 0x23, 0xdc,
	0x0d, 0xce, 0x9b, 0xff, 0xdc, 0x85, 0x8a, 0x96, 0x42, 0xa3, 0x8f, 0x61, 0x2b, 0xca, 0x8d, 0xee,
	0x60, 0x9b, 0x54, 0x95, 0x86, 0xb2, 0x77, 0x53, 0xdb, 0x8c, 0x36, 0x9f, 0x60, 0x9b, 0xa0, 0x01,
	0x94, 0x7c, 0xc1, 0xd5, 0x42, 0x43, 0xd9, 0xab, 0xb4, 0x1f, 0xab, 0x8b, 0xb2, 0x2c, 0x15, 0xab,
	0x69, 0x0f, 0x27, 0x97, 0x8c, 0x1c, 0x39, 0x9e, 0x3d, 0x67, 0x5b, 0x93, 0xac, 0xe8, 0x39, 0xac,
	0x59, 0x36, 0xc3, 0x86, 0xa8, 0x16, 0x1b, 0xca, 0x5e, 0xb9, 0xfd, 0x9d, 0x9a, 0x5b, 0xc5, 0x29,
	0xb2, 0xa9, 0x65, 0x5f, 0xb2, 0x69, 0x21, 0x2b, 0x3a, 0x82, 0x6d, 0x03, 0xdb, 0x0c, 0x5b, 0x23,
	0x47, 0x1f, 0x7a, 0xe6, 0x88, 0x88, 0xea, 0x0d, 0xe9, 0xa8, 0x1e, 0x39, 0x8a, 0xf2, 0xa5, 0xfe,
	0x20, 0xb8, 0xe5, 0x8c, 0x4e, 0xf1, 0xd8, 0x23, 0x5a, 0x25, 0x02, 0x75, 0x25, 0x06, 0x7d, 0x05,
	0x1b, 0xd1, 0x4e, 0x75, 0x6d, 0x09, 0x7c, 0x6c, 0x8d, 0x1e, 0xc1, 0x06, 0x36, 0xf5, 0x11, 0xa7,
	0x1e, 0xab, 0xae, 0x2f, 0x81, 0x5c, 0xc7, 0x66, 0xcf, 0x37, 0x46, 0xbf, 0x29, 0x70, 0x6f, 0x4a,
	0xfa, 0x54, 0xf5, 0xab, 0x25, 0xc9, 0xf7, 0xe4, 0xea, 0x29, 0x3b, 0x48, 0x45, 0x97, 0x3e, 0x7c,
	0xfc, 0x9e, 0x56, 0x37, 0x32, 0xce, 0xd1, 0x2f, 0x0a, 0xdc, 0x39, 0x23, 0x97, 0xe7, 0x94, 0x9b,
	0xd3, 0x82, 0x36, 0xa4, 0xa0, 0xde, 0xd5, 0x05, 0x7d, 0x1f, 0xf0, 0xcd, 0x28, 0xd9, 0x3d, 0x9b,
	0x77, 0x80, 0x7e, 0x86, 0x3b, 0x82, 0x5c, 0x08, 0x1d, 0xcf, 0x28, 0xb8, 0xb9, 0xea, 0x5f, 0x74,
	0x42, 0x2e, 0x44, 0x67, 0x56, 0xc0, 0x8e, 0x98, 0xb3, 0x8f, 0x5e, 0x29, 0xd0, 0xc8, 0xeb, 0xcd,
	0x2a, 0xac, 0x5a, 0x9d, 0x13, 0xc9, 0x7c, 0xc0, 0xf0, 0x53, 0x26, 0xfa, 0xce, 0x6c, 0x75, 0x44,
	0xc6, 0x79, 0xed, 0x5f, 0x05, 0x76, 0xe6, 0x75, 0x04, 0xfa, 0x09, 0x36, 0x87, 0xd8, 0x25, 0xba,
	0x4d, 0x04, 0xb7, 0x0c, 0x57, 0xf6, 0xfa, 0x4a, 0xb5, 0x4a, 0x2f, 0x8f, 0x03, 0x3a, 0xad, 0xec,
	0x93, 0x87, 0x0b, 0x24, 0xe0, 0x36, 0xa3, 0x82, 0x38, 0xc2, 0xc2, 0xe3, 0xd8, 0x61, 0xe1, 0xdd,
	0x3a, 0xbc, 0x15, 0x7b, 0x08, 0x77, 0x6a, 0x6f, 0x0a, 0xb0, 0x3b, 0xd7, 0x16, 0x7d, 0x0b, 0x65,
	0xcb, 0x66, 0x9c, 0xb8, 0xae, 0x45, 0x9d, 0x28, 0xf4, 0xd9, 0x3e, 0x3c, 0xa4, 0xde, 0x70, 0x4c,
	0x82, 0x3e, 0x4c, 0x02, 0xd0, 0x03, 0x58, 0x33, 0xc6, 0x96, 0x71, 0x16, 0x05, 0x91, 0x0d, 0x0d,
	0x6d, 0xd1, 0xd7, 0x50, 0x36, 0xa8, 0x2b, 0x74, 0xdb, 0x32, 0x38, 0x75, 0xc3, 0x01, 0xf7, 0xe1,
	0x0c, 0xb4, 0xef, 0x88, 0x87, 0x0f, 0x02, 0x24, 0xf8, 0xf6, 0xc7, 0xd2, 0xdc, 0xd7, 0x6c, 0x50,
	0x67, 0x42, 0x78, 0xa0, 0xb9, 0xb4, 0x8c, 0xe6, 0x04, 0x00, 0x7d, 0x03, 0xe5, 0x89, 0x65, 0x12,
	0xaa, 0x4f, 0x2c, 0x72, 0xee, 0x2e, 0x9c, 0x7a, 0x49, 0x3c, 0x48, 0xc0, 0xa9, 0x6f, 0x5f, 0x7b,
	0x5b, 0x82, 0x7a, 0xd6, 0x98, 0x40, 0x03, 0xa8, 0x1b, 0x1e, 0xe7, 0xc4, 0x11, 0xd1, 0x74, 0xc2,
	0x36, 0xf5, 0x9c, 0x38, 0x5c, 0x25, 0x3f, 0xdc, 0xbb, 0x21, 0x41, 0xc0, 0xdf, 0x91, 0xf0, 0x30,
	0x7a, 0x13, 0x1a, 0x71, 0x3b, 0x11, 0x73, 0xbe, 0x87, 0x42, 0xbe, 0x87, 0x8f, 0x12, 0x24, 0x73,
	0xbc, 0xbc, 0x52, 0xa0, 0x12, 0x52, 0x53, 0x26, 0x64, 0x9e, 0x8b, 0x8d, 0xe2, 0x5e, 0xb9, 0xfd,
	0xf2, 0xdd, 0xce, 0xd4, 0xcc, 0xc3, 0xa7, 0xd2, 0xb3, 0xb6, 0x15, 0x08, 0x09, 0x56, 0x6e, 0xed,
	0xad, 0x02, 0xcd, 0x7c, 0x14, 0x3a, 0x86, 0x9d, 0x55, 0xb3, 0x8f, 0x86, 0xb3, 0x09, 0xf9, 0xff,
	0x3a, 0x2e, 0x5c, 0xc7, 0x75, 0x5c, 0x7b, 0xad, 0xc0, 0xee, 0xdc, 0x59, 0x8f, 0x8e, 0x60, 0x3d,
	0x9c, 0xf5, 0xa1, 0xf6, 0xcf, 0x17, 0xba, 0x0e, 0xde, 0x60, 0xd1, 0x9d, 0xd1, 0x77, 0x5e, 0x50,
	0x2d, 0xc2, 0xa2, 0x1f, 0xa1, 0x96, 0xfc, 0x6f, 0x0c, 0x66, 0xe8, 0x43, 0xcb, 0xbc, 0xc2, 0x1f,
	0xf3, 0x41, 0x02, 0x7e, 0xc0, 0x8c, 0xae, 0x65, 0x06, 0xa9, 0xf1, 0x0b, 0xb2, 0x33, 0xef, 0x92,
	0x40, 0x6d, 0x28, 0xe0, 0x48, 0x74, 0x33, 0x4f, 0x74, 0xc7, 0xd4, 0x0a, 0xd8, 0x44, 0x1d, 0xd8,
	0x32, 0x38, 0x09, 0xde, 0x70, 0x26, 0x16, 0x64, 0xe1, 0x5c, 0x49, 0x3e, 0x0d, 0x36, 0x23, 0xc8,
	0x21, 0x16, 0x04, 0x1d, 0xc2, 0x36, 0xf6, 0x04, 0xd5, 0x31, 0x63, 0xe3, 0xcb, 0x80, 0xa4, 0xb8,
	0x04, 0xc9, 0x96, 0x0f, 0xea, 0xf8, 0x18, 0x9f, 0xa5, 0xf6, 0xd7, 0x0d, 0xa8, 0x67, 0xdd, 0x37,
	0xe8, 0x57, 0x05, 0xd6, 0xa3, 0xde, 0x50, 0x56, 0xed, 0x8d, 0x2c, 0x0f, 0x99, 0x87, 0x61, 0x6f,
	0x44, 0x0a, 0xd0, 0x73, 0x48, 0x76, 0xb4, 0x9e, 0xb8, 0x83, 0x97, 0xaf, 0x70, 0xf2, 0x07, 0x89,
	0x7d, 0x87, 0x45, 0x7e, 0x5d, 0x84, 0x66, 0xbe, 0x1e, 0x74, 0x01, 0x25, 0xff, 0xe5, 0x2d, 0x8b,
	0x5e, 0x69, 0x9b, 0x39, 0x6f, 0xe2, 0x2c, 0xc2, 0x1e, 0xc5, 0x63, 0xf9, 0x42, 0xce, 0x33, 0xd2,
	0xa4, 0x47, 0xd4, 0x83, 0xdb, 0x2b, 0x05, 0xbd, 0x2d, 0xd2, 0x91, 0x22, 0x0a, 0x9f, 0x72, 0xf2,
	0xd2, 0xb3, 0xb8, 0xdf, 0x25, 0x53, 0xcf, 0xcc, 0xf4, 0x28, 0x59, 0xe2, 0xde, 0x6a, 0x46, 0x54,
	0xe9, 0x89, 0xb5, 0x60, 0xb4, 0x94, 0xae, 0x63, 0xb4, 0x74, 0x6f, 0x41, 0x25, 0xfd, 0x00, 0xeb,
	0xfe, 0xa9, 0xc0, 0x27, 0x06, 0xb5, 0xf3, 0xfd, 0x74, 0xdf, 0x4f, 0x33, 0x3f, 0xf3, 0x43, 0x7c,
	0xa6, 0xfc, 0x5e, 0x28, 0xf6, 0x3a, 0x9d, 0x3f, 0x0a, 0xf7, 0x7b, 0x01, 0x41, 0xc7, 0x74, 0xd5,
	0xe0, 0xd3, 0xff, 0x3a, 0xdd, 0x57, 0xb5, 0x88, 0xe0, 0x4d, 0x64, 0x33, 0xe8, 0x98, 0xee, 0x20,
	0xb6, 0x19, 0x9c, 0xee, 0x0f, 0x62, 0x9b, 0xbf, 0x97, 0xb0, 0x19, 0xae, 0xc9, 0xec, 0x7e, 0xf9,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0xed, 0x16, 0xde, 0x04, 0x0f, 0x00, 0x00,
}
